// Contract suite for cash-book. Generated shape, mechanical assertions only.
//
// Asserts the invariants of servers/cash-book/SPEC.md that a test can check without
// judgement: one version number across package.json, src/version.ts, serverInfo and all
// four registry manifests; the remotes rule (the mcpb manifest carries remotes.json, the
// stdio-only names carry none); JSON-RPC-only stdout; tool-description hygiene; the
// free/Pro tier switch; that the six sibling stores are read and never written; and that
// the record shapes this suite seeds still match the ones those servers declare. It never
// asserts a number a human chose; those live in test/unit.test.mjs.
import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { readFileSync, statSync } from "node:fs";
import { join } from "node:path";
import { client, sandbox, cleanup, proKey, workedMonth, storeDir, seed, PERIOD, REPO } from "./_client.mjs";

const HERE = join(REPO, "servers", "cash-book");
const PRODUCT = "cash-book";
const MAX_DESCRIPTION = 220;
const HARD_MAX_DESCRIPTION = 1200;
const FILE_ARGS = ["path", "url", "out_path", "template_path"];
const IMPERATIVE = /^(Call this tool|Use this)\b/;

/**
 * Tools that already break the two description rules on the day this suite was written.
 * The suite is a ratchet: an existing entry is reported, a NEW one fails. Both lists are
 * defects; the fix is in src, not here.
 */
const OVER_LENGTH_BASELINE = [];
const NON_IMPERATIVE_BASELINE = [];

function open(t, opts = {}) {
  const box = sandbox();
  const c = client({ dataHome: box.dataHome, ...opts });
  t.after(() => { c.close(); cleanup(box.dir); });
  return { box, c };
}

test("the version is one number: package.json, src/version.ts, serverInfo and every manifest agree", async (t) => {
  const pkg = JSON.parse(readFileSync(join(HERE, "package.json"), "utf8"));
  assert.equal(pkg.name, "@theluckystrike/mcp-cash-book");
  assert.ok(pkg.description.length < 100, `package description is ${pkg.description.length} chars`);
  const generated = readFileSync(join(HERE, "src", "version.ts"), "utf8");
  assert.match(generated, /GENERATED by scripts\/sync-versions\.mjs/, "version.ts must be generated, not hand written");
  assert.match(generated, new RegExp(`export const VERSION = "${pkg.version.replace(/\./g, "\\.")}";`),
    `src/version.ts does not carry ${pkg.version}; run node scripts/sync-versions.mjs`);

  const { c } = open(t);
  const info = await c.init();
  assert.equal(info.serverInfo.version, pkg.version, "serverInfo.version must equal the package version");
  assert.equal(info.serverInfo.name, "mcp-cash-book");

  for (const file of ["server.json", "server.mcpb.json", "server.variant.json", "server.trial-balance.json"]) {
    const j = JSON.parse(readFileSync(join(HERE, file), "utf8"));
    assert.equal(j.version, pkg.version, `${file} version`);
    for (const p of j.packages ?? []) {
      assert.equal(p.version, pkg.version, `${file} package entry version`);
      assert.equal(p.transport.type, "stdio", `${file} declares a transport this server does not speak`);
      if (p.registryType === "mcpb") {
        // "TBD" until the release job hashes the bundle; after that, a real sha256.
        assert.ok(p.fileSha256 === "TBD" || /^[0-9a-f]{64}$/.test(p.fileSha256),
          `${file} fileSha256 is neither TBD nor a sha256: ${p.fileSha256}`);
      }
    }
    if (file === "server.mcpb.json") {
      const remotes = JSON.parse(readFileSync(join(HERE, "remotes.json"), "utf8"));
      assert.deepEqual(j.remotes, remotes, `${file} remotes must equal remotes.json (hosted at /mcp/cash-book)`);
      assert.equal(remotes[0].url, "https://mcp.zovo.one/mcp/cash-book");
    } else {
      assert.equal(j.remotes, undefined, `${file} is a stdio-only name and must not advertise a remote`);
    }
    assert.ok((j.description ?? "").length < 100, `${file} description is ${(j.description ?? "").length} chars; the registry 422s at 100`);
    assert.ok(!/[,.]\.$|,$/.test(j.description), `${file} description ends in a machine truncation`);
  }
  // Three distinct registry names, so the second and third are second listings, not copies.
  const names = ["server.json", "server.variant.json", "server.trial-balance.json"]
    .map((f) => JSON.parse(readFileSync(join(HERE, f), "utf8")).name);
  assert.equal(new Set(names).size, 3, `registry names must differ: ${names.join(", ")}`);
  assert.deepEqual(names, [
    "io.github.theluckystrike/cash-book",
    "io.github.theluckystrike/ledger",
    "io.github.theluckystrike/trial-balance",
  ]);

  // And sync-versions --check passes for the whole repo, so no sibling drifted either.
  execFileSync(process.execPath, [join(REPO, "scripts", "sync-versions.mjs"), "--check"], { encoding: "utf8" });
});

test("stdout carries JSON-RPC only across initialize, tools/list, a success and an error", async (t) => {
  const { box, c } = open(t);
  workedMonth(box.dataHome);
  await c.init();
  await c.tools();
  await c.call("trial_balance", PERIOD);
  await c.call("trial_balance", { from: "2026-06-30", to: "2026-06-01" });
  await new Promise((r) => setTimeout(r, 150));

  const lines = [...c.stdoutLines, c.tail].filter((l) => l.trim() !== "");
  assert.ok(lines.length >= 4, `expected at least 4 protocol lines, got ${lines.length}`);
  for (const line of lines) {
    let m;
    try { m = JSON.parse(line); } catch { assert.fail(`non-JSON on stdout: ${JSON.stringify(line.slice(0, 200))}`); }
    assert.equal(m.jsonrpc, "2.0", `stdout line is JSON but not JSON-RPC: ${line.slice(0, 200)}`);
  }
});

test("every tool description is non-empty, single-paragraph, and within the ceiling", async (t) => {
  const { c } = open(t);
  await c.init();
  const tools = await c.tools();
  assert.equal(tools.length, 8, "tool count changed; update servers/cash-book/SPEC.md");
  assert.deepEqual(tools.map((x) => x.name).sort(), [
    "ledger_build", "ledger_export_csv", "ledger_lines", "ledger_report",
    "license_activate", "license_status", "month_close", "trial_balance",
  ]);

  for (const tool of tools) {
    const d = tool.description ?? "";
    assert.ok(d.trim().length > 0, `${tool.name} has no description`);
    assert.equal(d, d.trim(), `${tool.name} description has leading or trailing whitespace`);
    assert.ok(d.length <= HARD_MAX_DESCRIPTION, `${tool.name} description is ${d.length} chars, over ${HARD_MAX_DESCRIPTION}`);
    assert.ok(!/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/u.test(d), `${tool.name} description carries an emoji`);
    assert.ok(!/[—]/.test(d), `${tool.name} description carries an em dash`);
  }

  const over = tools.filter((x) => (x.description ?? "").length > MAX_DESCRIPTION).map((x) => x.name).sort();
  const regressions = over.filter((n) => !OVER_LENGTH_BASELINE.includes(n));
  assert.deepEqual(regressions, [], `new tool descriptions over ${MAX_DESCRIPTION} chars`);
});

test("no tool takes a file path, so nothing here writes outside its own data directory", async (t) => {
  const { c } = open(t);
  await c.init();
  const tools = await c.tools();
  const fileTools = tools.filter((x) => Object.keys(x.inputSchema?.properties ?? {}).some((k) => FILE_ARGS.includes(k)));
  assert.deepEqual(fileTools.map((x) => x.name), []);
  const offenders = fileTools.filter((x) => !IMPERATIVE.test(x.description ?? "")).map((x) => x.name).sort();
  assert.deepEqual(offenders.filter((n) => !NON_IMPERATIVE_BASELINE.includes(n)), []);
});

test("license_status reports free with no key and pro with a signed key", async (t) => {
  const { c: free } = open(t);
  await free.init();
  const f = await free.call("license_status", {});
  assert.equal(f.isError, false, f.text);
  assert.match(f.text, /"tier":\s*"free"/, f.text.slice(0, 300));

  const key = proKey(PRODUCT);
  assert.match(key, /^MCPL1\./);
  const { c: pro } = open(t, { key });
  await pro.init();
  assert.match((await pro.call("license_status", {})).text, /"tier":\s*"pro"/);
});

test("the free tier is the documented one: trial balance free, three periods, close, export and report Pro", async (t) => {
  const { box, c } = open(t);
  workedMonth(box.dataHome);
  await c.init();
  assert.equal((await c.call("trial_balance", PERIOD)).isError, false);
  assert.equal((await c.call("ledger_build", PERIOD)).isError, false);
  assert.equal((await c.call("ledger_lines", PERIOD)).isError, false);
  for (const [tool, args] of [
    ["month_close", { month: "2026-06" }],
    ["ledger_export_csv", PERIOD],
    ["ledger_report", PERIOD],
  ]) {
    const r = await c.call(tool, args);
    assert.equal(r.isError, true, `${tool} answered on the free tier`);
    assert.match(r.text, /Pro is a one-time \$\d+ for this server/, tool);
    assert.match(r.text, /license_activate/, tool);
  }
});

test("the resource and the prompt are registered and answer", async (t) => {
  const { box, c } = open(t);
  workedMonth(box.dataHome);
  await c.init();
  const res = (await c.send("resources/read", { uri: "ledger://accounts" })).result;
  const body = JSON.parse(res.contents[0].text);
  assert.deepEqual(body.reads.map((x) => x.store), [
    "invoice", "billing-docs credit notes", "billing-docs purchase orders", "deposits",
    "expense-tracker", "bank-statement", "asset-register",
  ]);
  assert.ok(body.accounts.some((a) => a.account === "cash" && a.posted_from_bank === false));
  assert.equal(body.writes.length, 1);
  assert.equal(body.writes[0].store, "cash-book");
  assert.deepEqual(body.writes[0].files, ["periods.json", "closes.json"]);
  const prompts = (await c.send("prompts/list", {})).result.prompts;
  assert.deepEqual(prompts.map((p) => p.name), ["close_the_month"]);
});

test("no sibling store is ever written, on any tool", async (t) => {
  const { box, c } = open(t, { key: proKey() });
  workedMonth(box.dataHome);
  seed.purchaseOrders(box.dataHome, []);
  await c.init();
  const watched = [
    ["invoice", "invoices.json"], ["invoice", "clients.json"], ["invoice", "business.json"],
    ["billing-docs", "credit-notes.json"], ["billing-docs", "purchase-orders.json"],
    ["deposits", "deposits.json"], ["expense-tracker", "data.json"],
    ["bank-statement", "data.json"], ["asset-register", "assets.json"],
  ];
  const before = watched.map(([s, f]) => {
    const p = join(storeDir(box.dataHome, s), f);
    return [p, readFileSync(p, "utf8"), statSync(p).mtimeMs];
  });
  await c.call("ledger_build", PERIOD);
  await c.call("trial_balance", PERIOD);
  await c.call("ledger_lines", PERIOD);
  await c.call("ledger_report", PERIOD);
  await c.call("ledger_export_csv", PERIOD);
  await c.call("month_close", { month: "2026-06" });
  for (const [p, text, mtime] of before) {
    assert.equal(readFileSync(p, "utf8"), text, `${p} was rewritten`);
    assert.equal(statSync(p).mtimeMs, mtime, `${p} was touched`);
  }
});

test("the seeded record shapes still match what the sibling servers declare", async () => {
  // If a sibling renames a field, this suite's seeds would silently stop reaching the code
  // that reads them, and every figure would quietly become zero while still balancing.
  const need = {
    "invoice/src/store.ts": ["number", "issue_date", "currency", "net_minor", "tax_minor", "total_minor", "paid_minor", "paid_date", "payments", "tax_lines"],
    "billing-docs/src/store.ts": ["invoice_number", "issue_date", "currency", "net_minor", "tax_minor", "total_minor", "status"],
    "deposits/src/store.ts": ["amount_minor", "currency", "received_date", "applications", "refunds"],
    "expense-tracker/src/store.ts": ["date", "amount_minor", "currency", "category", "vat_rate"],
    "bank-statement/src/store.ts": ["date", "amount_minor", "currency", "description"],
    "asset-register/src/store.ts": ["cost_minor", "currency", "in_service_date", "scheme", "category", "method"],
  };
  for (const [file, fields] of Object.entries(need)) {
    const src = readFileSync(join(REPO, "servers", file), "utf8");
    for (const f of fields) {
      assert.match(src, new RegExp(`^\\s*${f}[?]?:`, "m"), `${file} no longer declares ${f}`);
    }
  }
  // The deposit application still names the invoice it paid, the only join between the
  // deposit book and the invoice ledger.
  const dep = readFileSync(join(REPO, "servers", "deposits", "src", "store.ts"), "utf8");
  assert.match(dep, /interface DepositApplication \{[^}]*invoice_number: string/s);
  // And the two stores that publish no ./lib still keep their rows under these keys, which
  // is the only reason this server can read them by path at all.
  for (const [name, key] of [["expense-tracker", "expenses"], ["bank-statement", "transactions"]]) {
    const store = readFileSync(join(REPO, "servers", name, "src", "store.ts"), "utf8");
    assert.match(store, new RegExp(`interface DB \\{[^}]*${key}:`, "s"), `${name} moved its ${key} array`);
    const pkg = JSON.parse(readFileSync(join(REPO, "servers", name, "package.json"), "utf8"));
    assert.equal(pkg.exports?.["./lib"], undefined, `${name} now publishes ./lib; read it through that instead of by path`);
  }
});

test("src holds no network call and no stdout write", async () => {
  // grep exits 1 on no match, which is the passing case here.
  let raw = "";
  try {
    raw = execFileSync("grep", ["-rEn", "fetch\\(|https?://|node:http|node:net|node:dns|console\\.", join(HERE, "src")], { encoding: "utf8" });
  } catch (e) {
    if (e.status !== 1) throw e;
  }
  const out = raw.trim().split("\n").filter(Boolean);
  const offending = out.filter((l) => !/mcp\.zovo\.one/.test(l));
  assert.deepEqual(offending, [], `network or stdout in src:\n${offending.join("\n")}`);
});

test("every ledger line the server emits carries a source server, a source id and a date", async (t) => {
  const { box, c } = open(t, { key: proKey() });
  workedMonth(box.dataHome);
  await c.init();
  const r = await c.json("ledger_lines", PERIOD);
  assert.ok(r.lines.length > 0);
  for (const l of r.lines) {
    assert.ok(typeof l.source === "string" && l.source.length > 0);
    assert.ok(typeof l.source_id === "string" && l.source_id.length > 0);
    assert.match(l.date, /^\d{4}-\d{2}-\d{2}$/);
    assert.ok(Number.isInteger(l.debit_minor) && Number.isInteger(l.credit_minor), "minor units are integers");
  }
});
