// Contract suite for packing-list. Mechanical assertions only.
//
// Asserts the invariants of servers/packing-list/SPEC.md that a test can check without
// judgement: one version number across package.json, src/version.ts, serverInfo and all
// four registry manifests; the remotes rule (this server is stdio and .mcpb only, so NO
// manifest may advertise a remote); JSON-RPC-only stdout; tool-description hygiene; the
// free/Pro tier switch; that nothing outside this server's own directory is written; and
// that no money arithmetic exists here at all. It never asserts a number a human chose;
// those live in test/unit.test.mjs.
import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { client, sandbox, cleanup, proKey, storeDir, writeProfile, seed, REPO, CREATE, REFERENCE } from "./_client.mjs";

const HERE = join(REPO, "servers", "packing-list");
const PRODUCT = "packing-list";
const MAX_DESCRIPTION = 220;
const HARD_MAX_DESCRIPTION = 1200;
const MANIFESTS = ["server.json", "server.mcpb.json", "server.slip.json", "server.consignment.json"];

/**
 * Tools that already break the description rules on the day this suite was written.
 * The suite is a ratchet: an existing entry is reported, a NEW one fails. The fix is in
 * src, not here.
 */
const OVER_LENGTH_BASELINE = [];

function open(t, opts = {}) {
  const box = sandbox();
  writeProfile(box.dataHome);
  const c = client({ dataHome: box.dataHome, ...opts });
  t.after(() => { c.close(); cleanup(box.dir); });
  return { box, c };
}

test("the version is one number: package.json, src/version.ts, serverInfo and every manifest agree", async (t) => {
  const pkg = JSON.parse(readFileSync(join(HERE, "package.json"), "utf8"));
  assert.equal(pkg.name, "@theluckystrike/mcp-packing-list");
  assert.match(pkg.version, /^\d+\.\d+\.\d+$/, "package version must be a plain semver; the release bump moves it, the test does not pin it");
  assert.ok(pkg.description.length < 100, `package description is ${pkg.description.length} chars`);
  const generated = readFileSync(join(HERE, "src", "version.ts"), "utf8");
  assert.match(generated, /GENERATED by scripts\/sync-versions\.mjs/, "version.ts must be generated, not hand written");
  assert.match(generated, new RegExp(`export const VERSION = "${pkg.version.replace(/\./g, "\\.")}";`),
    `src/version.ts does not carry ${pkg.version}; run node scripts/sync-versions.mjs`);

  const { c } = open(t);
  const info = await c.init();
  assert.equal(info.serverInfo.version, pkg.version, "serverInfo.version must equal the package version");
  assert.equal(info.serverInfo.name, "mcp-packing-list");

  for (const file of MANIFESTS) {
    const j = JSON.parse(readFileSync(join(HERE, file), "utf8"));
    assert.equal(j.version, pkg.version, `${file} version`);
    for (const p of j.packages ?? []) {
      assert.equal(p.version, pkg.version, `${file} package entry version`);
      assert.equal(p.transport.type, "stdio", `${file} declares a transport this server does not speak`);
      if (p.registryType === "mcpb") {
        // "TBD" until scripts/manifest-sha256.mjs hashes the built bundle; after that, the
        // real digest. A STALE digest is worse than none: the registry validates it against
        // the asset it downloads and rejects the row, naming the digest rather than the cause.
        assert.ok(p.fileSha256 === "TBD" || /^[0-9a-f]{64}$/.test(p.fileSha256),
          `${file} fileSha256 is neither TBD nor a sha256: ${p.fileSha256}`);
      }
    }
    // This server ships stdio and .mcpb only. It has no hosted endpoint, so NO manifest may
    // advertise a remote: the registry binds one endpoint URL to exactly one server name,
    // and a remote here would claim a URL that does not answer.
    assert.equal(j.remotes, undefined, `${file} advertises a remote; this server is not hosted`);
    assert.equal(existsSync(join(HERE, "remotes.json")), false, "remotes.json must not exist: this server is not hosted");
    assert.ok((j.description ?? "").length < 100, `${file} description is ${(j.description ?? "").length} chars; the registry 422s at 100`);
    assert.ok(!/[,.]\.$|,$/.test(j.description), `${file} description ends in a machine truncation`);
    assert.ok(!/\u2014/.test(JSON.stringify(j)), `${file} carries an em dash`);
  }
  // Three distinct registry names, so the second and third are second listings, not copies.
  const names = ["server.json", "server.slip.json", "server.consignment.json"]
    .map((f) => JSON.parse(readFileSync(join(HERE, f), "utf8")).name);
  assert.equal(new Set(names).size, 3, `registry names must differ: ${names.join(", ")}`);
  assert.deepEqual(names, [
    "io.github.theluckystrike/packing-list",
    "io.github.theluckystrike/packing-slip-cartons-shipment-weights",
    "io.github.theluckystrike/carton-consignment-waybill-pack-list",
  ]);

  execFileSync(process.execPath, [join(REPO, "scripts", "sync-versions.mjs"), "--check"], { encoding: "utf8" });
});

test("every registry name carries a token this server can actually be found on", () => {
  // Registry search matches a substring of the FULL name and nothing else; the description
  // is never searched (docs/NAMING_R5_RESULT.md). So the tokens this server is meant to be
  // findable on have to be IN the names, and this asserts they are rather than assuming it.
  const names = MANIFESTS.filter((f) => f !== "server.mcpb.json")
    .map((f) => JSON.parse(readFileSync(join(HERE, f), "utf8")).name.toLowerCase());
  const joined = names.join(" ");
  for (const token of ["packing", "carton", "consignment", "waybill", "slip", "pack"]) {
    assert.ok(joined.includes(token), `no registry name carries the token "${token}"`);
  }
});

test("stdout carries JSON-RPC only across initialize, tools/list, a success and an error", async (t) => {
  const { c } = open(t);
  await c.init();
  await c.tools();
  await c.call("packing_list_create", CREATE);
  await c.call("packing_list_show", { packing_list: "PL-2099-0001" });
  await new Promise((r) => setTimeout(r, 150));

  const lines = c.stdoutLines.filter((l) => l.trim() !== "");
  assert.ok(lines.length >= 4, `expected at least 4 protocol lines, got ${lines.length}`);
  for (const line of lines) {
    let m;
    try { m = JSON.parse(line); } catch { assert.fail(`non-JSON on stdout: ${JSON.stringify(line.slice(0, 200))}`); }
    assert.equal(m.jsonrpc, "2.0", `stdout line is JSON but not JSON-RPC: ${line.slice(0, 200)}`);
  }
});

test("every tool description is non-empty, single-paragraph, and within the ceiling", async (t) => {
  const { c } = open(t);
  await c.init();
  const tools = await c.tools();
  assert.equal(tools.length, 14, "tool count changed; update servers/packing-list/SPEC.md");
  assert.deepEqual(tools.map((x) => x.name).sort(), [
    "carton_add", "carton_report", "license_activate", "license_status", "pack_item",
    "packing_expect", "packing_list_create", "packing_list_delete", "packing_list_list",
    "packing_list_show", "packing_list_status", "packing_shortfall", "packing_slip", "unpack_item",
  ]);

  for (const tool of tools) {
    const d = tool.description ?? "";
    assert.ok(d.trim().length > 0, `${tool.name} has no description`);
    assert.equal(d, d.trim(), `${tool.name} description has leading or trailing whitespace`);
    assert.ok(d.length <= HARD_MAX_DESCRIPTION, `${tool.name} description is ${d.length} chars, over ${HARD_MAX_DESCRIPTION}`);
    assert.ok(!/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/u.test(d), `${tool.name} description carries an emoji`);
    assert.ok(!/\u2014/.test(d), `${tool.name} description carries an em dash`);
  }

  const over = tools.filter((x) => (x.description ?? "").length > MAX_DESCRIPTION).map((x) => x.name).sort();
  const regressions = over.filter((n) => !OVER_LENGTH_BASELINE.includes(n));
  assert.deepEqual(regressions, [], `new tool descriptions over ${MAX_DESCRIPTION} chars`);
});

test("the one tool that takes a file path opens with an imperative and names the path argument", async (t) => {
  const { c } = open(t);
  await c.init();
  const tools = await c.tools();
  const fileTools = tools.filter((x) => Object.keys(x.inputSchema?.properties ?? {}).includes("out_path"));
  assert.deepEqual(fileTools.map((x) => x.name), ["packing_slip"]);
  const d = fileTools[0].description;
  assert.match(d, /out_path/, "a tool that writes a file must name the argument in its description");
  assert.match(d, /Pro/, "the tier that may write a file must be named in the description");
});

test("license_status reports free with no key and pro with a signed key", async (t) => {
  const { c: free } = open(t);
  await free.init();
  const f = await free.call("license_status", {});
  assert.equal(f.isError, false, f.text);
  assert.match(f.text, /"tier":\s*"free"/, f.text.slice(0, 300));

  const key = proKey(PRODUCT);
  assert.match(key, /^MCPL1\./);
  const { c: pro } = open(t, { key });
  await pro.init();
  assert.match((await pro.call("license_status", {})).text, /"tier":\s*"pro"/);
});

test("a licence for another product does not unlock this one", async (t) => {
  const { c } = open(t, { key: proKey("not-a-real-product") });
  await c.init();
  assert.match((await c.call("license_status", {})).text, /"tier":\s*"free"/);
});

test("the free tier is the documented one: everything but writing the slip to a file", async (t) => {
  const { c } = open(t);
  await c.init();
  const id = await seed(c);
  for (const [tool, args] of [
    ["packing_list_show", { packing_list: id }],
    ["packing_list_list", {}],
    ["carton_report", { packing_list: id }],
    ["packing_shortfall", { packing_list: id }],
    ["packing_slip", { packing_list: id }],
    ["packing_expect", { packing_list: id, description: "Spare shelf", quantity: 1 }],
    ["carton_add", { packing_list: id, label: "Box 3", tare_grams: 100 }],
    ["pack_item", { packing_list: id, carton: "C03", description: "Spare shelf", quantity: 1, unit_grams: 1250 }],
    ["unpack_item", { packing_list: id, line: "L05" }],
    ["packing_list_status", { packing_list: id, status: "cancelled" }],
    ["packing_list_delete", { packing_list: id, confirm: true }],
  ]) {
    const r = await c.call(tool, args);
    assert.equal(r.isError, false, `${tool} was gated: ${r.text}`);
  }
  const fresh = await c.json("packing_list_create", { reference: "PO-7", consignee: "Harbour Cafe" });
  const gated = await c.call("packing_slip", { packing_list: fresh.created.id, out_path: "/tmp/should-not-be-written.txt" });
  assert.equal(gated.isError, true, "packing_slip wrote a file on the free tier");
  assert.match(gated.text, /Pro is a one-time \$\d+ for this server/);
  assert.match(gated.text, /license_activate/);
  // The conversion instrument: every gate link carries the tool that tripped it.
  assert.match(gated.text, new RegExp(`src=${PRODUCT}\\.packing_slip`), "the gate link is untagged");
  assert.match(gated.text, /any total or journal composed outside them is an estimate/, "the NO_HAND_MATH sentence is missing");
  assert.match(gated.text, new RegExp(`Or all \\d+ servers for \\$\\d+: https://mcp\\.zovo\\.one/buy/bundle\\?src=${PRODUCT}\\.packing_slip\\.bundle$`), "the bundle sentence is missing");
  assert.equal(existsSync("/tmp/should-not-be-written.txt"), false, "the gate wrote a file before refusing");
});

test("the free-tier cap message also carries the tagged link and the bundle", async (t) => {
  const { c } = open(t);
  await c.init();
  for (let i = 1; i <= 3; i++) await c.json("packing_list_create", { reference: `PO-${i}`, consignee: "Harbour Cafe" });
  const r = await c.call("packing_list_create", { reference: "PO-4", consignee: "Harbour Cafe" });
  assert.ok(r.isError, r.text);
  assert.match(r.text, new RegExp(`src=${PRODUCT}\\.packing_list_create`));
  assert.match(r.text, /buy\/bundle/);
});

test("the resource and the prompt are registered and answer", async (t) => {
  const { c } = open(t);
  await c.init();
  const res = (await c.send("resources/read", { uri: "packinglist://contract" })).result;
  const body = JSON.parse(res.contents[0].text);
  assert.deepEqual(body.statuses, ["draft", "packed", "shipped", "cancelled"]);
  assert.deepEqual(body.open_statuses, ["draft", "packed"]);
  assert.deepEqual(body.transitions, { draft: ["packed", "cancelled"], packed: ["shipped", "draft", "cancelled"], shipped: [], cancelled: [] });
  assert.equal(body.free_tier.open_packing_lists, 3);
  assert.deepEqual(body.free_tier.pro_tools, ["packing_slip with out_path"]);
  assert.equal(body.units.money, "none: a packing slip carries no prices");
  assert.deepEqual(body.weights.divisors, [4000, 5000, 6000]);
  assert.equal(body.weights.default_divisor, 5000);
  assert.deepEqual(Object.keys(body.shortfall_states).sort(), ["complete", "not_on_order", "over", "short"]);
  assert.equal(body.opens_sibling_stores, false);
  assert.equal(body.creates_invoices, false);
  assert.equal(body.writes.length, 1);
  assert.equal(body.writes[0].store, "packing-list");
  const prompts = (await c.send("prompts/list", {})).result.prompts;
  assert.deepEqual(prompts.map((p) => p.name), ["pack_the_shipment"]);
});

test("this server writes its own directory and no sibling store, on any tool", async (t) => {
  const { box, c } = open(t, { key: proKey() });
  await c.init();
  const id = await seed(c);
  await c.call("packing_slip", { packing_list: id });
  await c.call("carton_report", { packing_list: id });
  await c.call("packing_shortfall", { packing_list: id });
  await c.call("packing_list_list", {});
  await c.call("packing_list_status", { packing_list: id, status: "packed" });
  const gone = await c.json("packing_list_create", { reference: "PO-GONE", consignee: "Gone" });
  await c.call("packing_list_delete", { packing_list: gone.created.id, confirm: true });

  const files = readdirSync(storeDir(box.dataHome)).filter((f) => !f.startsWith("."));
  assert.deepEqual(files.sort(), ["counter.json", "packing-lists.json"]);
  // The shared profile was READ and must be untouched: one file, the one the test wrote.
  const siblings = readdirSync(join(box.dataHome, "mcp-servers")).sort();
  assert.deepEqual(siblings, ["packing-list", "profile"], `a sibling store was created: ${siblings.join(", ")}`);
  assert.deepEqual(readdirSync(join(box.dataHome, "mcp-servers", "profile")), ["business.json"],
    "this server wrote into the shared profile directory; it must only read business.json");
});

test("no weight and no shortfall is stored: a record holds its cartons and its lines only", async (t) => {
  const { box, c } = open(t, { key: proKey() });
  await c.init();
  const id = await seed(c);
  await c.call("carton_report", { packing_list: id });
  await c.call("packing_shortfall", { packing_list: id });
  const raw = readFileSync(join(storeDir(box.dataHome), "packing-lists.json"), "utf8");
  for (const key of ["net_grams", "gross_grams", "volumetric_grams", "chargeable_grams", "volume_cm3",
    "outstanding", "shortfall", "ready_to_ship", "units", "totals"]) {
    assert.equal(raw.includes(`"${key}"`), false, `${key} was stored; every weight must be derived on the call`);
  }
  const stored = JSON.parse(raw)[0];
  assert.deepEqual(Object.keys(stored).sort(), [
    "cartons", "consignee", "created", "date", "expected", "history", "id", "packed",
    "reference", "reference_kind", "ship_to", "status", "updated",
  ]);
  assert.deepEqual(Object.keys(stored.cartons[0]).sort(), ["height_cm", "id", "label", "length_cm", "tare_grams", "width_cm"]);
  assert.deepEqual(Object.keys(stored.packed[0]).sort(), ["carton", "description", "id", "quantity", "sku", "unit_grams"]);
  assert.deepEqual(Object.keys(stored.expected[0]).sort(), ["description", "id", "quantity", "sku"]);
});

test("there is no money arithmetic anywhere in this server", async () => {
  // A packing slip carries no prices. That is enforced here rather than trusted: no money
  // engine is imported, no currency is stored, and no currency symbol reaches the document.
  for (const f of ["index.ts", "packing.ts", "store.ts", "lib.ts"]) {
    const s = readFileSync(join(HERE, "src", f), "utf8");
    assert.equal(/^import .*mcp-invoice/m.test(s), false, `src/${f} imports the money engine`);
    const code = s.split("\n").filter((l) => !/^\s*(\*|\/\/|\/\*)/.test(l)).join("\n");
    assert.equal(/formatMoney|computeTotals|roundHalfUp|currencyDecimals/.test(code), false, `src/${f} carries money arithmetic`);
    assert.equal(/[\u20ac\u00a3\u00a5]/.test(s), false, `src/${f} carries a currency symbol`);
  }
  const pkg = JSON.parse(readFileSync(join(HERE, "package.json"), "utf8"));
  assert.equal(pkg.dependencies["@theluckystrike/mcp-invoice"], undefined, "the invoice engine must not be a dependency");
});

test("src holds no network call and no stdout write", async () => {
  // grep exits 1 on no match, which is the passing case here.
  let raw = "";
  try {
    raw = execFileSync("/usr/bin/grep", ["-rEn", "fetch\\(|https?://|node:http|node:net|node:dns|console\\.", join(HERE, "src")], { encoding: "utf8" });
  } catch (e) {
    if (e.status !== 1) throw e;
  }
  const out = raw.trim().split("\n").filter(Boolean);
  const offending = out.filter((l) => !/mcp\.zovo\.one|github\.com|modelcontextprotocol\.io|packinglist:\/\//.test(l));
  assert.deepEqual(offending, [], `network or stdout in src:\n${offending.join("\n")}`);
});

test("src, tests and docs carry no em dash and no emoji", () => {
  const files = [
    ...readdirSync(join(HERE, "src")).map((f) => join(HERE, "src", f)),
    ...readdirSync(join(HERE, "test")).map((f) => join(HERE, "test", f)),
    join(HERE, "README.md"), join(HERE, "llms-install.md"), join(HERE, "RESULT.md"), join(HERE, "SPEC.md"),
  ].filter(existsSync);
  for (const f of files) {
    const s = readFileSync(f, "utf8");
    assert.equal(s.includes("\u2014"), false, `${f} carries an em dash`);
    assert.equal(/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/u.test(s), false, `${f} carries an emoji`);
  }
});

test("the required files are all present", () => {
  for (const f of [
    "package.json", "tsconfig.json", "README.md", "LICENSE", "SPEC.md", "RESULT.md",
    "server.json", "server.mcpb.json", "server.slip.json", "server.consignment.json",
    "smithery.yaml", "glama.json", "llms-install.md", "Dockerfile",
    "src/index.ts", "src/lib.ts", "src/packing.ts", "src/store.ts", "src/version.ts",
  ]) {
    assert.ok(existsSync(join(HERE, f)), `missing ${f}`);
  }
});

test("every mass the server emits is a whole number of grams", async (t) => {
  const { c } = open(t);
  await c.init();
  const id = await seed(c);
  const r = await c.json("carton_report", { packing_list: id, divisor: 6000 });
  for (const cn of r.cartons) {
    for (const k of ["tare_grams", "net_grams", "gross_grams"]) {
      assert.ok(Number.isInteger(cn[k]), `${cn.id}.${k} is not an integer: ${cn[k]}`);
    }
    assert.ok(cn.volumetric_grams === null || Number.isInteger(cn.volumetric_grams), `${cn.id}.volumetric_grams`);
    assert.ok(cn.chargeable_grams === null || Number.isInteger(cn.chargeable_grams), `${cn.id}.chargeable_grams`);
    assert.equal(cn.gross_grams, cn.tare_grams + cn.net_grams, `${cn.id}: tare plus net does not make the gross`);
    if (cn.chargeable_grams !== null) assert.equal(cn.chargeable_grams, Math.max(cn.gross_grams, cn.volumetric_grams));
  }
  assert.equal(r.totals.gross_grams, r.cartons.reduce((n, x) => n + x.gross_grams, 0), "the shipment gross is not the sum of the cartons");
  assert.equal(r.totals.tare_grams + r.totals.net_grams, r.totals.gross_grams);
  const shortfallRows = (await c.json("packing_shortfall", { packing_list: id })).rows;
  for (const row of shortfallRows) {
    assert.ok(Number.isInteger(row.expected) && Number.isInteger(row.packed) && Number.isInteger(row.outstanding), JSON.stringify(row));
    assert.equal(row.outstanding, row.expected - row.packed, "outstanding is not expected minus packed");
  }
  const listed = await c.json("packing_list_list", { reference: REFERENCE });
  assert.equal(listed.packing_lists.length, 1);
});

test("the estate lists this server everywhere a new server has to be registered", () => {
  // The one-line registrations outside this folder. release-check.mjs is the full reader;
  // these are the ones a server cannot ship without, checked here so the omission fails in
  // this suite rather than at bundle time. Copied from the delivery-schedule suite, which is
  // where this pattern was established.
  const cases = [
    ["scripts/build-mcpb.sh", /^SERVERS="[^"]*\bpacking-list\b/m, "SERVERS list"],
    ["scripts/build-mcpb.sh", /^\s*\[packing-list\]="/m, "DISPLAY_NAME"],
    ["scripts/build-mcpb.sh", /^\s*\[packing-list\]='\[/m, "KEYWORDS"],
    ["scripts/build-pages.mjs", /const ids = \[[^\]]*"packing-list"/, "page ids"],
    ["scripts/gen-spec.mjs", /"packing-list"/, "SPEC generator"],
    ["scripts/validate.mjs", /^  "?packing-list"?: async \(c, tmp, tier, ok\) =>/m, "live validation probe"],
    ["servers/office-suite/src/index.ts", /id: "packing-list"/, "office-suite CHILDREN"],
    ["servers/invoice/src/index.ts", /"packing-list"/, "PROFILE_READERS"],
    ["data/facts.json", /"packing-list":/, "facts tagline, which the README table is generated from"],
    ["data/distribution.json", /"packing-list":/, "distribution per_server"],
    ["README.md", /\[mcp-packing-list\]/, "README server table"],
    ["data/tools.json", /"packing-list":/, "tools.json, which the storefront tool tables read"],
    ["scripts/sync-mirrors.sh", /^ALL_SERVERS="[^"]*\bpacking-list\b/m, "ALL_SERVERS"],
    ["scripts/mirror-seo.py", /^\s*"packing-list":/m, "mirror-seo CAPABILITY and topics"],
  ];
  for (const [file, re, what] of cases) {
    const src = readFileSync(join(REPO, file), "utf8");
    assert.ok(re.test(src), `${file} does not list packing-list in its ${what}`);
  }
});

test("this server is NOT registered on any hosted surface, because it has none", () => {
  // The inverse registration, and it matters as much as the positive one. The registry binds
  // one hosted endpoint URL to exactly one server name, so a /mcp/packing-list row anywhere would
  // claim a URL that has never answered and would burn the name for the day it is hosted.
  // scripts/validate.mjs drives the LIVE endpoints in its remote() section; a name added
  // there fails forever rather than once.
  const validate = readFileSync(join(REPO, "scripts", "validate.mjs"), "utf8");
  const remoteBlock = validate.slice(validate.indexOf("async function remote()"));
  assert.equal(remoteBlock.includes('"packing-list"'), false, "scripts/validate.mjs remote() probes packing-list over HTTP, but it has no hosted endpoint");
  const dist = JSON.parse(readFileSync(join(REPO, "data", "distribution.json"), "utf8"));
  assert.match(dist.per_server["packing-list"].hosted, /^none by design/, "distribution.json claims a hosted endpoint for packing-list");
});
