// Contract suite for deposits. Generated shape, mechanical assertions only.
//
// Asserts the invariants of servers/deposits/SPEC.md that a test can check without
// judgement: one version number across package.json, src/version.ts, serverInfo and all
// four registry manifests; JSON-RPC-only stdout; tool-description hygiene; and the
// free/Pro tier switch. It never asserts a number a human chose; those live in the
// server's own suites.
import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { client, sandbox, cleanup, proKey, REPO } from "./_client.mjs";

const HERE = join(REPO, "servers", "deposits");
const PRODUCT = "deposits";
const MAX_DESCRIPTION = 220;
const HARD_MAX_DESCRIPTION = 1200;
const FILE_ARGS = ["path", "url", "out_path", "template_path"];
const IMPERATIVE = /^(Call this tool|Use this)\b/;

/**
 * Tools that already break the two description rules on the day this suite was written.
 * The suite is a ratchet: an existing entry is reported, a NEW one fails. Both lists are
 * defects; the fix is in src, not here.
 */
const OVER_LENGTH_BASELINE = [];
const NON_IMPERATIVE_BASELINE = [];

function open(t, opts = {}) {
  const box = sandbox();
  const c = client({ dataHome: box.dataHome, ...opts });
  t.after(() => { c.close(); cleanup(box.dir); });
  return { box, c };
}

test("the version is one number: package.json, src/version.ts, serverInfo and every manifest agree", async (t) => {
  const pkg = JSON.parse(readFileSync(join(HERE, "package.json"), "utf8"));
  assert.equal(pkg.name, "@theluckystrike/mcp-deposits");
  assert.ok(pkg.description.length < 100, `package description is ${pkg.description.length} chars`);
  const generated = readFileSync(join(HERE, "src", "version.ts"), "utf8");
  assert.match(generated, /GENERATED by scripts\/sync-versions\.mjs/, "version.ts must be generated, not hand written");
  assert.match(generated, new RegExp(`export const VERSION = "${pkg.version.replace(/\./g, "\\.")}";`),
    `src/version.ts does not carry ${pkg.version}; run node scripts/sync-versions.mjs`);

  const { c } = open(t);
  const info = await c.init();
  assert.equal(info.serverInfo.version, pkg.version, "serverInfo.version must equal the package version");
  assert.equal(info.serverInfo.name, "mcp-deposits");

  for (const file of ["server.json", "server.mcpb.json", "server.variant.json", "server.retainer.json"]) {
    const j = JSON.parse(readFileSync(join(HERE, file), "utf8"));
    assert.equal(j.version, pkg.version, `${file} version`);
    for (const p of j.packages ?? []) {
      assert.equal(p.version, pkg.version, `${file} package entry version`);
      assert.equal(p.transport.type, "stdio", `${file} is stdio only: this server is not hosted`);
    }
    assert.equal(j.remotes, undefined, `${file} must not advertise a remote: this server is not hosted`);
    assert.ok((j.description ?? "").length < 100, `${file} description is ${j.description.length} chars; the registry 422s at 100`);
    assert.ok(!/[,.]\.$|,$/.test(j.description), `${file} description ends in a machine truncation`);
  }
  // Three distinct registry names, so the second and third are second listings, not copies.
  const names = ["server.json", "server.variant.json", "server.retainer.json"]
    .map((f) => JSON.parse(readFileSync(join(HERE, f), "utf8")).name);
  assert.equal(new Set(names).size, 3, `registry names must differ: ${names.join(", ")}`);
  assert.deepEqual(names, [
    "io.github.theluckystrike/deposits",
    "io.github.theluckystrike/deposit",
    "io.github.theluckystrike/retainer",
  ]);

  // And sync-versions --check passes for the whole repo, so no sibling drifted either.
  execFileSync(process.execPath, [join(REPO, "scripts", "sync-versions.mjs"), "--check"], { encoding: "utf8" });
});

test("stdout carries JSON-RPC only across initialize, tools/list, a success and an error", async (t) => {
  const { c } = open(t);
  await c.init();
  await c.tools();
  await c.call("deposit_list", {});
  await c.call("deposit_refund", { id: "DEP-2026-9999", method: "cash" });
  await new Promise((r) => setTimeout(r, 150));

  const lines = [...c.stdoutLines, c.tail].filter((l) => l.trim() !== "");
  assert.ok(lines.length >= 4, `expected at least 4 protocol lines, got ${lines.length}`);
  for (const line of lines) {
    let m;
    try { m = JSON.parse(line); } catch { assert.fail(`non-JSON on stdout: ${JSON.stringify(line.slice(0, 200))}`); }
    assert.equal(m.jsonrpc, "2.0", `stdout line is JSON but not JSON-RPC: ${line.slice(0, 200)}`);
  }
});

test("every tool description is non-empty, single-paragraph, and within the ceiling", async (t) => {
  const { c } = open(t);
  await c.init();
  const tools = await c.tools();
  assert.equal(tools.length, 10, "tool count changed; update servers/deposits/SPEC.md");
  assert.deepEqual(tools.map((x) => x.name).sort(), [
    "deposit_apply", "deposit_balance", "deposit_list", "deposit_record", "deposit_refund",
    "deposit_statement_pdf", "deposit_statement_text", "deposits_report",
    "license_activate", "license_status",
  ]);

  for (const tool of tools) {
    const d = tool.description ?? "";
    assert.ok(d.trim().length > 0, `${tool.name} has no description`);
    assert.equal(d, d.trim(), `${tool.name} description has leading or trailing whitespace`);
    assert.ok(d.length <= HARD_MAX_DESCRIPTION, `${tool.name} description is ${d.length} chars, over ${HARD_MAX_DESCRIPTION}`);
    assert.ok(!/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/u.test(d), `${tool.name} description carries an emoji`);
  }

  const over = tools.filter((x) => (x.description ?? "").length > MAX_DESCRIPTION).map((x) => x.name).sort();
  const regressions = over.filter((n) => !OVER_LENGTH_BASELINE.includes(n));
  assert.deepEqual(regressions, [], `new tool descriptions over ${MAX_DESCRIPTION} chars`);
});

test("a tool that takes a file path opens with an imperative sentence", async (t) => {
  const { c } = open(t);
  await c.init();
  const tools = await c.tools();
  const fileTools = tools.filter((x) => Object.keys(x.inputSchema?.properties ?? {}).some((k) => FILE_ARGS.includes(k)));
  assert.ok(fileTools.length >= 1, "deposit_statement_pdf takes out_path");
  const offenders = fileTools.filter((x) => !IMPERATIVE.test(x.description ?? "")).map((x) => x.name).sort();
  const regressions = offenders.filter((n) => !NON_IMPERATIVE_BASELINE.includes(n));
  assert.deepEqual(regressions, [], "new file tools whose description does not start with \"Call this tool\" or \"Use this\"");
});

test("license_status reports free with no key and pro with a signed key", async (t) => {
  const { c: free } = open(t);
  await free.init();
  const f = await free.call("license_status", {});
  assert.equal(f.isError, false, f.text);
  assert.match(f.text, /"tier":\s*"free"/, f.text.slice(0, 300));

  const key = proKey(PRODUCT);
  assert.match(key, /^MCPL1\./);
  const { c: pro } = open(t, { key });
  await pro.init();
  assert.match((await pro.call("license_status", {})).text, /"tier":\s*"pro"/);
});

test("the resource and the prompt are registered and answer", async (t) => {
  const { c } = open(t);
  await c.init();
  await c.call("deposit_record", { client: "Acme Ltd", amount_minor: 1000, kind: "security", currency: "EUR", received_date: "2026-09-01" });
  const res = (await c.send("resources/read", { uri: "deposits://held" })).result;
  const held = JSON.parse(res.contents[0].text);
  assert.equal(held.length, 1);
  assert.equal(held[0].held_minor, 1000);
  const prompts = (await c.send("prompts/list", {})).result.prompts;
  assert.deepEqual(prompts.map((p) => p.name), ["settle_deposits"]);
});
