// Contract suite for change-order. Generated shape, mechanical assertions only.
//
// Asserts the invariants of servers/change-order/SPEC.md that a test can check without
// judgement: one version number across package.json, src/version.ts, serverInfo and all
// four registry manifests; the remotes rule (the mcpb manifest carries remotes.json, the
// stdio-only names carry none); JSON-RPC-only stdout; tool-description hygiene; the
// free/Pro tier switch; that nothing outside this server's own directory is written; and
// that the invoice engine is imported rather than restated. It never asserts a number a
// human chose; those live in test/unit.test.mjs.
import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { client, sandbox, cleanup, proKey, storeDir, writeProfile, seed, approve, REPO, REFERENCE, CREATE } from "./_client.mjs";

const HERE = join(REPO, "servers", "change-order");
const PRODUCT = "change-order";
const MAX_DESCRIPTION = 220;
const HARD_MAX_DESCRIPTION = 1200;
const FILE_ARGS = ["path", "url", "out_path", "template_path"];

/**
 * Tools that already break the description rules on the day this suite was written.
 * The suite is a ratchet: an existing entry is reported, a NEW one fails. The fix is in
 * src, not here.
 */
const OVER_LENGTH_BASELINE = [];

function open(t, opts = {}) {
  const box = sandbox();
  writeProfile(box.dataHome);
  const c = client({ dataHome: box.dataHome, ...opts });
  t.after(() => { c.close(); cleanup(box.dir); });
  return { box, c };
}

test("the version is one number: package.json, src/version.ts, serverInfo and every manifest agree", async (t) => {
  const pkg = JSON.parse(readFileSync(join(HERE, "package.json"), "utf8"));
  assert.equal(pkg.name, "@theluckystrike/mcp-change-order");
  assert.match(pkg.version, /^\d+\.\d+\.\d+$/, "package version must be a plain semver; the release bump moves it, the test does not pin it");
  assert.ok(pkg.description.length < 100, `package description is ${pkg.description.length} chars`);
  const generated = readFileSync(join(HERE, "src", "version.ts"), "utf8");
  assert.match(generated, /GENERATED by scripts\/sync-versions\.mjs/, "version.ts must be generated, not hand written");
  assert.match(generated, new RegExp(`export const VERSION = "${pkg.version.replace(/\./g, "\\.")}";`),
    `src/version.ts does not carry ${pkg.version}; run node scripts/sync-versions.mjs`);

  const { c } = open(t);
  const info = await c.init();
  assert.equal(info.serverInfo.version, pkg.version, "serverInfo.version must equal the package version");
  assert.equal(info.serverInfo.name, "mcp-change-order");

  for (const file of ["server.json", "server.mcpb.json", "server.variant.json", "server.scope-change.json"]) {
    const j = JSON.parse(readFileSync(join(HERE, file), "utf8"));
    assert.equal(j.version, pkg.version, `${file} version`);
    for (const p of j.packages ?? []) {
      assert.equal(p.version, pkg.version, `${file} package entry version`);
      assert.equal(p.transport.type, "stdio", `${file} declares a transport this server does not speak`);
      if (p.registryType === "mcpb") {
        // "TBD" until the release job hashes the bundle; after that, a real sha256.
        assert.ok(p.fileSha256 === "TBD" || /^[0-9a-f]{64}$/.test(p.fileSha256),
          `${file} fileSha256 is neither TBD nor a sha256: ${p.fileSha256}`);
      }
    }
    if (file === "server.mcpb.json") {
      const remotes = JSON.parse(readFileSync(join(HERE, "remotes.json"), "utf8"));
      assert.deepEqual(j.remotes, remotes, `${file} remotes must equal remotes.json (hosted at /mcp/change-order)`);
      assert.equal(remotes[0].url, "https://mcp.zovo.one/mcp/change-order");
    } else {
      assert.equal(j.remotes, undefined, `${file} is a stdio-only name and must not advertise a remote`);
    }
    assert.ok((j.description ?? "").length < 100, `${file} description is ${(j.description ?? "").length} chars; the registry 422s at 100`);
    assert.ok(!/[,.]\.$|,$/.test(j.description), `${file} description ends in a machine truncation`);
    assert.ok(!/\u2014/.test(JSON.stringify(j)), `${file} carries an em dash`);
  }
  // Three distinct registry names, so the second and third are second listings, not copies.
  const names = ["server.json", "server.variant.json", "server.scope-change.json"]
    .map((f) => JSON.parse(readFileSync(join(HERE, f), "utf8")).name);
  assert.equal(new Set(names).size, 3, `registry names must differ: ${names.join(", ")}`);
  assert.deepEqual(names, [
    "io.github.theluckystrike/change-order",
    "io.github.theluckystrike/variation-order",
    "io.github.theluckystrike/scope-change",
  ]);

  // And sync-versions --check passes for the whole repo, so no sibling drifted either.
  execFileSync(process.execPath, [join(REPO, "scripts", "sync-versions.mjs"), "--check"], { encoding: "utf8" });
});

test("stdout carries JSON-RPC only across initialize, tools/list, a success and an error", async (t) => {
  const { c } = open(t);
  await c.init();
  await c.tools();
  await c.call("change_order_create", CREATE);
  await c.call("change_order_get", { change_order: "CO-2099-0001" });
  await new Promise((r) => setTimeout(r, 150));

  const lines = [...c.stdoutLines, c.tail].filter((l) => l.trim() !== "");
  assert.ok(lines.length >= 4, `expected at least 4 protocol lines, got ${lines.length}`);
  for (const line of lines) {
    let m;
    try { m = JSON.parse(line); } catch { assert.fail(`non-JSON on stdout: ${JSON.stringify(line.slice(0, 200))}`); }
    assert.equal(m.jsonrpc, "2.0", `stdout line is JSON but not JSON-RPC: ${line.slice(0, 200)}`);
  }
});

test("every tool description is non-empty, single-paragraph, and within the ceiling", async (t) => {
  const { c } = open(t);
  await c.init();
  const tools = await c.tools();
  assert.equal(tools.length, 11, "tool count changed; update servers/change-order/SPEC.md");
  assert.deepEqual(tools.map((x) => x.name).sort(), [
    "change_order_add_line", "change_order_create", "change_order_delete", "change_order_document",
    "change_order_get", "change_order_invoice_payload", "change_order_list", "change_order_status",
    "contract_value", "license_activate", "license_status",
  ]);

  for (const tool of tools) {
    const d = tool.description ?? "";
    assert.ok(d.trim().length > 0, `${tool.name} has no description`);
    assert.equal(d, d.trim(), `${tool.name} description has leading or trailing whitespace`);
    assert.ok(d.length <= HARD_MAX_DESCRIPTION, `${tool.name} description is ${d.length} chars, over ${HARD_MAX_DESCRIPTION}`);
    assert.ok(!/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/u.test(d), `${tool.name} description carries an emoji`);
    assert.ok(!/\u2014/.test(d), `${tool.name} description carries an em dash`);
  }

  const over = tools.filter((x) => (x.description ?? "").length > MAX_DESCRIPTION).map((x) => x.name).sort();
  const regressions = over.filter((n) => !OVER_LENGTH_BASELINE.includes(n));
  assert.deepEqual(regressions, [], `new tool descriptions over ${MAX_DESCRIPTION} chars`);
});

test("no tool takes a file path: the document is text and nothing is written outside the store", async (t) => {
  const { c } = open(t);
  await c.init();
  const tools = await c.tools();
  const fileTools = tools.filter((x) => Object.keys(x.inputSchema?.properties ?? {}).some((k) => FILE_ARGS.includes(k)));
  assert.deepEqual(fileTools.map((x) => x.name), []);
});

test("license_status reports free with no key and pro with a signed key", async (t) => {
  const { c: free } = open(t);
  await free.init();
  const f = await free.call("license_status", {});
  assert.equal(f.isError, false, f.text);
  assert.match(f.text, /"tier":\s*"free"/, f.text.slice(0, 300));

  const key = proKey(PRODUCT);
  assert.match(key, /^MCPL1\./);
  const { c: pro } = open(t, { key });
  await pro.init();
  assert.match((await pro.call("license_status", {})).text, /"tier":\s*"pro"/);
});

test("the free tier is the documented one: raise, line, move, get, list, delete and the running value are free", async (t) => {
  const { c } = open(t);
  await c.init();
  const id = await seed(c);
  await approve(c, id);
  const empty = await c.json("change_order_create", { ...CREATE, title: "Empty draft" });
  for (const [tool, args] of [
    ["change_order_add_line", { change_order: empty.created.id, kind: "added", description: "Page", quantity: 1, unit_price_minor: 100, reason: "x" }],
    ["change_order_status", { change_order: empty.created.id, status: "void", date: "2026-03-13" }],
    ["change_order_get", { change_order: id }],
    ["change_order_list", {}],
    ["contract_value", { reference: REFERENCE }],
    ["change_order_create", { ...CREATE, title: "Deleted draft" }],
    ["change_order_delete", { change_order: "Deleted draft" }],
  ]) {
    const r = await c.call(tool, args);
    assert.equal(r.isError, false, `${tool} was gated: ${r.text}`);
  }
  for (const [tool, args] of [
    ["change_order_document", { change_order: id }],
    ["change_order_invoice_payload", { change_order: id }],
  ]) {
    const r = await c.call(tool, args);
    assert.equal(r.isError, true, `${tool} answered on the free tier`);
    assert.match(r.text, /Pro is a one-time \$\d+ for this server/, tool);
    assert.match(r.text, /license_activate/, tool);
    // The conversion instrument: every gate link carries the tool that tripped it.
    assert.match(r.text, new RegExp(`src=${PRODUCT}\\.${tool}`), `${tool} gate link is untagged`);
    // And the shared cap sentence: no hand math, then the bundle link, on every gate.
    assert.match(r.text, /any total or journal composed outside them is an estimate/, `${tool} lacks the NO_HAND_MATH sentence`);
    assert.match(r.text, new RegExp(`Or all \\d+ servers for \\$\\d+: https://mcp\\.zovo\\.one/buy/bundle\\?src=${PRODUCT}\\.${tool}\\.bundle$`), `${tool} lacks the bundle sentence`);
  }
});

test("the resource and the prompt are registered and answer", async (t) => {
  const { c } = open(t);
  await c.init();
  const res = (await c.send("resources/read", { uri: "changeorder://contract" })).result;
  const body = JSON.parse(res.contents[0].text);
  assert.deepEqual(body.statuses, ["draft", "sent", "approved", "rejected", "void"]);
  assert.deepEqual(body.open_statuses, ["draft", "sent"]);
  assert.deepEqual(body.transitions, { draft: ["sent", "void"], sent: ["approved", "rejected", "void"], approved: [], rejected: [], void: [] });
  assert.equal(body.free_tier.open_change_orders, 5);
  assert.deepEqual(body.free_tier.pro_tools.sort(), ["change_order_document", "change_order_invoice_payload"]);
  assert.equal(body.payload_scales.invoice_create, "unit_price in MAJOR units");
  assert.equal(body.payload_scales.quote_create, "unit_price_minor in MINOR units");
  assert.equal(body.creates_invoices, false);
  assert.equal(body.creates_quotes, false);
  assert.equal(body.writes.length, 1);
  assert.equal(body.writes[0].store, "change-order");
  const prompts = (await c.send("prompts/list", {})).result.prompts;
  assert.deepEqual(prompts.map((p) => p.name), ["agree_the_change"]);
});

test("this server writes its own directory and no sibling store, on any tool", async (t) => {
  const { box, c } = open(t, { key: proKey() });
  await c.init();
  const id = await seed(c);
  await c.call("change_order_document", { change_order: id });
  await approve(c, id);
  await c.call("change_order_document", { change_order: id });
  await c.call("change_order_invoice_payload", { change_order: id });
  await c.call("contract_value", { reference: REFERENCE });
  await c.call("change_order_list", {});
  const gone = await c.json("change_order_create", { ...CREATE, title: "Gone" });
  await c.call("change_order_delete", { change_order: gone.created.id });

  const files = readdirSync(storeDir(box.dataHome)).filter((f) => !f.startsWith("."));
  assert.deepEqual(files.sort(), ["change-orders.json", "counter.json"]);
  // The shared profile was READ and must be untouched: one file, the one the test wrote.
  const siblings = readdirSync(join(box.dataHome, "mcp-servers")).sort();
  assert.deepEqual(siblings, ["change-order", "profile"], `a sibling store was created: ${siblings.join(", ")}`);
  assert.deepEqual(readdirSync(join(box.dataHome, "mcp-servers", "profile")), ["business.json"],
    "this server wrote into the shared profile directory; it must only read business.json");
});

test("no delta is derived and stored: a record holds its lines and its history and nothing worked out from them", async (t) => {
  const { box, c } = open(t, { key: proKey() });
  await c.init();
  const id = await seed(c);
  await approve(c, id);
  await c.call("change_order_invoice_payload", { change_order: id });
  await c.call("contract_value", { reference: REFERENCE });
  const raw = readFileSync(join(storeDir(box.dataHome), "change-orders.json"), "utf8");
  // A derived figure stored under any of these keys is a second copy of what the lines say.
  for (const key of ["delta_minor", "net_minor", "total_minor", "vat_minor", "value_minor", "current_value_minor",
    "approved_delta_minor", "pending_delta_minor", "delta_gross_minor", "unit_price"]) {
    assert.equal(raw.includes(`"${key}"`), false, `${key} was stored; every delta must be derived on the call`);
  }
  const stored = JSON.parse(raw)[0];
  assert.deepEqual(Object.keys(stored).sort(), [
    "client", "created", "currency", "date", "history", "id", "lines", "original_value_minor",
    "reference", "reference_kind", "status", "title", "updated",
  ]);
  assert.deepEqual(Object.keys(stored.lines[0]).sort(), ["created", "date", "description", "id", "kind", "quantity", "reason", "tax_rate", "unit_price_minor"]);
  assert.deepEqual(Object.keys(stored.lines[2]).sort(), ["created", "date", "description", "id", "kind", "quantity", "reason", "tax_rate", "unit_price_minor", "was_quantity", "was_unit_price_minor"]);
  assert.equal(stored.history.length, 2, "the two status steps must survive on disk");
});

test("the money engine is the invoice server's own, not a copy", async () => {
  // If servers/invoice changes its rounding basis, this server must change with it, which
  // it does because it never implements the arithmetic: it imports it.
  const engine = readFileSync(join(HERE, "src", "order.ts"), "utf8");
  assert.match(engine, /import \{[^}]*computeTotals[^}]*\} from "@theluckystrike\/mcp-invoice\/lib";/,
    "the totals must come from the invoice server, never be restated here");
  assert.match(engine, /roundHalfUp/, "the rounding must be the invoice server's roundHalfUp");
  for (const forbidden of [/function roundHalfUp/, /function computeTotals/, /Math\.round\(/]) {
    assert.equal(forbidden.test(engine), false, `src/order.ts reimplements ${forbidden}`);
  }
  const index = readFileSync(join(HERE, "src", "index.ts"), "utf8");
  assert.match(index, /readSharedProfile/, "the default currency must come from the shared business profile");
  assert.equal(/getBusiness|hasBusiness|findClient/.test(index), false, "the invoice store must not be opened: its dataDir creates a directory on read");
  assert.equal(/mcp-work-order|mcp-quotes\/lib"[^;]*getQuotes/.test(index), false, "no sibling store is read");
});

test("src holds no network call and no stdout write", async () => {
  // grep exits 1 on no match, which is the passing case here.
  let raw = "";
  try {
    raw = execFileSync("grep", ["-rEn", "fetch\\(|https?://|node:http|node:net|node:dns|console\\.", join(HERE, "src")], { encoding: "utf8" });
  } catch (e) {
    if (e.status !== 1) throw e;
  }
  const out = raw.trim().split("\n").filter(Boolean);
  const offending = out.filter((l) => !/mcp\.zovo\.one|github\.com|modelcontextprotocol\.io/.test(l));
  assert.deepEqual(offending, [], `network or stdout in src:\n${offending.join("\n")}`);
});

test("src, tests and docs carry no em dash and no emoji", () => {
  const files = [
    ...readdirSync(join(HERE, "src")).map((f) => join(HERE, "src", f)),
    ...readdirSync(join(HERE, "test")).map((f) => join(HERE, "test", f)),
    join(HERE, "README.md"), join(HERE, "llms-install.md"), join(HERE, "RESULT.md"),
  ].filter(existsSync);
  for (const f of files) {
    const s = readFileSync(f, "utf8");
    assert.equal(s.includes("\u2014"), false, `${f} carries an em dash`);
    assert.equal(/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/u.test(s), false, `${f} carries an emoji`);
  }
});

test("the required files are all present", () => {
  for (const f of [
    "package.json", "tsconfig.json", "README.md", "LICENSE", "SPEC.md", "RESULT.md",
    "server.json", "server.mcpb.json", "server.variant.json", "server.scope-change.json",
    "remotes.json", "smithery.yaml", "glama.json", "llms-install.md", "Dockerfile",
    "src/index.ts", "src/lib.ts", "src/order.ts", "src/store.ts", "src/version.ts",
  ]) {
    assert.ok(existsSync(join(HERE, f)), `missing ${f}`);
  }
});

test("every amount the server emits is an integer number of minor units", async (t) => {
  const { c } = open(t, { key: proKey() });
  await c.init();
  const id = await seed(c);
  await approve(c, id);
  const g = await c.json("change_order_get", { change_order: id });
  for (const l of g.change_order.lines_detail) {
    assert.ok(Number.isInteger(l.unit_price_minor), JSON.stringify(l));
    assert.ok(Number.isInteger(l.delta_minor), JSON.stringify(l));
  }
  for (const k of ["delta_minor", "vat_minor", "delta_gross_minor", "added_minor", "removed_minor", "changed_minor"]) {
    assert.ok(Number.isInteger(g.change_order[k]), `${k} is not an integer: ${g.change_order[k]}`);
  }
  const cv = await c.json("contract_value", { reference: REFERENCE });
  for (const k of ["original_value_minor", "approved_delta_minor", "current_value_minor", "pending_delta_minor", "if_all_pending_approved_minor"]) {
    assert.ok(Number.isInteger(cv[k]), `${k} is not an integer: ${cv[k]}`);
  }
  assert.equal(cv.original_value_minor + cv.approved_delta_minor, cv.current_value_minor, "original plus approved does not make the current value");
  assert.equal(cv.current_value_minor + cv.pending_delta_minor, cv.if_all_pending_approved_minor);
  const p = await c.json("change_order_invoice_payload", { change_order: id });
  for (const k of ["subtotal_minor", "net_minor", "vat_minor", "total_minor"]) {
    assert.ok(Number.isInteger(p.totals[k]), `${k} is not an integer: ${p.totals[k]}`);
  }
  assert.equal(p.totals.net_minor + p.totals.vat_minor, p.totals.total_minor, "net plus VAT does not make the total");
  for (const i of p.quote_create.arguments.items) {
    assert.ok(Number.isInteger(i.unit_price_minor), `quote_create takes MINOR units and got ${i.unit_price_minor}`);
  }
});
