// Contract suite for per-diem. Generated shape, mechanical assertions only.
//
// Asserts the invariants of servers/per-diem/SPEC.md that a test can check without
// judgement: one version number across package.json, src/version.ts, serverInfo and all
// four registry manifests; JSON-RPC-only stdout; tool-description hygiene; the free/Pro
// tier switch; and that every bundled rate table carries its provenance. It never asserts
// a number a human chose; those live in test/unit.test.mjs.
import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { client, sandbox, cleanup, proKey, REPO, TRIP } from "./_client.mjs";

const HERE = join(REPO, "servers", "per-diem");
const PRODUCT = "per-diem";
const MAX_DESCRIPTION = 220;
const HARD_MAX_DESCRIPTION = 1200;
const FILE_ARGS = ["path", "url", "out_path", "template_path"];
const IMPERATIVE = /^(Call this tool|Use this)\b/;

/**
 * Tools that already break the two description rules on the day this suite was written.
 * The suite is a ratchet: an existing entry is reported, a NEW one fails. Both lists are
 * defects; the fix is in src, not here.
 */
const OVER_LENGTH_BASELINE = [];
const NON_IMPERATIVE_BASELINE = [];

function open(t, opts = {}) {
  const box = sandbox();
  const c = client({ dataHome: box.dataHome, ...opts });
  t.after(() => { c.close(); cleanup(box.dir); });
  return { box, c };
}

test("the version is one number: package.json, src/version.ts, serverInfo and every manifest agree", async (t) => {
  const pkg = JSON.parse(readFileSync(join(HERE, "package.json"), "utf8"));
  assert.equal(pkg.name, "@theluckystrike/mcp-per-diem");
  assert.ok(pkg.description.length < 100, `package description is ${pkg.description.length} chars`);
  const generated = readFileSync(join(HERE, "src", "version.ts"), "utf8");
  assert.match(generated, /GENERATED by scripts\/sync-versions\.mjs/, "version.ts must be generated, not hand written");
  assert.match(generated, new RegExp(`export const VERSION = "${pkg.version.replace(/\./g, "\\.")}";`),
    `src/version.ts does not carry ${pkg.version}; run node scripts/sync-versions.mjs`);

  const { c } = open(t);
  const info = await c.init();
  assert.equal(info.serverInfo.version, pkg.version, "serverInfo.version must equal the package version");
  assert.equal(info.serverInfo.name, "mcp-per-diem");

  for (const file of ["server.json", "server.mcpb.json", "server.variant.json", "server.delegacja.json"]) {
    const j = JSON.parse(readFileSync(join(HERE, file), "utf8"));
    assert.equal(j.version, pkg.version, `${file} version`);
    for (const p of j.packages ?? []) {
      assert.equal(p.version, pkg.version, `${file} package entry version`);
      assert.equal(p.transport.type, "stdio", `${file} is stdio only: this server is not hosted`);
      if (p.registryType === "mcpb") {
        assert.ok(p.fileSha256 === "TBD" || /^[0-9a-f]{64}$/.test(p.fileSha256), `${file} fileSha256 must be TBD before the first release or a sha256 hex after`);
      }
    }
    if (file === "server.mcpb.json") {
      const remotes = JSON.parse(readFileSync(join(HERE, "remotes.json"), "utf8"));
      assert.deepEqual(j.remotes, remotes, `${file} remotes must equal remotes.json (hosted at /mcp/per-diem)`);
    } else {
      assert.equal(j.remotes, undefined, `${file} is a stdio-only second name and must not advertise a remote`);
    }
    assert.ok((j.description ?? "").length < 100, `${file} description is ${j.description.length} chars; the registry 422s at 100`);
    assert.ok(!/[,.]\.$|,$/.test(j.description), `${file} description ends in a machine truncation`);
  }
  // Three distinct registry names, so the second and third are second listings, not copies.
  const names = ["server.json", "server.variant.json", "server.delegacja.json"]
    .map((f) => JSON.parse(readFileSync(join(HERE, f), "utf8")).name);
  assert.equal(new Set(names).size, 3, `registry names must differ: ${names.join(", ")}`);
  assert.deepEqual(names, [
    "io.github.theluckystrike/per-diem",
    "io.github.theluckystrike/travel-allowance",
    "io.github.theluckystrike/delegacja",
  ]);

  // And sync-versions --check passes for the whole repo, so no sibling drifted either.
  execFileSync(process.execPath, [join(REPO, "scripts", "sync-versions.mjs"), "--check"], { encoding: "utf8" });
});

test("stdout carries JSON-RPC only across initialize, tools/list, a success and an error", async (t) => {
  const { c } = open(t);
  await c.init();
  await c.tools();
  await c.call("trip_list", {});
  await c.call("perdiem_calc", { scheme: "pl", destination: "Wakanda", start: "2026-05-04T08:00", end: "2026-05-04T21:00", timezone: "Europe/Warsaw" });
  await new Promise((r) => setTimeout(r, 150));

  const lines = [...c.stdoutLines, c.tail].filter((l) => l.trim() !== "");
  assert.ok(lines.length >= 4, `expected at least 4 protocol lines, got ${lines.length}`);
  for (const line of lines) {
    let m;
    try { m = JSON.parse(line); } catch { assert.fail(`non-JSON on stdout: ${JSON.stringify(line.slice(0, 200))}`); }
    assert.equal(m.jsonrpc, "2.0", `stdout line is JSON but not JSON-RPC: ${line.slice(0, 200)}`);
  }
});

test("every tool description is non-empty, single-paragraph, and within the ceiling", async (t) => {
  const { c } = open(t);
  await c.init();
  const tools = await c.tools();
  assert.equal(tools.length, 8, "tool count changed; update servers/per-diem/SPEC.md");
  assert.deepEqual(tools.map((x) => x.name).sort(), [
    "license_activate", "license_status",
    "perdiem_calc", "perdiem_rates", "perdiem_report",
    "trip_export", "trip_list", "trip_record",
  ]);

  for (const tool of tools) {
    const d = tool.description ?? "";
    assert.ok(d.trim().length > 0, `${tool.name} has no description`);
    assert.equal(d, d.trim(), `${tool.name} description has leading or trailing whitespace`);
    assert.ok(d.length <= HARD_MAX_DESCRIPTION, `${tool.name} description is ${d.length} chars, over ${HARD_MAX_DESCRIPTION}`);
    assert.ok(!/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/u.test(d), `${tool.name} description carries an emoji`);
  }

  const over = tools.filter((x) => (x.description ?? "").length > MAX_DESCRIPTION).map((x) => x.name).sort();
  const regressions = over.filter((n) => !OVER_LENGTH_BASELINE.includes(n));
  assert.deepEqual(regressions, [], `new tool descriptions over ${MAX_DESCRIPTION} chars`);
});

test("a tool that takes a file path opens with an imperative sentence", async (t) => {
  const { c } = open(t);
  await c.init();
  const tools = await c.tools();
  const fileTools = tools.filter((x) => Object.keys(x.inputSchema?.properties ?? {}).some((k) => FILE_ARGS.includes(k)));
  assert.deepEqual(fileTools.map((x) => x.name), [], "this server takes no file paths; if one is added it must open with \"Call this tool\" or \"Use this\"");
  const offenders = fileTools.filter((x) => !IMPERATIVE.test(x.description ?? "")).map((x) => x.name).sort();
  assert.deepEqual(offenders.filter((n) => !NON_IMPERATIVE_BASELINE.includes(n)), []);
});

test("license_status reports free with no key and pro with a signed key", async (t) => {
  const { c: free } = open(t);
  await free.init();
  const f = await free.call("license_status", {});
  assert.equal(f.isError, false, f.text);
  assert.match(f.text, /"tier":\s*"free"/, f.text.slice(0, 300));

  const key = proKey(PRODUCT);
  assert.match(key, /^MCPL1\./);
  const { c: pro } = open(t, { key });
  await pro.init();
  assert.match((await pro.call("license_status", {})).text, /"tier":\s*"pro"/);

  // A key signed for another product does not unlock the Pro tools here.
  const { c: wrong } = open(t, { key: proKey("deposits") });
  await wrong.init();
  assert.equal((await wrong.call("perdiem_report", {})).isError, true);
});

test("the resource and the prompt are registered and answer", async (t) => {
  const { c } = open(t);
  await c.init();
  const res = (await c.send("resources/read", { uri: "perdiem://schemes" })).result;
  const body = JSON.parse(res.contents[0].text);
  assert.deepEqual(body.schemes, ["pl", "uk", "us"]);
  assert.deepEqual(body.tables.map((x) => x.table), ["pl-domestic", "pl-foreign", "uk-domestic", "uk-overseas", "us-gsa"]);
  const prompts = (await c.send("prompts/list", {})).result.prompts;
  assert.deepEqual(prompts.map((p) => p.name), ["claim_trip"]);
});

test("every bundled table names its authority, instrument, source URL and both dates", async (t) => {
  const { c } = open(t);
  await c.init();
  const r = JSON.parse((await c.call("perdiem_rates", {})).text);
  assert.equal(r.tables.length, 5);
  for (const tbl of r.tables) {
    const h = tbl.header;
    for (const field of ["authority", "instrument", "source_url", "effective_date", "retrieved_date", "currency"]) {
      assert.ok(String(h[field] ?? "").trim().length > 0, `${tbl.table} has no ${field}`);
    }
    assert.match(h.source_url, /^https:\/\//, `${tbl.table} source_url`);
    if (tbl.count === 0) {
      assert.ok(String(h.coverage ?? "").length > 0, `${tbl.table} is empty and does not say why`);
    }
    // No table may carry an emoji or an em dash: this text is quoted straight into answers.
    const blob = JSON.stringify(tbl.header);
    assert.ok(!/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}—]/u.test(blob), `${tbl.table} header carries an emoji or an em dash`);
  }
});

test("the free tier is the documented one: rates and calc free, trips capped, export and report Pro", async (t) => {
  const { c } = open(t);
  await c.init();
  for (let i = 0; i < 5; i++) assert.equal((await c.call("trip_record", { ...TRIP, name: `t${i}` })).isError, false);
  assert.equal((await c.call("trip_record", { ...TRIP, name: "t5" })).isError, true);
  assert.equal((await c.call("perdiem_calc", TRIP)).isError, false);
  assert.equal((await c.call("perdiem_rates", {})).isError, false);
  assert.equal((await c.call("trip_list", {})).isError, false);
  assert.equal((await c.call("trip_export", { trip: "t0" })).isError, true);
  assert.equal((await c.call("perdiem_report", {})).isError, true);
});

test("src holds no network call and no stdout write", async (t) => {
  const out = execFileSync("grep", ["-rEn", "fetch\\(|https?://|node:http|node:net|node:dns|console\\.", join(HERE, "src")], { encoding: "utf8" }).trim().split("\n");
  const offending = out.filter((l) => !/\.json:/.test(l) && !/source_url|https:\/\/isap|https:\/\/www\.gov\.uk|https:\/\/www\.gsa\.gov/.test(l));
  assert.deepEqual(offending, [], `network or stdout in src:\n${offending.join("\n")}`);
});
