// Contract suite for delivery-schedule. Generated shape, mechanical assertions only.
//
// Asserts the invariants of servers/delivery-schedule/SPEC.md that a test can check
// without judgement: one version number across package.json, src/version.ts, serverInfo
// and all four registry manifests; the remotes rule (this server is stdio only and must
// advertise no remote until it is hosted); JSON-RPC-only stdout; tool-description hygiene;
// the free/Pro tier switch; that nothing outside this server's own directory is written;
// and that the invoice engine is imported rather than restated. It never asserts a number
// a human chose; those live in test/unit.test.mjs.
import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { client, sandbox, cleanup, proKey, storeDir, writeProfile, seed, REPO, REFERENCE, CREATE, AS_OF_LATE } from "./_client.mjs";

const HERE = join(REPO, "servers", "delivery-schedule");
const PRODUCT = "delivery-schedule";
const MAX_DESCRIPTION = 220;
const HARD_MAX_DESCRIPTION = 1200;
const FILE_ARGS = ["path", "url", "out_path", "template_path"];

/**
 * Tools that already break the description rules on the day this suite was written.
 * The suite is a ratchet: an existing entry is reported, a NEW one fails. The fix is in
 * src, not here.
 */
const OVER_LENGTH_BASELINE = [];

function open(t, opts = {}) {
  const box = sandbox();
  writeProfile(box.dataHome);
  const c = client({ dataHome: box.dataHome, ...opts });
  t.after(() => { c.close(); cleanup(box.dir); });
  return { box, c };
}

test("the version is one number: package.json, src/version.ts, serverInfo and every manifest agree", async (t) => {
  const pkg = JSON.parse(readFileSync(join(HERE, "package.json"), "utf8"));
  assert.equal(pkg.name, "@theluckystrike/mcp-delivery-schedule");
  assert.match(pkg.version, /^\d+\.\d+\.\d+$/, "package version must be a plain semver; the release bump moves it, the test does not pin it");
  assert.ok(pkg.description.length < 100, `package description is ${pkg.description.length} chars`);
  const generated = readFileSync(join(HERE, "src", "version.ts"), "utf8");
  assert.match(generated, /GENERATED by scripts\/sync-versions\.mjs/, "version.ts must be generated, not hand written");
  assert.match(generated, new RegExp(`export const VERSION = "${pkg.version.replace(/\./g, "\\.")}";`),
    `src/version.ts does not carry ${pkg.version}; run node scripts/sync-versions.mjs`);

  const { c } = open(t);
  const info = await c.init();
  assert.equal(info.serverInfo.version, pkg.version, "serverInfo.version must equal the package version");
  assert.equal(info.serverInfo.name, "mcp-delivery-schedule");

  for (const file of ["server.json", "server.mcpb.json", "server.variant.json", "server.milestone.json"]) {
    const j = JSON.parse(readFileSync(join(HERE, file), "utf8"));
    assert.equal(j.version, pkg.version, `${file} version`);
    for (const p of j.packages ?? []) {
      assert.equal(p.version, pkg.version, `${file} package entry version`);
      assert.equal(p.transport.type, "stdio", `${file} declares a transport this server does not speak`);
      if (p.registryType === "mcpb") {
        // "TBD" until the release job hashes the bundle; after that, a real sha256.
        assert.ok(p.fileSha256 === "TBD" || /^[0-9a-f]{64}$/.test(p.fileSha256),
          `${file} fileSha256 is neither TBD nor a sha256: ${p.fileSha256}`);
      }
    }
    // This server is stdio only until the hosted endpoint exists. remotes.json is the
    // switch: while it is absent no manifest may advertise a remote, and the day it lands
    // server.mcpb.json must carry it by value, exactly as every hosted sibling does.
    if (existsSync(join(HERE, "remotes.json"))) {
      const remotes = JSON.parse(readFileSync(join(HERE, "remotes.json"), "utf8"));
      if (file === "server.mcpb.json") assert.deepEqual(j.remotes, remotes, `${file} remotes must equal remotes.json`);
      else assert.equal(j.remotes, undefined, `${file} is a stdio-only name and must not advertise a remote`);
    } else {
      assert.equal(j.remotes, undefined, `${file} advertises a remote, but this server has no remotes.json and is not hosted`);
    }
    assert.ok((j.description ?? "").length < 100, `${file} description is ${(j.description ?? "").length} chars; the registry 422s at 100`);
    assert.ok(!/[,.]\.$|,$/.test(j.description), `${file} description ends in a machine truncation`);
    assert.ok(!/\u2014/.test(JSON.stringify(j)), `${file} carries an em dash`);
  }
  // Three distinct registry names, so the second and third are second listings, not copies.
  const names = ["server.json", "server.variant.json", "server.milestone.json"]
    .map((f) => JSON.parse(readFileSync(join(HERE, f), "utf8")).name);
  assert.equal(new Set(names).size, 3, `registry names must differ: ${names.join(", ")}`);
  assert.deepEqual(names, [
    "io.github.theluckystrike/delivery-schedule",
    "io.github.theluckystrike/deliverable-tracker",
    "io.github.theluckystrike/milestone-schedule",
  ]);

  // And sync-versions --check passes for the whole repo, so no sibling drifted either.
  execFileSync(process.execPath, [join(REPO, "scripts", "sync-versions.mjs"), "--check"], { encoding: "utf8" });
});

test("stdout carries JSON-RPC only across initialize, tools/list, a success and an error", async (t) => {
  const { c } = open(t);
  await c.init();
  await c.tools();
  await c.call("delivery_schedule_create", CREATE);
  await c.call("delivery_schedule_get", { schedule: "DS-2099-0001" });
  await new Promise((r) => setTimeout(r, 150));

  const lines = [...c.stdoutLines, c.tail].filter((l) => l.trim() !== "");
  assert.ok(lines.length >= 4, `expected at least 4 protocol lines, got ${lines.length}`);
  for (const line of lines) {
    let m;
    try { m = JSON.parse(line); } catch { assert.fail(`non-JSON on stdout: ${JSON.stringify(line.slice(0, 200))}`); }
    assert.equal(m.jsonrpc, "2.0", `stdout line is JSON but not JSON-RPC: ${line.slice(0, 200)}`);
  }
});

test("every tool description is non-empty, single-paragraph, and within the ceiling", async (t) => {
  const { c } = open(t);
  await c.init();
  const tools = await c.tools();
  assert.equal(tools.length, 12, "tool count changed; update servers/delivery-schedule/SPEC.md and the README");
  assert.deepEqual(tools.map((x) => x.name).sort(), [
    "deliverable_add", "deliverable_delete", "deliverable_status",
    "delivery_schedule_create", "delivery_schedule_delete", "delivery_schedule_document",
    "delivery_schedule_get", "delivery_schedule_list", "late_report",
    "license_activate", "license_status", "milestone_payload",
  ]);

  for (const tool of tools) {
    const d = tool.description ?? "";
    assert.ok(d.trim().length > 0, `${tool.name} has no description`);
    assert.equal(d, d.trim(), `${tool.name} description has leading or trailing whitespace`);
    assert.ok(d.length <= HARD_MAX_DESCRIPTION, `${tool.name} description is ${d.length} chars, over ${HARD_MAX_DESCRIPTION}`);
    assert.ok(!/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/u.test(d), `${tool.name} description carries an emoji`);
    assert.ok(!/\u2014/.test(d), `${tool.name} description carries an em dash`);
  }

  const over = tools.filter((x) => (x.description ?? "").length > MAX_DESCRIPTION).map((x) => x.name).sort();
  const regressions = over.filter((n) => !OVER_LENGTH_BASELINE.includes(n));
  assert.deepEqual(regressions, [], `new tool descriptions over ${MAX_DESCRIPTION} chars`);
});

test("no tool takes a file path: the document is text and nothing is written outside the store", async (t) => {
  const { c } = open(t);
  await c.init();
  const tools = await c.tools();
  const fileTools = tools.filter((x) => Object.keys(x.inputSchema?.properties ?? {}).some((k) => FILE_ARGS.includes(k)));
  assert.deepEqual(fileTools.map((x) => x.name), []);
});

test("license_status reports free with no key and pro with a signed key", async (t) => {
  const { c: free } = open(t);
  await free.init();
  const f = await free.call("license_status", {});
  assert.equal(f.isError, false, f.text);
  assert.match(f.text, /"tier":\s*"free"/, f.text.slice(0, 300));

  const key = proKey(PRODUCT);
  assert.match(key, /^MCPL1\./);
  const { c: pro } = open(t, { key });
  await pro.init();
  assert.match((await pro.call("license_status", {})).text, /"tier":\s*"pro"/);
});

test("the free tier is the documented one: open, add, move, get, list, delete and the late report are free", async (t) => {
  const { c } = open(t);
  await c.init();
  const id = await seed(c);
  for (const [tool, args] of [
    ["deliverable_add", { schedule: id, description: "Extra page", due_date: "2026-05-20", value_minor: 1000 }],
    ["deliverable_status", { schedule: id, deliverable: "D05", status: "delivered", date: "2026-05-19" }],
    ["deliverable_delete", { schedule: id, deliverable: "D04" }],
    ["delivery_schedule_get", { schedule: id, as_of: AS_OF_LATE }],
    ["delivery_schedule_list", {}],
    ["late_report", { as_of: AS_OF_LATE }],
    ["delivery_schedule_create", { reference: "Q-2026-0500", reference_date: "2026-04-01", client: "Harbour Cafe", title: "Second job" }],
    ["delivery_schedule_delete", { schedule: "Q-2026-0500" }],
  ]) {
    const r = await c.call(tool, args);
    assert.equal(r.isError, false, `${tool} was gated: ${r.text}`);
  }
  for (const [tool, args] of [
    ["delivery_schedule_document", { schedule: id }],
    ["milestone_payload", { schedule: id }],
  ]) {
    const r = await c.call(tool, args);
    assert.equal(r.isError, true, `${tool} answered on the free tier`);
    assert.match(r.text, /Pro is a one-time \$\d+ for this server/, tool);
    assert.match(r.text, /license_activate/, tool);
    // The conversion instrument: every gate link carries the tool that tripped it.
    assert.match(r.text, new RegExp(`src=${PRODUCT}\\.${tool}`), `${tool} gate link is untagged`);
    // And the shared cap sentence: no hand math, then the bundle link, on every gate.
    assert.match(r.text, /any total or journal composed outside them is an estimate/, `${tool} lacks the NO_HAND_MATH sentence`);
    assert.match(r.text, new RegExp(`Or all \\d+ servers for \\$\\d+: https://mcp\\.zovo\\.one/buy/bundle\\?src=${PRODUCT}\\.${tool}\\.bundle$`), `${tool} lacks the bundle sentence`);
  }
});

test("the resource and the prompt are registered and answer", async (t) => {
  const { c } = open(t);
  await c.init();
  const res = (await c.send("resources/read", { uri: "deliveryschedule://contract" })).result;
  const body = JSON.parse(res.contents[0].text);
  assert.deepEqual(body.statuses, ["planned", "in_progress", "delivered", "accepted"], "late must NOT be a stored status");
  assert.equal(body.statuses.includes("late"), false);
  assert.deepEqual(body.open_statuses, ["planned", "in_progress"]);
  assert.deepEqual(body.transitions, { planned: ["in_progress", "delivered"], in_progress: ["delivered"], delivered: ["accepted"], accepted: [] });
  assert.deepEqual(body.lateness_states, ["not_yet_due", "due_today", "late", "delivered_on_time", "delivered_late"]);
  assert.match(body.late_is_not_a_status, /derived from the due date and the as_of the caller passes/);
  assert.equal(body.free_tier.open_schedules, 3);
  assert.deepEqual(body.free_tier.pro_tools.sort(), ["delivery_schedule_document", "milestone_payload"]);
  assert.equal(body.payload_scales.invoice_create, "unit_price in MAJOR units");
  assert.equal(body.payload_scales.quote_create, "unit_price_minor in MINOR units");
  assert.equal(body.one_schedule_per_reference, true);
  assert.equal(body.creates_invoices, false);
  assert.equal(body.creates_quotes, false);
  assert.equal(body.writes.length, 1);
  assert.equal(body.writes[0].store, "delivery-schedule");
  const prompts = (await c.send("prompts/list", {})).result.prompts;
  assert.deepEqual(prompts.map((p) => p.name), ["run_the_schedule"]);
});

test("this server writes its own directory and no sibling store, on any tool", async (t) => {
  const { box, c } = open(t, { key: proKey() });
  await c.init();
  const id = await seed(c);
  await c.call("delivery_schedule_document", { schedule: id, as_of: AS_OF_LATE });
  await c.call("milestone_payload", { schedule: id, as_of: AS_OF_LATE });
  await c.call("late_report", { as_of: AS_OF_LATE });
  await c.call("delivery_schedule_list", {});
  const gone = await c.json("delivery_schedule_create", { reference: "Q-2026-0777", reference_date: "2026-04-01", client: "Gone", title: "Gone" });
  await c.call("delivery_schedule_delete", { schedule: gone.created.id });

  const files = readdirSync(storeDir(box.dataHome)).filter((f) => !f.startsWith("."));
  assert.deepEqual(files.sort(), ["counter.json", "schedules.json"]);
  // The shared profile was READ and must be untouched: one file, the one the test wrote.
  const siblings = readdirSync(join(box.dataHome, "mcp-servers")).sort();
  assert.deepEqual(siblings, ["delivery-schedule", "profile"], `a sibling store was created: ${siblings.join(", ")}`);
  assert.deepEqual(readdirSync(join(box.dataHome, "mcp-servers", "profile")), ["business.json"],
    "this server wrote into the shared profile directory; it must only read business.json");
});

test("the money engine is the invoice server's own, not a copy", async () => {
  // If servers/invoice changes its rounding basis, this server must change with it, which
  // it does because it never implements the arithmetic: it imports it.
  const engine = readFileSync(join(HERE, "src", "schedule.ts"), "utf8");
  assert.match(engine, /import \{[^}]*computeTotals[^}]*\} from "@theluckystrike\/mcp-invoice\/lib";/,
    "the totals must come from the invoice server, never be restated here");
  assert.match(engine, /daysBetween/, "the day count must be the invoice server's daysBetween");
  for (const forbidden of [/function roundHalfUp/, /function computeTotals/, /function daysBetween/, /Math\.round\(/]) {
    assert.equal(forbidden.test(engine), false, `src/schedule.ts reimplements ${forbidden}`);
  }
  const index = readFileSync(join(HERE, "src", "index.ts"), "utf8");
  assert.match(index, /readSharedProfile/, "the default currency must come from the shared business profile");
  assert.equal(/getBusiness|hasBusiness|findClient/.test(index), false, "the invoice store must not be opened: its dataDir creates a directory on read");
  assert.equal(/mcp-work-order|mcp-change-order|mcp-quotes\/lib"[^;]*getQuotes/.test(index), false, "no sibling store is read");
});

test("no minor-unit figure is interpolated into a human-readable string anywhere in src", async () => {
  // D-R100: a bare minor figure written into prose lands beside a MAJOR unit price on the
  // customer's own document, which is the 100x seam in their hands. Every amount printed
  // for a human goes through formatMoney, which carries the currency code.
  for (const file of ["schedule.ts", "index.ts", "store.ts"]) {
    const src = readFileSync(join(HERE, "src", file), "utf8");
    const stripped = src.replace(/^\s*(\/\/|\*|\/\*).*$/gm, "");
    const hits = [...stripped.matchAll(/\$\{[^}]*_minor[^}]*\}/g)]
      .map((m) => m[0])
      .filter((h) => !/^\$\{(money|formatMoney)\(/.test(h));
    assert.deepEqual(hits, [], `src/${file} interpolates a bare minor-unit figure into a string: ${hits.join(", ")}. Every amount printed for a human goes through formatMoney, which carries the currency code`);
  }
});

test("src holds no network call and no stdout write", async () => {
  // grep exits 1 on no match, which is the passing case here.
  let raw = "";
  try {
    raw = execFileSync("grep", ["-rEn", "fetch\\(|https?://|node:http|node:net|node:dns|console\\.", join(HERE, "src")], { encoding: "utf8" });
  } catch (e) {
    if (e.status !== 1) throw e;
  }
  const out = raw.trim().split("\n").filter(Boolean);
  const offending = out.filter((l) => !/mcp\.zovo\.one|github\.com|modelcontextprotocol\.io/.test(l));
  assert.deepEqual(offending, [], `network or stdout in src:\n${offending.join("\n")}`);
});

test("src, tests and docs carry no em dash and no emoji", () => {
  const files = [
    ...readdirSync(join(HERE, "src")).map((f) => join(HERE, "src", f)),
    ...readdirSync(join(HERE, "test")).map((f) => join(HERE, "test", f)),
    join(HERE, "README.md"), join(HERE, "llms-install.md"), join(HERE, "RESULT.md"),
  ].filter(existsSync);
  for (const f of files) {
    const s = readFileSync(f, "utf8");
    assert.equal(s.includes("\u2014"), false, `${f} carries an em dash`);
    assert.equal(/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/u.test(s), false, `${f} carries an emoji`);
  }
});

test("the required files are all present", () => {
  for (const f of [
    "package.json", "tsconfig.json", "README.md", "LICENSE", "SPEC.md", "RESULT.md",
    "server.json", "server.mcpb.json", "server.variant.json", "server.milestone.json",
    "smithery.yaml", "glama.json", "llms-install.md", "Dockerfile",
    "src/index.ts", "src/lib.ts", "src/schedule.ts", "src/store.ts", "src/version.ts",
  ]) {
    assert.ok(existsSync(join(HERE, f)), `missing ${f}`);
  }
});

test("the estate lists this server everywhere a new server has to be registered", () => {
  // The one-line registrations outside this folder. release-check.mjs is the full reader;
  // these are the ones a server cannot ship without, checked here so the omission fails in
  // this suite rather than at bundle time.
  const cases = [
    ["scripts/build-mcpb.sh", /^SERVERS="[^"]*\bdelivery-schedule\b/m, "SERVERS list"],
    ["scripts/build-mcpb.sh", /^\s*\[delivery-schedule\]="/m, "DISPLAY_NAME"],
    ["scripts/build-mcpb.sh", /^\s*\[delivery-schedule\]='\[/m, "KEYWORDS"],
    ["scripts/sync-mirrors.sh", /^ALL_SERVERS="[^"]*\bdelivery-schedule\b/m, "ALL_SERVERS"],
    ["scripts/mirror-seo.py", /^\s*"delivery-schedule":/m, "mirror-seo CAPABILITY"],
    ["scripts/build-pages.mjs", /const ids = \[[^\]]*"delivery-schedule"/, "page ids"],
    ["scripts/gen-spec.mjs", /"delivery-schedule"/, "SPEC generator"],
    ["servers/office-suite/src/index.ts", /id: "delivery-schedule"/, "office-suite CHILDREN"],
    ["servers/invoice/src/index.ts", /"delivery-schedule"/, "PROFILE_READERS"],
  ];
  for (const [file, re, what] of cases) {
    const src = readFileSync(join(REPO, file), "utf8");
    assert.ok(re.test(src), `${file} does not list delivery-schedule in its ${what}`);
  }
});
