// Contract suite for job-card. Mechanical assertions only.
//
// Asserts the invariants of servers/job-card/SPEC.md that a test can check without
// judgement: one version number across package.json, src/version.ts, serverInfo and all
// three registry manifests; the remotes rule (the mcpb manifest carries remotes.json, the
// stdio-only name carries none); JSON-RPC-only stdout; tool-description hygiene; the
// free/Pro tier switch; that nothing outside this server's own two files is written; and
// that the status machine moves one step at a time. It never asserts a number a human
// chose; those live in test/smoke.test.mjs.
import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { client, sandbox, cleanup, proKey, storeDir, JOB, LABOR, MATERIAL, LABOR_VALUE_CENTS, MATERIAL_VALUE_CENTS, REPO } from "./_client.mjs";

const HERE = join(REPO, "servers", "job-card");
const PRODUCT = "job-card";
const MAX_DESCRIPTION = 220;
const HARD_MAX_DESCRIPTION = 1200;
const MANIFESTS = ["server.json", "server.mcpb.json", "server.variant.json"];

/**
 * Tools that already break the description rules on the day this suite was written.
 * The suite is a ratchet: an existing entry is reported, a NEW one fails. The fix is in
 * src, not here.
 */
const OVER_LENGTH_BASELINE = ["job_card_create", "job_card_get", "job_card_log_labor", "job_card_print", "job_card_summary", "job_card_update_status"];

function open(t, opts = {}) {
  const box = sandbox();
  const c = client({ dataHome: box.dataHome, ...opts });
  t.after(() => { c.close(); cleanup(box.dir); });
  return { box, c };
}

test("the version is one number: package.json, src/version.ts, serverInfo and every manifest agree", async (t) => {
  const pkg = JSON.parse(readFileSync(join(HERE, "package.json"), "utf8"));
  assert.equal(pkg.name, "@theluckystrike/mcp-job-card");
  assert.match(pkg.version, /^\d+\.\d+\.\d+$/, "package version must be a plain semver; the release bump moves it, the test does not pin it");
  assert.ok(pkg.description.length < 100, `package description is ${pkg.description.length} chars`);
  const generated = readFileSync(join(HERE, "src", "version.ts"), "utf8");
  assert.match(generated, /GENERATED by scripts\/sync-versions\.mjs/, "version.ts must be generated, not hand written");
  assert.match(generated, new RegExp(`export const VERSION = "${pkg.version.replace(/\./g, "\\.")}";`),
    `src/version.ts does not carry ${pkg.version}; run node scripts/sync-versions.mjs`);

  const { c } = open(t);
  const info = await c.init();
  assert.equal(info.serverInfo.version, pkg.version, "serverInfo.version must equal the package version");
  assert.equal(info.serverInfo.name, "mcp-job-card");

  for (const file of MANIFESTS) {
    const j = JSON.parse(readFileSync(join(HERE, file), "utf8"));
    assert.equal(j.version, pkg.version, `${file} version`);
    for (const p of j.packages ?? []) {
      assert.equal(p.version, pkg.version, `${file} package entry version`);
      assert.equal(p.transport.type, "stdio", `${file} declares a transport this server does not speak`);
      if (p.registryType === "mcpb") {
        // "TBD" until scripts/manifest-sha256.mjs hashes the built bundle; after that, the
        // real digest. A STALE digest is worse than none.
        assert.ok(p.fileSha256 === "TBD" || /^[0-9a-f]{64}$/.test(p.fileSha256),
          `${file} fileSha256 is neither TBD nor a sha256: ${p.fileSha256}`);
      }
    }
    if (file === "server.mcpb.json") {
      const remotes = JSON.parse(readFileSync(join(HERE, "remotes.json"), "utf8"));
      assert.deepEqual(j.remotes, remotes, `${file} remotes must equal remotes.json (hosted at /mcp/job-card)`);
      assert.equal(remotes[0].url, "https://mcp.zovo.one/mcp/job-card");
    } else {
      assert.equal(j.remotes, undefined, `${file} is a stdio-only name and must not advertise a remote`);
    }
    assert.ok((j.description ?? "").length < 100, `${file} description is ${(j.description ?? "").length} chars; the registry 422s at 100`);
    assert.ok(!/[,.]\.$|,$/.test(j.description), `${file} description ends in a machine truncation`);
    assert.ok(!/\u2014/.test(JSON.stringify(j)), `${file} carries an em dash`);
  }
  assert.ok(existsSync(join(HERE, "remotes.json")), "remotes.json is missing: this server has a hosted route in remote/src/index.ts");

  // server.json and server.mcpb.json share the primary name; the variant is the second listing.
  const names = MANIFESTS.map((f) => JSON.parse(readFileSync(join(HERE, f), "utf8")).name);
  assert.equal(new Set(names).size, 2, `registry names must be one primary and one variant: ${names.join(", ")}`);
  assert.deepEqual(names, [
    "io.github.theluckystrike/job-card",
    "io.github.theluckystrike/job-card",
    "io.github.theluckystrike/job-card-template",
  ]);

  execFileSync(process.execPath, [join(REPO, "scripts", "sync-versions.mjs"), "--check"], { encoding: "utf8" });
});

test("every registry name carries a token this server can actually be found on", () => {
  // Registry search matches a substring of the FULL name and nothing else; the description
  // is never searched. So the tokens this server is meant to be findable on have to be IN
  // the names, and this asserts they are rather than assuming it.
  const joined = MANIFESTS.map((f) => JSON.parse(readFileSync(join(HERE, f), "utf8")).name.toLowerCase()).join(" ");
  for (const token of ["job", "card", "template"]) {
    assert.ok(joined.includes(token), `no registry name carries the token "${token}"`);
  }
});

test("stdout carries JSON-RPC only across initialize, tools/list, a success and an error", async (t) => {
  const { c } = open(t);
  await c.init();
  await c.tools();
  await c.call("job_card_create", JOB);
  await c.call("job_card_get", { card: "JC-2099-0001" });
  await new Promise((r) => setTimeout(r, 150));

  const lines = c.stdoutLines.filter((l) => l.trim() !== "");
  assert.ok(lines.length >= 4, `expected at least 4 protocol lines, got ${lines.length}`);
  for (const line of lines) {
    let m;
    try { m = JSON.parse(line); } catch { assert.fail(`non-JSON on stdout: ${JSON.stringify(line.slice(0, 200))}`); }
    assert.equal(m.jsonrpc, "2.0", `stdout line is JSON but not JSON-RPC: ${line.slice(0, 200)}`);
  }
});

test("every tool description is non-empty, single-paragraph, and within the ceiling", async (t) => {
  const { c } = open(t);
  await c.init();
  const tools = await c.tools();
  assert.equal(tools.length, 11, "tool count changed; update servers/job-card/SPEC.md");
  assert.deepEqual(tools.map((x) => x.name).sort(), [
    "job_card_create", "job_card_delete", "job_card_get", "job_card_list",
    "job_card_log_labor", "job_card_log_material", "job_card_print", "job_card_summary",
    "job_card_update_status", "license_activate", "license_status",
  ]);

  for (const tool of tools) {
    const d = tool.description ?? "";
    assert.ok(d.trim().length > 0, `${tool.name} has no description`);
    assert.equal(d, d.trim(), `${tool.name} description has leading or trailing whitespace`);
    assert.ok(d.length <= HARD_MAX_DESCRIPTION, `${tool.name} description is ${d.length} chars, over ${HARD_MAX_DESCRIPTION}`);
    assert.ok(!/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/u.test(d), `${tool.name} description carries an emoji`);
    assert.ok(!/\u2014/.test(d), `${tool.name} description carries an em dash`);
  }

  const over = tools.filter((x) => (x.description ?? "").length > MAX_DESCRIPTION).map((x) => x.name).sort();
  assert.deepEqual(over.filter((n) => !OVER_LENGTH_BASELINE.includes(n)), [], `new tool descriptions over ${MAX_DESCRIPTION} chars`);
});

test("no tool takes a file path, so nothing here writes outside its own data directory", async (t) => {
  const { c } = open(t);
  await c.init();
  const tools = await c.tools();
  const FILE_ARGS = ["path", "url", "out_path", "template_path"];
  const fileTools = tools.filter((x) => Object.keys(x.inputSchema?.properties ?? {}).some((k) => FILE_ARGS.includes(k)));
  assert.deepEqual(fileTools.map((x) => x.name), [], "a file-path argument appeared; job_card_print returns text and writes nothing");
});

test("license_status reports free with no key and pro with a signed key", async (t) => {
  const { c: free } = open(t);
  await free.init();
  const f = await free.call("license_status", {});
  assert.equal(f.isError, false, f.text);
  assert.match(f.text, /"tier":\s*"free"/, f.text.slice(0, 300));

  const key = proKey(PRODUCT);
  assert.match(key, /^MCPL1\./);
  const { c: pro } = open(t, { key });
  await pro.init();
  assert.match((await pro.call("license_status", {})).text, /"tier":\s*"pro"/);
});

test("a licence for another product does not unlock this one", async (t) => {
  const { c } = open(t, { key: proKey("not-a-real-product") });
  await c.init();
  assert.match((await c.call("license_status", {})).text, /"tier":\s*"free"/);
});

test("the free tier is the documented one: everything but the eleventh active card", async (t) => {
  const { c } = open(t);
  await c.init();
  const j = await c.json("job_card_create", JOB);
  const id = j.created.id;
  for (const [tool, args] of [
    ["job_card_log_labor", { card: id, ...LABOR }],
    ["job_card_log_material", { card: id, ...MATERIAL }],
    ["job_card_update_status", { card: id, status: "in_progress", date: "2026-03-09" }],
    ["job_card_list", {}],
    ["job_card_get", { card: id }],
    ["job_card_print", { card: id }],
    ["job_card_summary", { date: "2026-03-09" }],
  ]) {
    const r = await c.call(tool, args);
    assert.equal(r.isError, false, `${tool} was gated: ${r.text}`);
  }
});

test("the free-tier active-card cap carries the tagged link and the bundle, and nothing is written", async (t) => {
  const { box, c } = open(t);
  await c.init();
  for (let i = 1; i <= 10; i++) await c.json("job_card_create", { ...JOB, description: `Job number ${i}` });
  const r = await c.call("job_card_create", { ...JOB, description: "Job number 11" });
  assert.ok(r.isError, r.text);
  assert.match(r.text, /Pro is a one-time \$\d+ for this server/);
  assert.match(r.text, /license_activate/);
  assert.match(r.text, new RegExp(`src=${PRODUCT}\\.job_card_create`), "the gate link is untagged");
  assert.match(r.text, /buy\/bundle/);
  const cards = JSON.parse(readFileSync(join(storeDir(box.dataHome), "cards.json"), "utf8"));
  assert.equal(cards.length, 10, "the refused eleventh card was written");
});

test("an archived card frees its slot on the free tier", async (t) => {
  const { c } = open(t);
  await c.init();
  for (let i = 1; i <= 10; i++) await c.json("job_card_create", { ...JOB, description: `Job number ${i}` });
  const j = await c.json("job_card_list", {});
  const first = j.cards.find((x) => x.status === "open");
  for (const status of ["in_progress", "done", "invoiced", "archived"]) {
    assert.equal((await c.call("job_card_update_status", { card: first.id, status, date: "2026-03-10" })).isError, false, status);
  }
  const again = await c.call("job_card_create", { ...JOB, description: "Job number 11" });
  assert.equal(again.isError, false, `archiving did not free the slot: ${again.text}`);
});

test("the status machine moves one step at a time and a skipped step is refused", async (t) => {
  const { c } = open(t);
  await c.init();
  const j = await c.json("job_card_create", JOB);
  const id = j.created.id;
  const skip = await c.call("job_card_update_status", { card: id, status: "done", date: "2026-03-09" });
  assert.ok(skip.isError, "open jumped straight to done");
  assert.match(skip.text, /one step at a time/);
  const same = await c.call("job_card_update_status", { card: id, status: "open", date: "2026-03-09" });
  assert.ok(same.isError, "re-stamping the current status was allowed");
});

test("a card holding labor or materials cannot be deleted", async (t) => {
  const { c } = open(t);
  await c.init();
  const j = await c.json("job_card_create", JOB);
  await c.call("job_card_log_labor", { card: j.created.id, ...LABOR });
  const r = await c.call("job_card_delete", { card: j.created.id });
  assert.ok(r.isError, "a card holding labor was deleted");
  const empty = await c.json("job_card_create", { ...JOB, description: "Typed twice, nothing logged" });
  assert.equal((await c.call("job_card_delete", { card: empty.created.id })).isError, false, "an empty card was not deletable");
});

test("the running totals are the sums of the stored line values, in integer cents", async (t) => {
  const { c } = open(t);
  await c.init();
  const j = await c.json("job_card_create", JOB);
  await c.call("job_card_log_labor", { card: j.created.id, ...LABOR });
  await c.call("job_card_log_material", { card: j.created.id, ...MATERIAL });
  const got = await c.json("job_card_get", { card: j.created.id });
  assert.equal(got.labor_total_cents, LABOR_VALUE_CENTS, JSON.stringify(got).slice(0, 300));
  assert.equal(got.materials_total_cents, MATERIAL_VALUE_CENTS);
  assert.equal(got.grand_total_cents, LABOR_VALUE_CENTS + MATERIAL_VALUE_CENTS);
});

test("there are no resources and no prompts on this server: both methods answer Method not found", async (t) => {
  const { c } = open(t);
  await c.init();
  const res = await c.send("resources/list", {});
  const pr = await c.send("prompts/list", {});
  for (const r of [res, pr]) {
    // No capability is registered, so the SDK answers Method not found rather than an empty list.
    assert.equal(r.error?.code, -32601, JSON.stringify(r).slice(0, 200));
  }
});

test("this server writes two files and no others, on any tool", async (t) => {
  const { box, c } = open(t, { key: proKey() });
  await c.init();
  const j = await c.json("job_card_create", JOB);
  await c.call("job_card_log_labor", { card: j.created.id, ...LABOR });
  await c.call("job_card_log_material", { card: j.created.id, ...MATERIAL });
  await c.call("job_card_update_status", { card: j.created.id, status: "in_progress", date: "2026-03-09" });
  await c.call("job_card_print", { card: j.created.id });
  await c.call("job_card_print", { card: j.created.id, format: "html" });
  await c.call("job_card_list", {});
  await c.call("job_card_summary", { date: "2026-03-09" });
  const empty = await c.json("job_card_create", { ...JOB, description: "Entered by mistake" });
  await c.call("job_card_delete", { card: empty.created.id });

  const files = readdirSync(storeDir(box.dataHome)).filter((f) => !f.startsWith("."));
  assert.deepEqual(files.sort(), ["cards.json", "counter.json"]);
  const siblings = readdirSync(join(box.dataHome, "mcp-servers"));
  assert.deepEqual(siblings, ["job-card"], `a sibling store was touched: ${siblings.join(", ")}`);
});

test("src holds no network call and no stdout write", async () => {
  let raw = "";
  try {
    raw = execFileSync("/usr/bin/grep", ["-rEn", "fetch\\(|https?://|node:http|node:net|node:dns|console\\.", join(HERE, "src")], { encoding: "utf8" });
  } catch (e) {
    if (e.status !== 1) throw e;
  }
  const offending = raw.trim().split("\n").filter(Boolean)
    .filter((l) => !/mcp\.zovo\.one|github\.com|modelcontextprotocol\.io/.test(l));
  assert.deepEqual(offending, [], `network or stdout in src:\n${offending.join("\n")}`);
});

test("src, tests and docs carry no em dash and no emoji", () => {
  const files = [
    ...readdirSync(join(HERE, "src")).map((f) => join(HERE, "src", f)),
    ...readdirSync(join(HERE, "test")).map((f) => join(HERE, "test", f)),
    join(HERE, "README.md"), join(HERE, "llms-install.md"), join(HERE, "RESULT.md"), join(HERE, "SPEC.md"),
  ].filter(existsSync);
  for (const f of files) {
    const s = readFileSync(f, "utf8");
    assert.equal(s.includes("\u2014"), false, `${f} carries an em dash`);
    assert.equal(/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/u.test(s), false, `${f} carries an emoji`);
  }
});

test("the required files are all present", () => {
  for (const f of [
    "package.json", "tsconfig.json", "README.md", "LICENSE", "SPEC.md", "RESULT.md",
    "server.json", "server.mcpb.json", "server.variant.json",
    "smithery.yaml", "glama.json", "llms-install.md", "Dockerfile",
    "src/index.ts", "src/card.ts", "src/store.ts", "src/version.ts",
  ]) {
    assert.ok(existsSync(join(HERE, f)), `missing ${f}`);
  }
});

test("the estate lists this server everywhere a new server has to be registered", () => {
  // The one-line registrations outside this folder. release-check.mjs is the full reader;
  // these are the ones a server cannot ship without, checked here so the omission fails in
  // this suite rather than at bundle time. Copied from the checklist suite, which is where
  // this pattern was established. This server reads no shared profile, so PROFILE_READERS
  // correctly does NOT list it and there is no positive case to assert here.
  const cases = [
    ["scripts/build-mcpb.sh", /^SERVERS="[^"]*\bjob-card\b/m, "SERVERS list"],
    ["scripts/build-mcpb.sh", /^\s*\[job-card\]="/m, "DISPLAY_NAME"],
    ["scripts/build-mcpb.sh", /^\s*\[job-card\]='\[/m, "KEYWORDS"],
    ["scripts/build-pages.mjs", /const ids = \[[^\]]*"job-card"/, "page ids"],
    ["scripts/gen-spec.mjs", /"job-card"/, "SPEC generator"],
    ["servers/office-suite/src/index.ts", /id: "job-card"/, "office-suite CHILDREN"],
    ["data/facts.json", /"job-card":/, "facts tagline, which the README table is generated from"],
    ["data/distribution.json", /"job-card":/, "distribution per_server"],
    ["data/tools.json", /"job-card":/, "tools.json, which the storefront tool tables read"],
    ["scripts/sync-mirrors.sh", /^ALL_SERVERS="[^"]*\bjob-card\b/m, "ALL_SERVERS"],
    ["scripts/mirror-seo.py", /^\s*"job-card":/m, "mirror-seo CAPABILITY and topics"],
  ];
  for (const [file, re, what] of cases) {
    const src = readFileSync(join(REPO, file), "utf8");
    assert.ok(re.test(src), `${file} does not list job-card in its ${what}`);
  }
});

test("the hosted registration is exactly one of two honest states", () => {
  // The hosted route for this server exists in remote/src/index.ts and the worker deploy is
  // pending (docs/HOSTED_LOOP34.md). data/distribution.json must say one of two things and
  // nothing in between: "none by design" is a narrative from before the route existed and is
  // now stale, but the ONLY string that means live is the exact published URL, because
  // scripts/kpi.mjs counts hosted servers by string match.
  const dist = JSON.parse(readFileSync(join(REPO, "data", "distribution.json"), "utf8"));
  const hosted = String(dist.per_server["job-card"].hosted);
  const published = "published https://mcp.zovo.one/mcp/job-card";
  assert.ok(hosted === published || hosted.startsWith("none by design") || hosted.startsWith("pending deploy:"),
    `distribution.json per_server.job-card.hosted is neither the exact published string nor a none-by-design note: ${hosted}`);
  // And the live-validation remote sweep covers this server, added by the hosting loop.
  const validate = readFileSync(join(REPO, "scripts", "validate.mjs"), "utf8");
  const remoteBlock = validate.slice(validate.indexOf("async function remote()"));
  assert.ok(remoteBlock.includes('"job-card"'), "scripts/validate.mjs remote() does not probe job-card");
});
