// GENERATED by scripts/build-figures.mjs. Do not edit by hand.
//
// Every number a guide page is allowed to quote lives here, read out of the repository at
// build time. Regenerate with `node scripts/build-figures.mjs`; `--check` fails when this
// file no longer matches the sources. billing/test/figures.test.mjs runs the check.
//
// TOOLS is the STDIO tool count: server.registerTool calls in servers/<id>/src/index.ts.
// The hosted wrapper adds file-transfer tools to some servers, so the hosted count can be
// higher. Pages must say "stdio" when they quote it.

/** Every server directory with a TypeScript entry point, sorted. */
export const SERVER_IDS = [
  "amortization",
  "asset-register",
  "bank-statement",
  "barcode",
  "billing-docs",
  "calendar",
  "cash-book",
  "catalogue",
  "change-order",
  "checklist",
  "clauses",
  "currency",
  "delivery-schedule",
  "deposits",
  "docx",
  "expense-tracker",
  "image",
  "invoice",
  "kanban",
  "office-suite",
  "packing-list",
  "pdf",
  "per-diem",
  "petty-cash",
  "price-tracker",
  "quotes",
  "recurring",
  "resume",
  "spreadsheet",
  "statement-of-account",
  "time-tracker",
  "timezone",
  "work-order",
  "zip"
];

/** Servers that register tools of their own, i.e. everything office-suite spawns. */
export const CHILD_IDS = [
  "amortization",
  "asset-register",
  "bank-statement",
  "barcode",
  "billing-docs",
  "calendar",
  "cash-book",
  "catalogue",
  "change-order",
  "checklist",
  "clauses",
  "currency",
  "delivery-schedule",
  "deposits",
  "docx",
  "expense-tracker",
  "image",
  "invoice",
  "kanban",
  "packing-list",
  "pdf",
  "per-diem",
  "petty-cash",
  "price-tracker",
  "quotes",
  "recurring",
  "resume",
  "spreadsheet",
  "statement-of-account",
  "time-tracker",
  "timezone",
  "work-order",
  "zip"
];

/** Servers answering at https://mcp.zovo.one/mcp/<id>, read from remote/src/index.ts. */
export const HOSTED_IDS = [
  "time-tracker",
  "price-tracker",
  "invoice",
  "expense-tracker",
  "spreadsheet",
  "currency",
  "timezone",
  "docx",
  "resume",
  "recurring",
  "clauses",
  "pdf",
  "calendar",
  "kanban",
  "image",
  "bank-statement",
  "quotes",
  "barcode",
  "zip",
  "billing-docs",
  "deposits",
  "per-diem",
  "asset-register",
  "statement-of-account",
  "cash-book",
  "amortization",
  "petty-cash",
  "work-order",
  "catalogue",
  "change-order"
];

/** stdio tools each server registers, excluding the shared license pair. */
export const TOOLS = {
  "amortization": 7,
  "asset-register": 7,
  "bank-statement": 10,
  "barcode": 8,
  "billing-docs": 14,
  "calendar": 10,
  "cash-book": 7,
  "catalogue": 10,
  "change-order": 9,
  "checklist": 14,
  "clauses": 10,
  "currency": 8,
  "delivery-schedule": 10,
  "deposits": 9,
  "docx": 9,
  "expense-tracker": 12,
  "image": 10,
  "invoice": 11,
  "kanban": 15,
  "office-suite": 0,
  "packing-list": 12,
  "pdf": 10,
  "per-diem": 7,
  "petty-cash": 7,
  "price-tracker": 8,
  "quotes": 10,
  "recurring": 12,
  "resume": 8,
  "spreadsheet": 8,
  "statement-of-account": 6,
  "time-tracker": 12,
  "timezone": 9,
  "work-order": 10,
  "zip": 7
};

/** Tools @theluckystrike/mcp-license adds to every server. */
export const LICENSE_TOOLS = 2;

/** Sum of TOOLS over CHILD_IDS. */
export const OWN_TOOLS_TOTAL = 316;

/** Distinct tool names office-suite exposes: every child's own tools, plus the shared
 * license pair once. Reconciles with the independently measured OFFICE_SUITE_TOOLS in
 * billing/src/index.js, taken over stdio from the running bundle on 2026-09-07. */
export const OFFICE_SUITE_TOOLS = 318;

/** Servers the site actually lists, i.e. those with a README that becomes a /s/ page. */
export const LISTED_IDS = [
  "amortization",
  "asset-register",
  "bank-statement",
  "barcode",
  "billing-docs",
  "calendar",
  "cash-book",
  "catalogue",
  "change-order",
  "checklist",
  "clauses",
  "currency",
  "delivery-schedule",
  "deposits",
  "docx",
  "expense-tracker",
  "image",
  "invoice",
  "kanban",
  "office-suite",
  "packing-list",
  "pdf",
  "per-diem",
  "petty-cash",
  "price-tracker",
  "quotes",
  "recurring",
  "resume",
  "spreadsheet",
  "statement-of-account",
  "time-tracker",
  "timezone",
  "work-order",
  "zip"
];
export const LISTED_CHILD_IDS = [
  "amortization",
  "asset-register",
  "bank-statement",
  "barcode",
  "billing-docs",
  "calendar",
  "cash-book",
  "catalogue",
  "change-order",
  "checklist",
  "clauses",
  "currency",
  "delivery-schedule",
  "deposits",
  "docx",
  "expense-tracker",
  "image",
  "invoice",
  "kanban",
  "packing-list",
  "pdf",
  "per-diem",
  "petty-cash",
  "price-tracker",
  "quotes",
  "recurring",
  "resume",
  "spreadsheet",
  "statement-of-account",
  "time-tracker",
  "timezone",
  "work-order",
  "zip"
];

/** Counts, computed so prose cannot go stale. LISTED_COUNT is the one a visitor should
 * ever see: SERVER_DIR_COUNT can be ahead of it while a new server is being built. */
export const LISTED_COUNT = 34;
export const LISTED_CHILD_COUNT = 33;
export const SERVER_DIR_COUNT = 34;
export const CHILD_COUNT = 33;
export const HOSTED_COUNT = 30;

/** Hosted limits, read from remote/src/index.ts. */
export const RATE_LIMIT_FREE = 600;
export const RATE_LIMIT_PRO = 6000;
export const DISCOVERY_LIMIT = 120;
export const TOKEN_MINTS_PER_IP = 10;
export const ANON_TOKEN_DAYS = 30;
export const SWEEP_AFTER_DAYS = 35;

/** Prices, read from data/facts.json. */
export const SINGLE_USD = 19;
export const BUNDLE_USD = 39;

/** Published version, read from servers/<id>/server.json. */
export const VERSION = "0.21.0";

/** The free-tier sentence for each server, verbatim from data/facts.json. */
export const FREE = {
  "amortization": "loan_schedule is free and unlimited on every tier: the payment and the interest are the question this server exists to answer, and a free tier that hides the answer is a demo. The meter is on the number of agreements held, three loans in the register, which is the unit of work.",
  "asset-register": "Depreciation schedules are unlimited on every tier: the rates are public information a tax authority published, and metering the reading of a regulation would be charging for the government's work. The cap is on the SIZE of the register, 10 assets, plus unlimited asset_list and asset_dispose.",
  "bank-statement": "2 accounts, 12 months of transactions, 5 rules, summary and search, reconciliation 31 days at a time, recurring detection over the last 3 months (5 charges).",
  "barcode": "20 codes per calendar month, SVG output at any size, every symbology, EPC SEPA payment codes, WiFi and vCard codes, and the local register.",
  "billing-docs": "5 documents per calendar month, credit notes and purchase orders together, counted by issue date, with full, partial and per-line credit notes, VAT, multiple currencies and receiving orders all included, and both text exports never metered.",
  "calendar": "2 calendars, windows up to 31 days, exports up to 50 events, conflict checks answered over the first 31 days of any window.",
  "cash-book": "trial_balance and ledger_lines are free and unlimited on every tier: whether the books add up is the question this server exists for, and a free tier that hides the answer is a demo. The meter is on the PERIOD, three distinct periods a calendar month, keyed by from, to and currency, so rebuilding one already in the register is free forever on every tier.",
  "catalogue": "25 SKUs, the one standard price tier, unlimited rate cards, and every text answer including lines_resolve and price_list_text. Withholding lines_resolve would withhold the one thing the sibling servers came here for, and a price list nobody can read is not a price list. sku_delete is free on every tier and the resolution register is what makes that safe: a code that has priced a line, or that a rate card points at, is refused by name with the times it was used and the last resolution id, because a code printed on a document somebody sent is a fact about that document. A byte-identical duplicate is refused BEFORE the free cap is consulted, and the adversarial suite asserts that refusal text does not contain \"free tier\": a duplicate is one product filed twice far more often than it is two products, and it burns neither a slot nor a place in the list.",
  "change-order": "Five OPEN change orders, draft and sent, and 200 lines each on every tier. The cap counts the ones the client has not answered rather than the ones ever raised, so approving, rejecting or voiding one frees its slot, and change_order_delete on a draft with no lines is free on every tier, because a way back that only a Pro key can reach is not a way back. contract_value is free on every tier: the running value is the thing the change orders exist to answer, and withholding it would withhold the record. A byte-identical change order is refused BEFORE the cap is consulted, so the refusal names the id already stored rather than selling an upgrade, and burns neither a slot nor a CO number.",
  "checklist": "Three checklists, and UNLIMITED RUNS of them on every tier, because capping the running of a checklist would cap the only thing a checklist is for. Up to 500 steps on a checklist on every tier. Every read, every count, the failures, the outstanding list and the run report TEXT are free. Deleting a checklist frees its slot, and the runs already made from it stay readable, because each run carries its own copy of the steps.",
  "clauses": "Starter set plus 10 own clauses, search with the jurisdiction filter, assembly up to 8 clauses, markdown export.",
  "currency": "Latest rates, convert, convert_many, fx_rates_for, history up to 90 days (a wider window is shortened and answered, not refused).",
  "delivery-schedule": "Three OPEN delivery schedules, and 200 deliverables on each on every tier. The cap counts the jobs that still owe something rather than the jobs ever run, so accepting the last deliverable completes a schedule and frees its slot without deleting the record, and delivery_schedule_delete on an empty one is free on every tier, because a way back that only a Pro key can reach is not a way back. late_report is free on every tier: what is late is the question the server exists for, and withholding it would withhold the one answer the client is going to ask for. A second schedule against a reference that already has one is refused BEFORE the cap is consulted, so the refusal names the id already stored rather than selling an upgrade.",
  "deposits": "5 deposits recorded per calendar month, counted by received date, with applying to invoices, refunds, lists, balances and the text statement all unlimited on every tier: a cap that trapped a client's deposit would be a limit on their money rather than on yours.",
  "docx": "Create, convert and read documents without limit; 3 proposals or contracts per calendar month; templates up to 10 placeholders.",
  "expense-tracker": "Unlimited logging; list and summary cover the last 30 days; 3 projects; 5 rules; CSV export up to 200 rows, never partial.",
  "image": "Info, resize, convert, compress, crop, strip metadata on images up to 4 MP; batches of 5.",
  "invoice": "3 invoices per calendar month; overdue report free; PDF carries a small footer line.",
  "kanban": "3 projects, 200 open tasks, default columns.",
  "office-suite": "Each child's free tier.",
  "packing-list": "Three OPEN packing lists, draft and packed, with unlimited cartons, packed lines and declared order lines on every tier. The cap counts shipments in flight rather than shipments ever made, so marking one shipped or cancelling it frees its slot, and deleting a draft is free on every tier, because a way back that only a Pro key can reach is not a way back. carton_report, packing_shortfall, packing_list_show and the packing slip TEXT are free on every tier: those are the questions this server exists to answer, and a free tier that withheld them would withhold the reason to install it.",
  "pdf": "Info, count, text, merge up to 5 files, edits on files up to 30 pages, PAID and DRAFT stamps.",
  "per-diem": "Rate lookups and calculations are unlimited on every tier: the tables are public regulation, and metering the reading of a regulation would be charging for the tax authority's work. 5 trips saved per calendar month, counted by start date, and unlimited trip lists.",
  "petty-cash": "reconcile is free and unlimited on every tier: whether the cash in the tin matches the paperwork is the question this server exists to answer, and a free tier that withholds the answer is a demo. voucher_delete and topup_record are free for the same reason -- a voucher typed in twice would otherwise cost a slot with no way back but a key. The meter is on the volume of record keeping: one float, and twenty vouchers a calendar month, which is a real one-tin office.",
  "price-tracker": "Unlimited price checks with extraction confidence; 3 watches with 30 observations each; alerts_pending free; redirects off product pages are refused.",
  "quotes": "5 open quotes at a time, unlimited pasteable text quotes, accept, decline, revise, VAT, discounts and multi-currency, pipeline and win-rate report for the current calendar year to date.",
  "recurring": "3 active schedules, 30-day upcoming view, generate due invoices.",
  "resume": "Profile, modern-style resume, markdown and HTML exports, 3 cover letters per calendar month, tailoring on job posts up to 2,000 characters.",
  "spreadsheet": "Read, query (filters, group by, sum/avg/min/max), stats and find on files up to 5,000 rows; writes up to 500 rows, never a partial file above that.",
  "statement-of-account": "statement_aging is free and unlimited on every tier, for one client or for everyone: who owes me money is the question this server exists for, and a free tier that hides it is a demo. The meter is on the document that goes to a client, five distinct statements a calendar month, counted by client, period and currency, so rebuilding one already in the register is free forever. Plain-text statements and dunning at the friendly and firm levels are free.",
  "time-tracker": "Unlimited timers and entries; reports, lists and CSV cover the last 7 days; 2 projects with rates. Currency per entry (EUR, USD, GBP, PLN).",
  "timezone": "Conversions, overlap, DST, business days, slots for up to 3 participants over 5 days, 5 contacts, 3 ics per month.",
  "work-order": "Five OPEN work orders, which is a one-van trade, and 200 lines each on every tier. The cap counts open jobs (draft, scheduled, in progress) rather than jobs ever raised, so finishing one frees its slot, and work_order_delete on a draft with no lines is free on every tier because a way back that only a Pro key can reach is not a way back. The text completion report is free: handing the customer what was done is the thing the job was for. A byte-identical work order is refused BEFORE the cap is consulted, so the refusal names the id already stored rather than selling an upgrade, and burns neither a slot nor a WO number.",
  "zip": "20 archives per calendar month, up to 25 MB and 200 entries each, and unlimited reading: zip_list, zip_extract and zip_extract_text are never metered, along with every bomb, traversal and symlink guard."
};

/** The Pro sentence for each server, verbatim from data/facts.json. */
export const PRO = {
  "amortization": "Unlimited loans, loan_repay_early for settling or overpaying at any period costed gross and net of the penalty, loan_journal with its expense-tracker payload carrying the interest alone, and loans_report: what is owed per currency, when each next payment falls due, and the interest charged in a calendar year.",
  "asset-register": "Unlimited assets in the register, the monthly journal entry with its ready-made expense_add payload (one per currency, no vat_rate because depreciation is a book charge), and the report of net book value by category and currency with the year's charge and every disposal in it.",
  "bank-statement": "Unlimited accounts, history and rules, reconciliation over any range, every recurring charge, export.",
  "barcode": "Unlimited codes, PNG output from 32 to 4000 px, and barcode_batch for up to 500 codes in one call.",
  "billing-docs": "Unlimited documents, both A4 PDFs with your logo and no footer credit, and the billing_docs_report of credited, on-order and overdue deliveries.",
  "calendar": "Unlimited calendars, any window, unlimited exports, URL refresh.",
  "cash-book": "Unlimited periods, month_close with its trial balance snapshot and its list of what the month leaves unposted or inconsistent, ledger_export_csv as RFC 4180 text with no file written, and ledger_report with the movement and closing balance per account plus the purchase commitments held as a memo.",
  "catalogue": "An unlimited catalogue, price tiers beyond standard so trade and wholesale are a second column rather than a second catalogue, price_list_pdf as an A4 page, and catalogue_report: how many rows are in force today, which rows a later row already replaces, and which SKUs carry no price in the profile's default currency, which are the rows that stop a resolution dead.",
  "change-order": "Unlimited open change orders, change_order_document as a plain-text document with every line, its reason, the contract value before and after and an approval block for the client to sign, and change_order_invoice_payload: the approved delta as invoice_create items in MAJOR units and quote_create items in MINOR units at once, with VAT at the shared profile rate and rounding_drift_minor asserted to zero.",
  "checklist": "Unlimited checklists, and run_report writing the report to a .txt file at a path you name. The path goes through a bounded ancestor walk rather than mkdirSync with recursive, so a caller-supplied path under /proc, /sys or /dev fails in milliseconds instead of retrying forever; a URL is refused by name before any resolution, so the refusal never leaks the server's working directory; and an existing file is refused unless overwrite is passed.",
  "clauses": "Unlimited clauses, tag filters, JSON import and export, unlimited assembly, clause versions.",
  "currency": "Full history back to 1999, any-date rates, unlimited history windows.",
  "delivery-schedule": "Unlimited open schedules, delivery_schedule_document as a plain-text document with every deliverable, its due date, its status, the delivered and accepted dates, the counts as at a date and a sign-off block for the client, and milestone_payload: the delivered-and-accepted deliverables as invoice_create items in MAJOR units and quote_create items in MINOR units at once, with VAT at the shared profile rate, rounding_drift_minor asserted to zero, and anything left out listed by name under excluded rather than billed as zero.",
  "deposits": "Unlimited deposits recorded, the A4 deposit statement PDF with your logo and no footer credit, and the deposits_report of held per currency, oldest held and what has sat unapplied.",
  "docx": "Unlimited proposals and contracts, letterhead with logo and colours, unlimited template fills.",
  "expense-tracker": "Full history, unlimited projects and rules, xlsx export, unlimited rebill items with markup.",
  "image": "Unlimited size and batches, custom watermark text, dominant colours.",
  "invoice": "Unlimited invoices, no branding, logo, custom prefix.",
  "kanban": "Unlimited projects and tasks, custom columns, weekly review history, estimates versus actuals.",
  "office-suite": "The $39 bundle key unlocks every child.",
  "packing-list": "Unlimited open packing lists, and packing_slip writing the slip to a .txt file at a path you name. The path goes through a bounded ancestor walk rather than mkdirSync with recursive, so a caller-supplied path under /proc, /sys or /dev fails in milliseconds instead of retrying forever; a URL is refused by name before any resolution, so the refusal never leaks the server's working directory; and an existing file is refused unless overwrite is passed.",
  "pdf": "Unlimited files and pages, custom stamp text and colours, business watermark, page reorder.",
  "per-diem": "Unlimited trips saved, the expense-tracker export payloads (one per currency, ready for expense_add), and the report of totals per scheme and per calendar month.",
  "petty-cash": "Unlimited floats and vouchers, replenish_request with the amount that restores the imprest, the vouchers it reimburses, the per-category expense_add-ready payload and the balanced double entry, and float_report with the balance against the imprest, what is unreconciled, the last count and the history of every difference a count has found.",
  "price-tracker": "Unlimited watches, full history, refresh all.",
  "quotes": "Unlimited open quotes, A4 PDF with your logo and no footer credit, pipeline and win-rate report over any date range.",
  "recurring": "Unlimited schedules, 12-month forecast, audit history, end-of-month and anchor-day rules.",
  "resume": "All styles, unlimited cover letters and tailoring, profile variants, letterhead colours.",
  "spreadsheet": "No limits.",
  "statement-of-account": "Unlimited statements, the A4 PDF on the same page layout as your invoices with your logo and no footer credit, the level 3 final demand, and statements_report: every client at once, totalled per currency, ranked by what is overdue rather than by what is large, with the oldest overdue invoice in the whole book named.",
  "time-tracker": "Full history, invoice_summary, group by tag, unlimited rated projects.",
  "timezone": "Unlimited participants, days, contacts and ics files, recurring slot search.",
  "work-order": "Unlimited open work orders, the A4 completion report PDF with the sign-off block, work_order_invoice_payload with VAT at the shared profile rate and rounding_drift_minor asserted to zero, and work_orders_report: the whole board by status, hours logged this month, and unbilled value per currency.",
  "zip": "Unlimited archives, no size cap and no entry cap."
};

const ONES = [
  "zero",
  "one",
  "two",
  "three",
  "four",
  "five",
  "six",
  "seven",
  "eight",
  "nine",
  "ten",
  "eleven",
  "twelve",
  "thirteen",
  "fourteen",
  "fifteen",
  "sixteen",
  "seventeen",
  "eighteen",
  "nineteen",
  "twenty"
];
const TENS = {
  "20": "twenty",
  "30": "thirty",
  "40": "forty",
  "50": "fifty",
  "60": "sixty",
  "70": "seventy",
  "80": "eighty",
  "90": "ninety"
};

/** A small integer as an English word, so a count can be written out without typing it. */
export function word(n) {
  if (n <= 20) return ONES[n] || String(n);
  const t = Math.floor(n / 10) * 10;
  const r = n % 10;
  if (!TENS[t]) return String(n);
  return r === 0 ? TENS[t] : TENS[t] + "-" + ONES[r];
}

/** Same, capitalised, for the start of a sentence. */
export function Word(n) {
  const w = word(n);
  return w.charAt(0).toUpperCase() + w.slice(1);
}
