name = "mcp-billing"
main = "src/index.js"
compatibility_date = "2025-09-01"
compatibility_flags = ["nodejs_compat"]
account_id = "dd3f2a29b7707e21a87f26a622c0bb9d"
workers_dev = true
routes = [{ pattern = "mcp.zovo.one", custom_domain = true }]

[[kv_namespaces]]
binding = "LICENSES"
id = "75f8bf4872a0433285d11575cece8641"
