// Contract suite for checklist. Mechanical assertions only.
//
// Asserts the invariants of servers/checklist/SPEC.md that a test can check without
// judgement: one version number across package.json, src/version.ts, serverInfo and all
// four registry manifests; the remotes rule (this server is stdio and .mcpb only, so NO
// manifest may advertise a remote); JSON-RPC-only stdout; tool-description hygiene; the
// free/Pro tier switch; that nothing outside this server's own directory is written; and
// the snapshot rule, which is the one property that would be invisible on disk if it broke.
// It never asserts a number a human chose; those live in test/unit.test.mjs.
import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { client, sandbox, cleanup, proKey, storeDir, writeProfile, seed, seedChecklist, REPO } from "./_client.mjs";

const HERE = join(REPO, "servers", "checklist");
const PRODUCT = "checklist";
const MAX_DESCRIPTION = 220;
const HARD_MAX_DESCRIPTION = 1200;
const MANIFESTS = ["server.json", "server.mcpb.json", "server.snag.json", "server.onboarding.json"];

/**
 * Tools that already break the description rules on the day this suite was written.
 * The suite is a ratchet: an existing entry is reported, a NEW one fails. The fix is in
 * src, not here.
 */
const OVER_LENGTH_BASELINE = [];

function open(t, opts = {}) {
  const box = sandbox();
  writeProfile(box.dataHome);
  const c = client({ dataHome: box.dataHome, ...opts });
  t.after(() => { c.close(); cleanup(box.dir); });
  return { box, c };
}

test("the version is one number: package.json, src/version.ts, serverInfo and every manifest agree", async (t) => {
  const pkg = JSON.parse(readFileSync(join(HERE, "package.json"), "utf8"));
  assert.equal(pkg.name, "@theluckystrike/mcp-checklist");
  assert.match(pkg.version, /^\d+\.\d+\.\d+$/, "package version must be a plain semver; the release bump moves it, the test does not pin it");
  assert.ok(pkg.description.length < 100, `package description is ${pkg.description.length} chars`);
  const generated = readFileSync(join(HERE, "src", "version.ts"), "utf8");
  assert.match(generated, /GENERATED by scripts\/sync-versions\.mjs/, "version.ts must be generated, not hand written");
  assert.match(generated, new RegExp(`export const VERSION = "${pkg.version.replace(/\./g, "\\.")}";`),
    `src/version.ts does not carry ${pkg.version}; run node scripts/sync-versions.mjs`);

  const { c } = open(t);
  const info = await c.init();
  assert.equal(info.serverInfo.version, pkg.version, "serverInfo.version must equal the package version");
  assert.equal(info.serverInfo.name, "mcp-checklist");

  for (const file of MANIFESTS) {
    const j = JSON.parse(readFileSync(join(HERE, file), "utf8"));
    assert.equal(j.version, pkg.version, `${file} version`);
    for (const p of j.packages ?? []) {
      assert.equal(p.version, pkg.version, `${file} package entry version`);
      assert.equal(p.transport.type, "stdio", `${file} declares a transport this server does not speak`);
      if (p.registryType === "mcpb") {
        // "TBD" until scripts/manifest-sha256.mjs hashes the built bundle; after that, the
        // real digest. A STALE digest is worse than none: the registry validates it against
        // the asset it downloads and rejects the row, naming the digest rather than the cause.
        assert.ok(p.fileSha256 === "TBD" || /^[0-9a-f]{64}$/.test(p.fileSha256),
          `${file} fileSha256 is neither TBD nor a sha256: ${p.fileSha256}`);
      }
    }
    // stdio and .mcpb only. The registry binds one endpoint URL to exactly one server name,
    // so a remote here would claim a URL that does not answer.
    assert.equal(j.remotes, undefined, `${file} advertises a remote; this server is not hosted`);
    assert.ok((j.description ?? "").length < 100, `${file} description is ${(j.description ?? "").length} chars; the registry 422s at 100`);
    assert.ok(!/[,.]\.$|,$/.test(j.description), `${file} description ends in a machine truncation`);
    assert.ok(!/\u2014/.test(JSON.stringify(j)), `${file} carries an em dash`);
  }
  assert.equal(existsSync(join(HERE, "remotes.json")), false, "remotes.json must not exist: this server is not hosted");

  const names = ["server.json", "server.snag.json", "server.onboarding.json"]
    .map((f) => JSON.parse(readFileSync(join(HERE, f), "utf8")).name);
  assert.equal(new Set(names).size, 3, `registry names must differ: ${names.join(", ")}`);
  assert.deepEqual(names, [
    "io.github.theluckystrike/checklist",
    "io.github.theluckystrike/snag-list-defect-handover-signoff",
    "io.github.theluckystrike/onboarding-checklist-inspection-runs",
  ]);

  execFileSync(process.execPath, [join(REPO, "scripts", "sync-versions.mjs"), "--check"], { encoding: "utf8" });
});

test("every registry name carries a token this server can actually be found on", () => {
  // Registry search matches a substring of the FULL name and nothing else; the description
  // is never searched (docs/NAMING_R5_RESULT.md). So the tokens this server is meant to be
  // findable on have to be IN the names, and this asserts they are rather than assuming it.
  const joined = ["server.json", "server.snag.json", "server.onboarding.json"]
    .map((f) => JSON.parse(readFileSync(join(HERE, f), "utf8")).name.toLowerCase()).join(" ");
  for (const token of ["checklist", "snag", "handover", "onboarding", "inspection", "signoff", "defect"]) {
    assert.ok(joined.includes(token), `no registry name carries the token "${token}"`);
  }
});

test("stdout carries JSON-RPC only across initialize, tools/list, a success and an error", async (t) => {
  const { c } = open(t);
  await c.init();
  await c.tools();
  await c.call("checklist_create", { name: "Anything" });
  await c.call("run_show", { run: "RUN-2099-0001" });
  await new Promise((r) => setTimeout(r, 150));

  const lines = c.stdoutLines.filter((l) => l.trim() !== "");
  assert.ok(lines.length >= 4, `expected at least 4 protocol lines, got ${lines.length}`);
  for (const line of lines) {
    let m;
    try { m = JSON.parse(line); } catch { assert.fail(`non-JSON on stdout: ${JSON.stringify(line.slice(0, 200))}`); }
    assert.equal(m.jsonrpc, "2.0", `stdout line is JSON but not JSON-RPC: ${line.slice(0, 200)}`);
  }
});

test("every tool description is non-empty, single-paragraph, and within the ceiling", async (t) => {
  const { c } = open(t);
  await c.init();
  const tools = await c.tools();
  assert.equal(tools.length, 16, "tool count changed; update servers/checklist/SPEC.md");
  assert.deepEqual(tools.map((x) => x.name).sort(), [
    "checklist_create", "checklist_delete", "checklist_item_add", "checklist_item_remove",
    "checklist_list", "checklist_show", "license_activate", "license_status",
    "run_check", "run_delete", "run_list", "run_report", "run_show", "run_sign_off",
    "run_start", "run_status",
  ]);

  for (const tool of tools) {
    const d = tool.description ?? "";
    assert.ok(d.trim().length > 0, `${tool.name} has no description`);
    assert.equal(d, d.trim(), `${tool.name} description has leading or trailing whitespace`);
    assert.ok(d.length <= HARD_MAX_DESCRIPTION, `${tool.name} description is ${d.length} chars, over ${HARD_MAX_DESCRIPTION}`);
    assert.ok(!/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/u.test(d), `${tool.name} description carries an emoji`);
    assert.ok(!/\u2014/.test(d), `${tool.name} description carries an em dash`);
  }

  const over = tools.filter((x) => (x.description ?? "").length > MAX_DESCRIPTION).map((x) => x.name).sort();
  assert.deepEqual(over.filter((n) => !OVER_LENGTH_BASELINE.includes(n)), [], `new tool descriptions over ${MAX_DESCRIPTION} chars`);
});

test("the one tool that takes a file path names the argument and the tier that may use it", async (t) => {
  const { c } = open(t);
  await c.init();
  const tools = await c.tools();
  const fileTools = tools.filter((x) => Object.keys(x.inputSchema?.properties ?? {}).includes("out_path"));
  assert.deepEqual(fileTools.map((x) => x.name), ["run_report"]);
  assert.match(fileTools[0].description, /out_path/);
  assert.match(fileTools[0].description, /Pro/);
});

test("license_status reports free with no key and pro with a signed key", async (t) => {
  const { c: free } = open(t);
  await free.init();
  const f = await free.call("license_status", {});
  assert.equal(f.isError, false, f.text);
  assert.match(f.text, /"tier":\s*"free"/, f.text.slice(0, 300));

  const key = proKey(PRODUCT);
  assert.match(key, /^MCPL1\./);
  const { c: pro } = open(t, { key });
  await pro.init();
  assert.match((await pro.call("license_status", {})).text, /"tier":\s*"pro"/);
});

test("a licence for another product does not unlock this one", async (t) => {
  const { c } = open(t, { key: proKey("not-a-real-product") });
  await c.init();
  assert.match((await c.call("license_status", {})).text, /"tier":\s*"free"/);
});

test("the free tier is the documented one: everything but writing the report to a file", async (t) => {
  const { c } = open(t);
  await c.init();
  const { checklist, run } = await seed(c);
  for (const [tool, args] of [
    ["checklist_show", { checklist }],
    ["checklist_list", {}],
    ["checklist_item_add", { checklist, text: "Extra step" }],
    ["checklist_item_remove", { checklist, item: "I07" }],
    ["run_show", { run }],
    ["run_list", {}],
    ["run_report", { run }],
    ["run_check", { run, item: "I06", state: "pass", by: "Ben" }],
    ["run_sign_off", { run, by: "Cara", force: true }],
    ["run_start", { checklist, title: "Another van" }],
  ]) {
    const r = await c.call(tool, args);
    assert.equal(r.isError, false, `${tool} was gated: ${r.text}`);
  }
  const gated = await c.call("run_report", { run, out_path: "/tmp/checklist-should-not-be-written.txt" });
  assert.equal(gated.isError, true, "run_report wrote a file on the free tier");
  assert.match(gated.text, /Pro is a one-time \$\d+ for this server/);
  assert.match(gated.text, /license_activate/);
  assert.match(gated.text, new RegExp(`src=${PRODUCT}\\.run_report`), "the gate link is untagged");
  assert.match(gated.text, /any total or journal composed outside them is an estimate/, "the NO_HAND_MATH sentence is missing");
  assert.match(gated.text, new RegExp(`Or all \\d+ servers for \\$\\d+: https://mcp\\.zovo\\.one/buy/bundle\\?src=${PRODUCT}\\.run_report\\.bundle$`), "the bundle sentence is missing");
  assert.equal(existsSync("/tmp/checklist-should-not-be-written.txt"), false, "the gate wrote a file before refusing");
});

test("the free-tier cap message also carries the tagged link and the bundle", async (t) => {
  const { c } = open(t);
  await c.init();
  for (let i = 1; i <= 3; i++) await c.json("checklist_create", { name: `List ${i}` });
  const r = await c.call("checklist_create", { name: "List 4" });
  assert.ok(r.isError, r.text);
  assert.match(r.text, new RegExp(`src=${PRODUCT}\\.checklist_create`));
  assert.match(r.text, /buy\/bundle/);
});

test("the resource and the prompt are registered and answer", async (t) => {
  const { c } = open(t);
  await c.init();
  const res = (await c.send("resources/read", { uri: "checklist://contract" })).result;
  const body = JSON.parse(res.contents[0].text);
  assert.deepEqual(body.item_states, ["pending", "pass", "fail", "na"]);
  assert.deepEqual(body.run_statuses, ["open", "complete", "signed_off", "abandoned"]);
  assert.deepEqual(body.open_run_statuses, ["open", "complete"]);
  assert.deepEqual(body.run_transitions, { open: ["complete", "abandoned"], complete: ["signed_off", "open", "abandoned"], signed_off: [], abandoned: [] });
  assert.match(body.snapshot_rule, /copies its checklist's items when it starts/);
  assert.match(body.na_means, /ANSWERED and never as passed/);
  assert.equal(body.free_tier.checklists, 3);
  assert.equal(body.free_tier.runs, "unlimited on every tier");
  assert.deepEqual(body.free_tier.pro_tools, ["run_report with out_path"]);
  assert.equal(body.opens_sibling_stores, false);
  assert.equal(body.writes.length, 1);
  assert.equal(body.writes[0].store, "checklist");
  const prompts = (await c.send("prompts/list", {})).result.prompts;
  assert.deepEqual(prompts.map((p) => p.name), ["run_the_checklist"]);
});

test("this server writes its own directory and no sibling store, on any tool", async (t) => {
  const { box, c } = open(t, { key: proKey() });
  await c.init();
  const { checklist, run } = await seed(c);
  await c.call("run_report", { run });
  await c.call("checklist_show", { checklist, as_text: true });
  await c.call("run_list", {});
  await c.call("run_sign_off", { run, by: "Cara", force: true });
  const gone = await c.json("checklist_create", { name: "Gone" });
  await c.call("checklist_delete", { checklist: gone.created.id, confirm: true });

  const files = readdirSync(storeDir(box.dataHome)).filter((f) => !f.startsWith("."));
  assert.deepEqual(files.sort(), ["counter.json", "runs.json", "templates.json"]);
  const siblings = readdirSync(join(box.dataHome, "mcp-servers")).sort();
  assert.deepEqual(siblings, ["checklist", "profile"], `a sibling store was created: ${siblings.join(", ")}`);
  assert.deepEqual(readdirSync(join(box.dataHome, "mcp-servers", "profile")), ["business.json"],
    "this server wrote into the shared profile directory; it must only read business.json");
});

test("the snapshot rule is on disk: a run stores its own items, not a pointer to the checklist", async (t) => {
  const { box, c } = open(t);
  await c.init();
  const { checklist } = await seed(c);
  await c.json("checklist_item_add", { checklist, text: "A step added after the run started", required: true });
  const runs = JSON.parse(readFileSync(join(storeDir(box.dataHome), "runs.json"), "utf8"));
  const r = runs[0];
  assert.equal(r.items.length, 6, "the run's items are not its own copy");
  assert.equal(r.items.some((i) => /added after the run started/.test(i.text)), false);
  assert.equal(r.template_version, 7, "the run did not record the checklist version it copied");
  assert.deepEqual(Object.keys(r).sort(), [
    "created", "date", "history", "id", "items", "reference", "status",
    "template", "template_name", "template_version", "title", "updated",
  ]);
  assert.deepEqual(Object.keys(r.items[0]).sort(), ["at", "by", "id", "required", "section", "state", "text"]);
  // And no progress figure is stored: every count is derived on the call.
  const raw = readFileSync(join(storeDir(box.dataHome), "runs.json"), "utf8");
  for (const key of ["progress", "percent_answered", "pass_count", "answered", "ready_to_sign_off", "complete"]) {
    assert.equal(raw.includes(`"${key}"`), false, `${key} was stored; every count must be derived on the call`);
  }
});

test("there is no money anywhere in this server: a checklist has no amounts", async () => {
  for (const f of ["index.ts", "checklist.ts", "store.ts", "lib.ts"]) {
    const s = readFileSync(join(HERE, "src", f), "utf8");
    assert.equal(/^import .*mcp-invoice/m.test(s), false, `src/${f} imports the money engine`);
    const code = s.split("\n").filter((l) => !/^\s*(\*|\/\/|\/\*)/.test(l)).join("\n");
    assert.equal(/formatMoney|computeTotals|roundHalfUp|currencyDecimals/.test(code), false, `src/${f} carries money arithmetic`);
    assert.equal(/[\u20ac\u00a3\u00a5]/.test(s), false, `src/${f} carries a currency symbol`);
  }
  const pkg = JSON.parse(readFileSync(join(HERE, "package.json"), "utf8"));
  assert.equal(pkg.dependencies["@theluckystrike/mcp-invoice"], undefined, "the invoice engine must not be a dependency");
});

test("src holds no network call and no stdout write", async () => {
  let raw = "";
  try {
    raw = execFileSync("/usr/bin/grep", ["-rEn", "fetch\\(|https?://|node:http|node:net|node:dns|console\\.", join(HERE, "src")], { encoding: "utf8" });
  } catch (e) {
    if (e.status !== 1) throw e;
  }
  const offending = raw.trim().split("\n").filter(Boolean)
    .filter((l) => !/mcp\.zovo\.one|github\.com|modelcontextprotocol\.io|checklist:\/\//.test(l));
  assert.deepEqual(offending, [], `network or stdout in src:\n${offending.join("\n")}`);
});

test("src, tests and docs carry no em dash and no emoji", () => {
  const files = [
    ...readdirSync(join(HERE, "src")).map((f) => join(HERE, "src", f)),
    ...readdirSync(join(HERE, "test")).map((f) => join(HERE, "test", f)),
    join(HERE, "README.md"), join(HERE, "llms-install.md"), join(HERE, "RESULT.md"), join(HERE, "SPEC.md"),
  ].filter(existsSync);
  for (const f of files) {
    const s = readFileSync(f, "utf8");
    assert.equal(s.includes("\u2014"), false, `${f} carries an em dash`);
    assert.equal(/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/u.test(s), false, `${f} carries an emoji`);
  }
});

test("the required files are all present", () => {
  for (const f of [
    "package.json", "tsconfig.json", "README.md", "LICENSE", "SPEC.md", "RESULT.md",
    "server.json", "server.mcpb.json", "server.snag.json", "server.onboarding.json",
    "smithery.yaml", "glama.json", "llms-install.md", "Dockerfile",
    "src/index.ts", "src/lib.ts", "src/checklist.ts", "src/store.ts", "src/version.ts",
  ]) {
    assert.ok(existsSync(join(HERE, f)), `missing ${f}`);
  }
});

test("every count the server emits is a whole number and the parts sum to the whole", async (t) => {
  const { c } = open(t);
  await c.init();
  const { run } = await seed(c);
  const p = (await c.json("run_show", { run })).progress;
  for (const k of ["items", "pending", "pass", "fail", "na", "required", "required_pending", "required_fail", "answered"]) {
    assert.ok(Number.isInteger(p[k]), `${k} is not an integer: ${p[k]}`);
  }
  assert.equal(p.pass + p.fail + p.na + p.pending, p.items, "the states do not sum to the item count");
  assert.equal(p.answered + p.pending, p.items, "answered plus pending is not the item count");
  assert.equal(p.outstanding.length, p.pending);
  assert.equal(p.failures.length, p.fail);
  assert.ok(p.percent_answered >= 0 && p.percent_answered <= 100);
});

test("a checklist with no steps cannot start a run", async (t) => {
  const { c } = open(t);
  await c.init();
  const t0 = await c.json("checklist_create", { name: "Empty" });
  const r = await c.call("run_start", { checklist: t0.created.id, title: "Nothing" });
  assert.ok(r.isError, r.text);
  assert.match(r.text, /has no steps yet/);
});

test("the estate lists this server everywhere a new server has to be registered", () => {
  // The one-line registrations outside this folder. release-check.mjs is the full reader;
  // these are the ones a server cannot ship without, checked here so the omission fails in
  // this suite rather than at bundle time. Copied from the delivery-schedule suite, which is
  // where this pattern was established.
  const cases = [
    ["scripts/build-mcpb.sh", /^SERVERS="[^"]*\bchecklist\b/m, "SERVERS list"],
    ["scripts/build-mcpb.sh", /^\s*\[checklist\]="/m, "DISPLAY_NAME"],
    ["scripts/build-mcpb.sh", /^\s*\[checklist\]='\[/m, "KEYWORDS"],
    ["scripts/build-pages.mjs", /const ids = \[[^\]]*"checklist"/, "page ids"],
    ["scripts/gen-spec.mjs", /"checklist"/, "SPEC generator"],
    ["scripts/validate.mjs", /^  "?checklist"?: async \(c, tmp, tier, ok\) =>/m, "live validation probe"],
    ["servers/office-suite/src/index.ts", /id: "checklist"/, "office-suite CHILDREN"],
    ["servers/invoice/src/index.ts", /"checklist"/, "PROFILE_READERS"],
    ["data/facts.json", /"checklist":/, "facts tagline, which the README table is generated from"],
    ["data/distribution.json", /"checklist":/, "distribution per_server"],
    ["README.md", /\[mcp-checklist\]/, "README server table"],
    ["data/tools.json", /"checklist":/, "tools.json, which the storefront tool tables read"],
    ["scripts/sync-mirrors.sh", /^ALL_SERVERS="[^"]*\bchecklist\b/m, "ALL_SERVERS"],
    ["scripts/mirror-seo.py", /^\s*"checklist":/m, "mirror-seo CAPABILITY and topics"],
  ];
  for (const [file, re, what] of cases) {
    const src = readFileSync(join(REPO, file), "utf8");
    assert.ok(re.test(src), `${file} does not list checklist in its ${what}`);
  }
});

test("this server is NOT registered on any hosted surface, because it has none", () => {
  // The inverse registration, and it matters as much as the positive one. The registry binds
  // one hosted endpoint URL to exactly one server name, so a /mcp/checklist row anywhere would
  // claim a URL that has never answered and would burn the name for the day it is hosted.
  // scripts/validate.mjs drives the LIVE endpoints in its remote() section; a name added
  // there fails forever rather than once.
  const validate = readFileSync(join(REPO, "scripts", "validate.mjs"), "utf8");
  const remoteBlock = validate.slice(validate.indexOf("async function remote()"));
  assert.equal(remoteBlock.includes('"checklist"'), false, "scripts/validate.mjs remote() probes checklist over HTTP, but it has no hosted endpoint");
  const dist = JSON.parse(readFileSync(join(REPO, "data", "distribution.json"), "utf8"));
  assert.match(dist.per_server["checklist"].hosted, /^none by design/, "distribution.json claims a hosted endpoint for checklist");
});
