// Contract suite for billing-docs. Generated shape, mechanical assertions only.
//
// Asserts the invariants of servers/billing-docs/SPEC.md that a test can check without
// judgement: one version number across package.json, src/version.ts, serverInfo and both
// registry manifests; JSON-RPC-only stdout; tool-description hygiene; corrupt-store
// quarantine; and the free/Pro tier switch. It never asserts a number a human chose;
// those live in the server's own suites.
import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { client, sandbox, cleanup, proKey, docsDir, REPO } from "./_client.mjs";

const HERE = join(REPO, "servers", "billing-docs");
const PRODUCT = "billing-docs";
const MAX_DESCRIPTION = 220;
const HARD_MAX_DESCRIPTION = 1200;
const FILE_ARGS = ["path", "url", "out_path", "template_path"];
const IMPERATIVE = /^(Call this tool|Use this)\b/;

/**
 * Tools that already break the two description rules on the day this suite was written.
 * The suite is a ratchet: an existing entry is reported, a NEW one fails. Both lists are
 * defects; the fix is in src, not here.
 */
const OVER_LENGTH_BASELINE = [];
const NON_IMPERATIVE_BASELINE = [];

const GARBAGE = '{"version":1, <<< truncated by a crash';

function open(t, opts = {}) {
  const box = sandbox();
  const c = client({ dataHome: box.dataHome, ...opts });
  t.after(() => { c.close(); cleanup(box.dir); });
  return { box, c };
}

test("the version is one number: package.json, src/version.ts and serverInfo agree", async (t) => {
  const pkg = JSON.parse(readFileSync(join(HERE, "package.json"), "utf8"));
  const generated = readFileSync(join(HERE, "src", "version.ts"), "utf8");
  assert.match(generated, /GENERATED by scripts\/sync-versions\.mjs/, "version.ts must be generated, not hand written");
  assert.match(generated, new RegExp(`export const VERSION = "${pkg.version.replace(/\./g, "\\.")}";`),
    `src/version.ts does not carry ${pkg.version}; run node scripts/sync-versions.mjs`);

  const { c } = open(t);
  const info = await c.init();
  assert.equal(info.serverInfo.version, pkg.version, "serverInfo.version must equal the package version");
  assert.equal(info.serverInfo.name, "mcp-billing-docs");

  for (const file of ["server.json", "server.mcpb.json", "server.variant.json", "server.purchase-order.json"]) {
    const j = JSON.parse(readFileSync(join(HERE, file), "utf8"));
    assert.equal(j.version, pkg.version, `${file} version`);
    for (const p of j.packages ?? []) assert.equal(p.version, pkg.version, `${file} package entry version`);
    assert.ok((j.description ?? "").length < 100, `${file} description is ${j.description.length} chars; the registry 422s at 100`);
    assert.ok(!/[,.]\.$|,$/.test(j.description), `${file} description ends in a machine truncation`);
  }
  // Two distinct registry names, so the second one is a second listing and not a copy.
  const names = ["server.json", "server.variant.json", "server.purchase-order.json"]
    .map((f) => JSON.parse(readFileSync(join(HERE, f), "utf8")).name);
  assert.equal(new Set(names).size, 3, `registry names must differ: ${names.join(", ")}`);

  // And sync-versions --check passes for the whole repo, so no sibling drifted either.
  execFileSync(process.execPath, [join(REPO, "scripts", "sync-versions.mjs"), "--check"], { encoding: "utf8" });
});

test("stdout carries JSON-RPC only across initialize, tools/list and one call", async (t) => {
  const { c } = open(t);
  await c.init();
  await c.tools();
  await c.call("credit_note_list", {});
  await new Promise((r) => setTimeout(r, 150));

  const lines = [...c.stdoutLines, c.tail].filter((l) => l.trim() !== "");
  assert.ok(lines.length >= 3, `expected at least 3 protocol lines, got ${lines.length}`);
  for (const line of lines) {
    let m;
    try { m = JSON.parse(line); } catch { assert.fail(`non-JSON on stdout: ${JSON.stringify(line.slice(0, 200))}`); }
    assert.equal(m.jsonrpc, "2.0", `stdout line is JSON but not JSON-RPC: ${line.slice(0, 200)}`);
  }
});

test("every tool description is non-empty, single-paragraph, and within the hard ceiling", async (t) => {
  const { c } = open(t);
  await c.init();
  const tools = await c.tools();
  assert.equal(tools.length, 14, "tool count changed; update servers/billing-docs/SPEC.md");

  for (const tool of tools) {
    const d = tool.description ?? "";
    assert.ok(d.trim().length > 0, `${tool.name} has no description`);
    assert.equal(d, d.trim(), `${tool.name} description has leading or trailing whitespace`);
    assert.ok(d.length <= HARD_MAX_DESCRIPTION, `${tool.name} description is ${d.length} chars, over ${HARD_MAX_DESCRIPTION}`);
    assert.ok(!/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/u.test(d), `${tool.name} description carries an emoji`);
  }

  const over = tools.filter((x) => (x.description ?? "").length > MAX_DESCRIPTION).map((x) => x.name).sort();
  const regressions = over.filter((n) => !OVER_LENGTH_BASELINE.includes(n));
  assert.deepEqual(regressions, [], `new tool descriptions over ${MAX_DESCRIPTION} chars`);
  const fixed = OVER_LENGTH_BASELINE.filter((n) => !over.includes(n));
  if (fixed.length) t.diagnostic(`now within ${MAX_DESCRIPTION} chars, drop from the baseline: ${fixed.join(", ")}`);
});

test("a tool that takes a file path or a URL opens with an imperative sentence", async (t) => {
  const { c } = open(t);
  await c.init();
  const tools = await c.tools();
  const fileTools = tools.filter((x) => Object.keys(x.inputSchema?.properties ?? {}).some((k) => FILE_ARGS.includes(k)));
  assert.ok(fileTools.length >= 2, "both PDF tools take out_path");
  const offenders = fileTools.filter((x) => !IMPERATIVE.test(x.description ?? "")).map((x) => x.name).sort();
  const regressions = offenders.filter((n) => !NON_IMPERATIVE_BASELINE.includes(n));
  assert.deepEqual(regressions, [], "new file/URL tools whose description does not start with \"Call this tool\" or \"Use this\"");
});

test("corrupt store: the garbage is quarantined byte-for-byte and nothing is overwritten", async (t) => {
  const { box, c } = open(t);
  const dir = docsDir(box.dataHome);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, "purchase-orders.json"), GARBAGE);

  await c.init();
  const r = await c.call("purchase_order_create", { supplier: "Widget Co", items: [{ description: "Cables", quantity: 1, unit_price_minor: 1000 }] });
  assert.equal(r.isError, true, `a corrupt store must refuse, not succeed: ${r.text.slice(0, 300)}`);
  assert.match(r.text, /corrupt|not valid JSON/i, r.text.slice(0, 300));

  const moved = readdirSync(dir).filter((f) => f.startsWith("purchase-orders.json.corrupt-"));
  assert.equal(moved.length, 1, `expected one quarantined copy, found ${JSON.stringify(readdirSync(dir))}`);
  assert.equal(readFileSync(join(dir, moved[0]), "utf8"), GARBAGE, "the quarantined copy must be the original bytes");
  assert.equal(readdirSync(dir).includes("purchase-orders.json"), false, "an empty store must not be written over the corrupt one");
});

test("cap: the free document cap refuses without writing a partial document", async (t) => {
  const { box, c } = open(t);
  await c.init();
  for (let i = 0; i < 5; i++) {
    const r = await c.call("purchase_order_create", { supplier: `S${i}`, issue_date: "2026-09-02", items: [{ description: "X", quantity: 1, unit_price_minor: 100 }] });
    assert.equal(r.isError, false, r.text);
  }
  const over = await c.call("purchase_order_create", { supplier: "S5", issue_date: "2026-09-02", items: [{ description: "X", quantity: 1, unit_price_minor: 100 }] });
  assert.equal(over.isError, true, over.text);
  assert.match(over.text, /Nothing was stored/);
  const stored = JSON.parse(readFileSync(join(docsDir(box.dataHome), "purchase-orders.json"), "utf8"));
  assert.equal(stored.length, 5, "the refused document left no row");
  // Conversion instrument (docs/CONVERSION_INSTRUMENT.md): the /buy link on a cap
  // message names the tool that produced it, not the prose of the feature.
  assert.ok(over.text.includes("https://mcp.zovo.one/buy/billing-docs?src=billing-docs.purchase_order_create"), over.text.slice(0, 400));
});

test("license_status reports free with no key and pro with a signed key", async (t) => {
  const { c: free } = open(t);
  await free.init();
  const f = await free.call("license_status", {});
  assert.equal(f.isError, false, f.text);
  assert.match(f.text, /"tier":\s*"free"/, f.text.slice(0, 300));

  const key = proKey(PRODUCT);
  assert.match(key, /^MCPL1\./);
  const { c: pro } = open(t, { key });
  await pro.init();
  assert.match((await pro.call("license_status", {})).text, /"tier":\s*"pro"/);

  const { c: other } = open(t, { key: proKey("not-a-real-product") });
  await other.init();
  assert.match((await other.call("license_status", {})).text, /"tier":\s*"free"/);
});
