// Contract suite for image. Mechanical assertions only: the invariants of
// servers/image/SPEC.md that a test can check without judgement.
//
// It uses its own stdio client rather than test/_client.mjs, because that one throws on
// the first non-JSON stdout line; this suite has to SEE such a line to assert it is not
// there. The fixture builders are shared.
import { test } from "node:test";
import assert from "node:assert/strict";
import { spawn, execFileSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { REPO, makePng } from "./_client.mjs";

const PRODUCT = "image";
const ENTRY = join(REPO, "servers", PRODUCT, "dist", "index.js");

const MAX_DESCRIPTION = 220;
const HARD_MAX_DESCRIPTION = 1200;
const FILE_ARGS = ["path", "url", "out_path", "out_dir", "template_path"];
const IMPERATIVE = /^(Call this tool|Use this)\b/;

/**
 * Tools that already break the two description rules on the day this suite was written.
 * The suite is a ratchet: an existing entry is reported, a NEW one fails. The fix is in
 * src, never here.
 */
const OVER_LENGTH_BASELINE = [];
const NON_IMPERATIVE_BASELINE = [];

const GARBAGE = '[{"op":"resize", <<< truncated by a crash';

function box() {
  const dir = mkdtempSync(join(tmpdir(), `mcp-contract-${PRODUCT}-`));
  return { dir, dataHome: join(dir, "data") };
}

function client({ dataHome, key } = {}) {
  const env = { ...process.env, XDG_DATA_HOME: dataHome, XDG_CONFIG_HOME: join(dataHome, "..", "config"), MCP_LICENSE_KEY: key ?? "" };
  const child = spawn(process.execPath, [ENTRY], { stdio: ["pipe", "pipe", "pipe"], env });
  child.stderr.resume();
  const stdoutLines = [];
  let buf = "";
  const pending = new Map();
  child.stdout.on("data", (d) => {
    buf += d.toString();
    let i;
    while ((i = buf.indexOf("\n")) >= 0) {
      const line = buf.slice(0, i);
      buf = buf.slice(i + 1);
      stdoutLines.push(line);
      if (!line.trim()) continue;
      let m;
      try { m = JSON.parse(line); } catch { continue; }
      const r = pending.get(m.id);
      if (r) { pending.delete(m.id); r(m); }
    }
  });
  let id = 0;
  const send = (method, params) => new Promise((res, rej) => {
    const mid = ++id;
    pending.set(mid, res);
    child.stdin.write(JSON.stringify({ jsonrpc: "2.0", id: mid, method, params }) + "\n");
    const t = setTimeout(() => { if (pending.has(mid)) { pending.delete(mid); rej(new Error(`timeout on ${method}`)); } }, 60000);
    t.unref();
  });
  return {
    send, stdoutLines,
    get tail() { return buf; },
    async init() {
      const r = await send("initialize", { protocolVersion: "2024-11-05", capabilities: {}, clientInfo: { name: "contract", version: "0" } });
      child.stdin.write(JSON.stringify({ jsonrpc: "2.0", method: "notifications/initialized", params: {} }) + "\n");
      return r.result;
    },
    async tools() { return (await send("tools/list", {})).result.tools; },
    async call(name, args) {
      const r = await send("tools/call", { name, arguments: args ?? {} });
      if (!r.result) return { text: JSON.stringify(r.error), isError: true };
      return { text: r.result.content.map((c) => c.text).join("\n"), isError: r.result.isError === true };
    },
    close() { child.kill(); },
  };
}

const clean = (dir) => { try { rmSync(dir, { recursive: true, force: true }); } catch { /* best effort */ } };
const proKey = (product) => execFileSync(process.execPath, [join(REPO, "scripts", "sign-license.mjs"), product], { encoding: "utf8" }).trim();

test("the version is one number: package.json, src/version.ts and serverInfo agree", async (t) => {
  const here = join(REPO, "servers", PRODUCT);
  const pkg = JSON.parse(readFileSync(join(here, "package.json"), "utf8"));
  const generated = readFileSync(join(here, "src", "version.ts"), "utf8");
  assert.match(generated, /GENERATED by scripts\/sync-versions\.mjs/, "version.ts must be generated, not hand written");
  assert.match(generated, new RegExp(`export const VERSION = "${pkg.version.replace(/\./g, "\\.")}";`),
    `src/version.ts does not carry ${pkg.version}; run node scripts/sync-versions.mjs`);

  const b = box();
  const c = client({ dataHome: b.dataHome });
  t.after(() => { c.close(); clean(b.dir); });
  const info = await c.init();
  assert.equal(info.serverInfo.version, pkg.version, "serverInfo.version must equal the package version");
  assert.equal(info.serverInfo.name, `mcp-${PRODUCT}`);

  for (const file of ["server.json", "server.mcpb.json"]) {
    const j = JSON.parse(readFileSync(join(here, file), "utf8"));
    assert.equal(j.version, pkg.version, `${file} version`);
    for (const p of j.packages ?? []) assert.equal(p.version, pkg.version, `${file} package entry version`);
  }
  execFileSync(process.execPath, [join(REPO, "scripts", "sync-versions.mjs"), "--check"], { encoding: "utf8" });
});

test("stdout carries JSON-RPC only, including through a decoder that warns", async (t) => {
  const b = box();
  const c = client({ dataHome: b.dataHome });
  t.after(() => { c.close(); clean(b.dir); });
  await c.init();
  await c.tools();

  // D-I1: omggif and jpeg-js print their warnings with console.log, which is the
  // transport. A truncated GIF is the input that produced them.
  const png = await makePng(join(b.dir, "small.png"), 24, 16);
  await c.call("image_info", { path: png });
  const gif = join(b.dir, "broken.gif");
  writeFileSync(gif, Buffer.concat([Buffer.from("GIF89a", "latin1"), Buffer.alloc(40, 0x21)]));
  await c.call("image_info", { path: gif });
  await c.call("image_info", { path: png });
  await new Promise((r) => setTimeout(r, 150));

  const lines = [...c.stdoutLines, c.tail].filter((l) => l.trim() !== "");
  assert.ok(lines.length >= 3, `expected at least 3 protocol lines, got ${lines.length}`);
  for (const line of lines) {
    let m;
    try { m = JSON.parse(line); } catch { assert.fail(`non-JSON on stdout: ${JSON.stringify(line.slice(0, 200))}`); }
    assert.equal(m.jsonrpc, "2.0", `stdout line is JSON but not JSON-RPC: ${line.slice(0, 200)}`);
  }
});

test("every tool description is non-empty, single-paragraph, and within the hard ceiling", async (t) => {
  const b = box();
  const c = client({ dataHome: b.dataHome });
  t.after(() => { c.close(); clean(b.dir); });
  await c.init();
  const tools = await c.tools();
  assert.equal(tools.length, 12, `tool count changed; update servers/${PRODUCT}/SPEC.md`);

  for (const tool of tools) {
    const d = tool.description ?? "";
    assert.ok(d.trim().length > 0, `${tool.name} has no description`);
    assert.equal(d, d.trim(), `${tool.name} description has leading or trailing whitespace`);
    assert.ok(d.length <= HARD_MAX_DESCRIPTION, `${tool.name} description is ${d.length} chars, over the hard ceiling ${HARD_MAX_DESCRIPTION}`);
    assert.ok(!/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/u.test(d), `${tool.name} description carries an emoji`);
  }

  const over = tools.filter((x) => (x.description ?? "").length > MAX_DESCRIPTION).map((x) => x.name).sort();
  const regressions = over.filter((n) => !OVER_LENGTH_BASELINE.includes(n));
  assert.deepEqual(regressions, [], `new tool descriptions over ${MAX_DESCRIPTION} chars`);
  assert.equal(over.length, 0, `${over.length} tool descriptions over ${MAX_DESCRIPTION} chars: ${over.join(", ")}`);
  const fixed = OVER_LENGTH_BASELINE.filter((n) => !over.includes(n));
  if (fixed.length) t.diagnostic(`now within ${MAX_DESCRIPTION} chars, drop from the baseline: ${fixed.join(", ")}`);
});

test("a tool that takes a file path or a URL opens with an imperative sentence", async (t) => {
  const b = box();
  const c = client({ dataHome: b.dataHome });
  t.after(() => { c.close(); clean(b.dir); });
  await c.init();
  const tools = await c.tools();

  const fileTools = tools.filter((x) => Object.keys(x.inputSchema?.properties ?? {}).some((k) => FILE_ARGS.includes(k)));
  assert.ok(fileTools.length > 0, "expected at least one file/URL tool");
  const offenders = fileTools.filter((x) => !IMPERATIVE.test(x.description ?? "")).map((x) => x.name).sort();
  const regressions = offenders.filter((n) => !NON_IMPERATIVE_BASELINE.includes(n));
  assert.deepEqual(regressions, [], 'new file/URL tools whose description does not start with "Call this tool" or "Use this"');
  assert.equal(offenders.length, 0, `${offenders.length} file/URL tool descriptions do not open with an imperative: ${offenders.join(", ")}`);
  const fixed = NON_IMPERATIVE_BASELINE.filter((n) => !offenders.includes(n));
  if (fixed.length) t.diagnostic(`now imperative, drop from the baseline: ${fixed.join(", ")}`);
});

test("corrupt register: quarantined byte-for-byte, and the image work still succeeds", async (t) => {
  const b = box();
  const dir = join(b.dataHome, "mcp-servers", PRODUCT);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, "operations.json"), GARBAGE);

  const c = client({ dataHome: b.dataHome });
  t.after(() => { c.close(); clean(b.dir); });
  await c.init();

  const src = await makePng(join(b.dir, "in.png"), 40, 30);
  const out = join(b.dir, "out.png");
  const r = await c.call("image_resize", { path: src, width: 20, out_path: out });

  // The register is best effort: the file is on disk before it is touched, so a corrupt
  // register is a note on a successful answer, never "nothing was written".
  assert.equal(r.isError, false, r.text.slice(0, 400));
  assert.equal(existsSync(out), true, "the resized file must exist");
  assert.match(r.text, /operation history|corrupt/i, r.text.slice(0, 400));

  const moved = readdirSync(dir).filter((f) => f.startsWith("operations.json.corrupt-"));
  assert.equal(moved.length, 1, `expected one quarantined copy, found ${JSON.stringify(readdirSync(dir))}`);
  assert.equal(readFileSync(join(dir, moved[0]), "utf8"), GARBAGE, "the quarantined copy must be the original bytes");
  assert.equal(readdirSync(dir).includes("operations.json"), false, "an empty register must not be written over the corrupt one");
  assert.ok(readdirSync(dir).includes("operations.json.corrupt"), "the marker must exist");
});

test("cap: an output over the free megapixel limit writes no file at all", async (t) => {
  const b = box();
  const c = client({ dataHome: b.dataHome });
  t.after(() => { c.close(); clean(b.dir); });
  await c.init();

  const src = await makePng(join(b.dir, "src.png"), 60, 40);
  const out = join(b.dir, "huge.png");
  const r = await c.call("image_resize", { path: src, width: 3000, height: 3000, fit: "exact", out_path: out });

  // A tier limit is an answer, not a protocol error.
  assert.equal(r.isError, false, r.text.slice(0, 300));
  assert.match(r.text, /free/i, r.text.slice(0, 300));
  assert.equal(existsSync(out), false, "a refused resize must leave no file behind");
  assert.equal(readdirSync(b.dir).filter((f) => f.includes(".tmp")).length, 0, "no tmp file may survive a refusal");
});

test("license_status reports free with no key and pro with a signed key", async (t) => {
  const a = box();
  const free = client({ dataHome: a.dataHome });
  t.after(() => { free.close(); clean(a.dir); });
  await free.init();
  const f = await free.call("license_status", {});
  assert.equal(f.isError, false, f.text);
  assert.match(f.text, /"tier":\s*"free"/, f.text.slice(0, 300));

  const key = proKey(PRODUCT);
  assert.match(key, /^MCPL1\./);
  const bb = box();
  const pro = client({ dataHome: bb.dataHome, key });
  t.after(() => { pro.close(); clean(bb.dir); });
  await pro.init();
  const p = await pro.call("license_status", {});
  assert.equal(p.isError, false, p.text);
  assert.match(p.text, /"tier":\s*"pro"/, p.text.slice(0, 300));

  // A key signed for another product must not unlock this one.
  const d = box();
  const other = client({ dataHome: d.dataHome, key: proKey("not-a-real-product") });
  t.after(() => { other.close(); clean(d.dir); });
  await other.init();
  const o = await other.call("license_status", {});
  assert.match(o.text, /"tier":\s*"free"/, o.text.slice(0, 300));
});
