// The honesty gate for round 4 content, and for the counts on the home page.
//
// Two defects motivated this file.
//
// 1. The home page stated the size of its own catalogue three different ways in one
//    document: "Thirty-one" in the h1, title and JSON-LD, "32 servers" in the validation
//    line, and "The 31 servers" over a table, while `ls servers/ | wc -l` returned 32. It is
//    the most retrieved page in the estate and nothing caught it, because no gate had ever
//    looked at a rendered page for a number.
// 2. billing/test/guide-figures.test.mjs holds one guide to one round file. The nine pages
//    added in round 4 quote rate limits, tool counts, prices and third-party findings, so
//    the same discipline is applied to all of them here: every figure has to be findable in
//    a file in this repository.
//
// billing/src/figures.js is generated by scripts/build-figures.mjs out of
// servers/*/src/index.ts, packages/mcp-license, remote/src/index.ts, servers/*/server.json
// and data/facts.json. The first test re-runs that generator in check mode, so a figure
// cannot be right in the page and stale against the source.

import test from "node:test";
import assert from "node:assert";
import { readFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import worker, { SINGLE_PRODUCT_IDS, VALIDATION } from "../src/index.js";
import { GUIDES } from "../src/content.js";
import {
  LISTED_COUNT, LISTED_CHILD_COUNT, HOSTED_COUNT, SERVER_DIR_COUNT, VERSION,
} from "../src/figures.js";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const read = (p) => readFileSync(join(ROOT, p), "utf8");

/** The nine pages written in round 4. Every figure on each has to resolve to a repo file. */
const R4_SLUGS = [
  "which-mcp-servers-work-by-pasting-a-url",
  "paid-mcp-servers-and-how-you-pay-for-one",
  "fill-a-quote-or-estimate-template-from-chat",
  "petty-cash-book-and-cash-ledger-mcp-servers",
  "currency-conversion-mcp-servers-compared",
  "zip-and-unzip-mcp-servers-compared",
  "delivery-schedule-and-work-order-documents-from-mcp",
  "will-an-mcp-server-email-the-invoice-to-my-client",
  "can-an-mcp-server-read-a-photo-of-a-receipt",
];

test("billing/src/figures.js is what the manifests currently say", () => {
  const out = execFileSync("node", [join(ROOT, "scripts/build-figures.mjs"), "--check"], { encoding: "utf8" });
  assert.match(out, /figures OK/);
});

test("the catalogue counts agree with each other", () => {
  assert.equal(SINGLE_PRODUCT_IDS.length, LISTED_CHILD_COUNT,
    `PRODUCTS sells ${SINGLE_PRODUCT_IDS.length} servers singly and ${LISTED_CHILD_COUNT} listed servers are not office-suite. One of them is wrong.`);
  assert.ok(HOSTED_COUNT <= LISTED_COUNT, "more hosted endpoints than listed servers");
  assert.ok(SERVER_DIR_COUNT >= LISTED_COUNT,
    "a listed server has no source directory, which cannot happen");
  assert.equal(VALIDATION.servers, LISTED_COUNT,
    `the home page claims ${VALIDATION.pass} of ${VALIDATION.total} checks across ${VALIDATION.servers} servers while the site lists ${LISTED_COUNT}. Re-run validation, then update VALIDATION in billing/src/index.js.`);
});

test("no count of servers on the home page is typed, spelled out, or wrong", async () => {
  const res = await worker.fetch(new Request("https://mcp.zovo.one/"), {}, { waitUntil() {} });
  const html = await res.text();

  // A machine reader gets nothing from "Thirty-one" that it does not get from 31, and a
  // spelled-out count is how the old defect hid: it did not look like the numerals it
  // contradicted. No English number word may sit in front of "servers" on this page.
  const spelled = [...html.matchAll(/\b(Twenty|Thirty|Forty|Fifty)(?:-[a-z]+)?\s+(?:local-first\s+)?(?:MCP\s+)?servers/g)].map((m) => m[0]);
  assert.deepEqual(spelled, [], `the home page spells out a server count: ${spelled.join(", ")}`);

  // Every numeral immediately in front of "servers" has to be a count this repository can
  // derive. 32 is what the site lists, 31 is what office-suite spawns and what is sold
  // singly, 30 is what answers at a URL.
  const allowed = new Set([LISTED_COUNT, LISTED_CHILD_COUNT, HOSTED_COUNT]);
  const found = [...html.matchAll(/\b(\d+)\s+(?:local-first\s+)?(?:MCP\s+)?servers/g)].map((m) => Number(m[1]));
  assert.ok(found.length > 0, "the home page states no server count at all, which means this gate is not looking at the page");
  const wrong = found.filter((n) => !allowed.has(n));
  assert.deepEqual(wrong, [], `the home page states a server count nothing in the repo derives: ${wrong.join(", ")}. Derived counts are ${[...allowed].join(", ")}.`);
});

test("the home page names servers and gives a URL rather than deferring", async () => {
  const res = await worker.fetch(new Request("https://mcp.zovo.one/"), {}, { waitUntil() {} });
  const html = await res.text();
  // The blind recommendation run retrieved this page twice and cited it neither time,
  // describing it as a generic listing page. A page an assistant can answer from has to
  // carry the name, the one-line description and the exact URL in the HTML, not behind a
  // link. One paste-in URL per hosted server, and none of them the bare form that returns
  // 401 on tools/call.
  const pasteUrls = html.match(/https:\/\/mcp\.zovo\.one\/mcp\/[a-z-]+\/t\/&lt;token&gt;/g) || [];
  assert.equal(pasteUrls.length, HOSTED_COUNT,
    `the home page prints ${pasteUrls.length} paste-in URLs for ${HOSTED_COUNT} hosted servers`);
  assert.match(html, /curl -X POST https:\/\/mcp\.zovo\.one\/mcp\/token/,
    "the home page does not say how to get the token its URLs need");
});

// ---------------------------------------------------------------------------
// Round 4 pages: every figure resolves to a file in this repository.
// ---------------------------------------------------------------------------

/**
 * Files a round 4 figure may come from. figures.js carries the derived counts, limits and
 * prices; facts.json carries the per-server free tiers it is built from; the two docs carry
 * the third-party measurements the pages attribute rather than assert.
 */
const SOURCES = [
  "billing/src/figures.js",
  "data/facts.json",
  "docs/BLIND_RECOMMENDATION_R1.md",
  "docs/CONTENT_R3.md",
];

const haystack = SOURCES.map(read).join("\n").replace(/,(?=\d)/g, "");

/**
 * Figures that are correct but that the boundary-anchored match below cannot see, each with
 * the reason. Keep this list short and keep the reason on the line.
 */
const EXPLAINED = new Map([
  // VERSION is "0.21.0" in figures.js. Splitting a three-part version yields "0.21", which
  // the (?!\.\d) lookahead then refuses against its own source.
  ["0.21", `VERSION is ${VERSION} in billing/src/figures.js`],
]);

function figures(text) {
  // <pre> blocks are code, and HUMANIZE.md exempts code. They also carry hex tokens whose
  // digits are not figures about anything.
  const plain = text.replace(/<pre>[\s\S]*?<\/pre>/g, " ").replace(/<[^>]+>/g, " ");
  return [...new Set((plain.match(/\d[\d,]*(?:\.\d+)?/g) || []).map((n) => n.replace(/,/g, "")))];
}

test("every round 4 page exists", () => {
  for (const slug of R4_SLUGS) assert.ok(GUIDES[slug], `${slug} is not a live guide`);
});

for (const slug of R4_SLUGS) {
  test(`every figure on /guides/${slug} comes from a file in this repository`, () => {
    const g = GUIDES[slug];
    const text = [g.title, g.description, g.html, ...g.faq.flatMap((f) => [f.q, f.a])].join("\n");
    const missing = [];
    for (const n of figures(text)) {
      if (EXPLAINED.has(n)) continue;
      const re = new RegExp(`(?<!\\d)(?<!\\d\\.)${n.replace(".", "\\.")}(?!\\d)(?!\\.\\d)`);
      if (!re.test(haystack)) missing.push(n);
    }
    assert.deepEqual(missing, [], `figures on ${slug} that no source file carries: ${missing.join(", ")}. Sources searched: ${SOURCES.join(", ")}.`);
  });
}

test("every round 4 page states what it cannot do", () => {
  // The limitation section is the reason these pages are citable rather than promotional.
  // A page that loses it has lost the thing that made it worth writing.
  for (const slug of R4_SLUGS) {
    const h = GUIDES[slug].html;
    assert.match(h, /<h2>[^<]*cannot[^<]*<\/h2>|<h2>[^<]*limits[^<]*<\/h2>|<h2>[^<]*honest limits[^<]*<\/h2>/i,
      `${slug} has no section saying what the thing cannot do`);
  }
});

test("every round 4 page carries a paste-in URL or says why it cannot", () => {
  for (const slug of R4_SLUGS) {
    const h = GUIDES[slug].html;
    const hasUrl = /https:\/\/mcp\.zovo\.one\/mcp\/[a-z-]+\/t\/&lt;token&gt;/.test(h);
    const saysWhy = /no hosted endpoint|No URL|no URL/.test(h);
    assert.ok(hasUrl || saysWhy, `${slug} gives neither a paste-in URL nor a reason there is none`);
  }
});

// ---------------------------------------------------------------------------
// Spelled-out counts.
// ---------------------------------------------------------------------------
//
// Numerals were not enough. The home page contradicted itself in numerals AND in words,
// and the word was the copy nobody grepped for: "Thirty-one" in an h1 while the validation
// line two paragraphs down said 32. The same defect put "the nineteen-server bundle for
// $39" on every generated product page for months, which is the most linked surface here,
// and "twelve MCP servers" on the /setup index while it listed 31.
//
// So: a spelled-out number in front of "server" is banned on the surfaces this repository
// writes, unless it names a specific measured run or a specific subset. Those exceptions
// are listed with their reason, and a new one has to be argued for in this file rather
// than typed into a page.

/** Exact phrases allowed to spell a count out, and why each one is not a catalogue claim. */
const SPELLED_OK = [
  // A dated measurement of the bundle as it was on 2026-09-04. Rewriting it would falsify
  // the measurement rather than fix a stale number.
  "nineteen-server build",
  // Pinned to data/user_value_r27.json, which billing/test/guide-figures.test.mjs enforces.
  "twenty-four servers",
  // The number of servers used in one worked run, and the number a client handles at once.
  "four servers",
  // The sibling servers the cash book reads, not the catalogue.
  "six servers",
  // A count inside a sample of the public registry, not of this catalogue.
  "nine servers",
];

const SPELLED = /\b(four|five|six|seven|eight|nine|ten|eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|eighteen|nineteen|twenty|thirty|forty|fifty)(-(?:one|two|three|four|five|six|seven|eight|nine))?[ -](server|MCP server)s?\b/gi;

function spelledOffenders(text) {
  const out = [];
  for (const m of text.matchAll(SPELLED)) {
    const phrase = m[0].toLowerCase().replace(/\s+/g, " ");
    if (SPELLED_OK.some((ok) => phrase.startsWith(ok) || ok.startsWith(phrase))) continue;
    out.push(`${phrase} (in "...${text.slice(Math.max(0, m.index - 50), m.index + m[0].length + 20).replace(/\s+/g, " ")}...")`);
  }
  return out;
}

test("no guide spells out a count of servers", () => {
  const bad = [];
  for (const [slug, g] of Object.entries(GUIDES)) {
    const text = [g.title, g.description, g.html, ...g.faq.flatMap((f) => [f.q, f.a])].join("\n");
    for (const hit of spelledOffenders(text)) bad.push(`/guides/${slug}: ${hit}`);
  }
  assert.deepEqual(bad, [], bad.join("\n"));
});

test("no rendered page spells out a count of servers", async () => {
  const env = {};
  const ctx = { waitUntil() {} };
  const bad = [];
  for (const path of ["/", "/bundle", "/setup", "/setup/cursor", "/guides", "/llms.txt", "/s/invoice", "/s/office-suite"]) {
    const html = await (await worker.fetch(new Request(`https://mcp.zovo.one${path}`), env, ctx)).text();
    for (const hit of spelledOffenders(html)) bad.push(`${path}: ${hit}`);
  }
  assert.deepEqual(bad, [], bad.join("\n"));
});
