// Contract suite for amortization. Generated shape, mechanical assertions only.
//
// Asserts the invariants of servers/amortization/SPEC.md that a test can check without
// judgement: one version number across package.json, src/version.ts, serverInfo and all
// four registry manifests; the remotes rule (the mcpb manifest carries remotes.json, the
// stdio-only names carry none); JSON-RPC-only stdout; tool-description hygiene; the
// free/Pro tier switch; that nothing outside this server's own two files is written; and
// that the accounts it journals to still match the ones servers/cash-book declares. It
// never asserts a number a human chose; those live in test/unit.test.mjs.
import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { client, sandbox, cleanup, proKey, storeDir, REPO, WORKED } from "./_client.mjs";

const HERE = join(REPO, "servers", "amortization");
const PRODUCT = "amortization";
const MAX_DESCRIPTION = 220;
const HARD_MAX_DESCRIPTION = 1200;
const FILE_ARGS = ["path", "url", "out_path", "template_path"];
const IMPERATIVE = /^(Call this tool|Use this)\b/;

/**
 * Tools that already break the two description rules on the day this suite was written.
 * The suite is a ratchet: an existing entry is reported, a NEW one fails. Both lists are
 * defects; the fix is in src, not here.
 */
const OVER_LENGTH_BASELINE = [];
const NON_IMPERATIVE_BASELINE = [];

function open(t, opts = {}) {
  const box = sandbox();
  const c = client({ dataHome: box.dataHome, ...opts });
  t.after(() => { c.close(); cleanup(box.dir); });
  return { box, c };
}

test("the version is one number: package.json, src/version.ts, serverInfo and every manifest agree", async (t) => {
  const pkg = JSON.parse(readFileSync(join(HERE, "package.json"), "utf8"));
  assert.equal(pkg.name, "@theluckystrike/mcp-amortization");
  assert.match(pkg.version, /^\d+\.\d+\.\d+$/, "package version must be a plain semver; the release bump moves it, the test does not pin it");
  assert.ok(pkg.description.length < 100, `package description is ${pkg.description.length} chars`);
  const generated = readFileSync(join(HERE, "src", "version.ts"), "utf8");
  assert.match(generated, /GENERATED by scripts\/sync-versions\.mjs/, "version.ts must be generated, not hand written");
  assert.match(generated, new RegExp(`export const VERSION = "${pkg.version.replace(/\./g, "\\.")}";`),
    `src/version.ts does not carry ${pkg.version}; run node scripts/sync-versions.mjs`);

  const { c } = open(t);
  const info = await c.init();
  assert.equal(info.serverInfo.version, pkg.version, "serverInfo.version must equal the package version");
  assert.equal(info.serverInfo.name, "mcp-amortization");

  for (const file of ["server.json", "server.mcpb.json", "server.variant.json", "server.lease.json"]) {
    const j = JSON.parse(readFileSync(join(HERE, file), "utf8"));
    assert.equal(j.version, pkg.version, `${file} version`);
    for (const p of j.packages ?? []) {
      assert.equal(p.version, pkg.version, `${file} package entry version`);
      assert.equal(p.transport.type, "stdio", `${file} declares a transport this server does not speak`);
      if (p.registryType === "mcpb") {
        // "TBD" until the release job hashes the bundle; after that, a real sha256.
        assert.ok(p.fileSha256 === "TBD" || /^[0-9a-f]{64}$/.test(p.fileSha256),
          `${file} fileSha256 is neither TBD nor a sha256: ${p.fileSha256}`);
      }
    }
    if (file === "server.mcpb.json") {
      const remotes = JSON.parse(readFileSync(join(HERE, "remotes.json"), "utf8"));
      assert.deepEqual(j.remotes, remotes, `${file} remotes must equal remotes.json (hosted at /mcp/amortization)`);
      assert.equal(remotes[0].url, "https://mcp.zovo.one/mcp/amortization");
    } else {
      assert.equal(j.remotes, undefined, `${file} is a stdio-only name and must not advertise a remote`);
    }
    assert.ok((j.description ?? "").length < 100, `${file} description is ${(j.description ?? "").length} chars; the registry 422s at 100`);
    assert.ok(!/[,.]\.$|,$/.test(j.description), `${file} description ends in a machine truncation`);
  }
  // Three distinct registry names, so the second and third are second listings, not copies.
  const names = ["server.json", "server.variant.json", "server.lease.json"]
    .map((f) => JSON.parse(readFileSync(join(HERE, f), "utf8")).name);
  assert.equal(new Set(names).size, 3, `registry names must differ: ${names.join(", ")}`);
  assert.deepEqual(names, [
    "io.github.theluckystrike/amortization",
    "io.github.theluckystrike/loan-schedule",
    "io.github.theluckystrike/lease-schedule",
  ]);

  // And sync-versions --check passes for the whole repo, so no sibling drifted either.
  execFileSync(process.execPath, [join(REPO, "scripts", "sync-versions.mjs"), "--check"], { encoding: "utf8" });
});

test("stdout carries JSON-RPC only across initialize, tools/list, a success and an error", async (t) => {
  const { c } = open(t);
  await c.init();
  await c.tools();
  await c.call("loan_create", WORKED);
  await c.call("loan_schedule", { loan: "LOAN-1999-0001" });
  await new Promise((r) => setTimeout(r, 150));

  const lines = [...c.stdoutLines, c.tail].filter((l) => l.trim() !== "");
  assert.ok(lines.length >= 4, `expected at least 4 protocol lines, got ${lines.length}`);
  for (const line of lines) {
    let m;
    try { m = JSON.parse(line); } catch { assert.fail(`non-JSON on stdout: ${JSON.stringify(line.slice(0, 200))}`); }
    assert.equal(m.jsonrpc, "2.0", `stdout line is JSON but not JSON-RPC: ${line.slice(0, 200)}`);
  }
});

test("every tool description is non-empty, single-paragraph, and within the ceiling", async (t) => {
  const { c } = open(t);
  await c.init();
  const tools = await c.tools();
  assert.equal(tools.length, 8, "tool count changed; update servers/amortization/SPEC.md");
  assert.deepEqual(tools.map((x) => x.name).sort(), [
    "license_activate", "license_status", "loan_create", "loan_journal",
    "loan_list", "loan_repay_early", "loan_schedule", "loans_report",
  ]);

  for (const tool of tools) {
    const d = tool.description ?? "";
    assert.ok(d.trim().length > 0, `${tool.name} has no description`);
    assert.equal(d, d.trim(), `${tool.name} description has leading or trailing whitespace`);
    assert.ok(d.length <= HARD_MAX_DESCRIPTION, `${tool.name} description is ${d.length} chars, over ${HARD_MAX_DESCRIPTION}`);
    assert.ok(!/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/u.test(d), `${tool.name} description carries an emoji`);
    assert.ok(!/[—]/.test(d), `${tool.name} description carries an em dash`);
  }

  const over = tools.filter((x) => (x.description ?? "").length > MAX_DESCRIPTION).map((x) => x.name).sort();
  const regressions = over.filter((n) => !OVER_LENGTH_BASELINE.includes(n));
  assert.deepEqual(regressions, [], `new tool descriptions over ${MAX_DESCRIPTION} chars`);
});

test("no tool takes a file path, so nothing here writes outside its own data directory", async (t) => {
  const { c } = open(t);
  await c.init();
  const tools = await c.tools();
  const fileTools = tools.filter((x) => Object.keys(x.inputSchema?.properties ?? {}).some((k) => FILE_ARGS.includes(k)));
  assert.deepEqual(fileTools.map((x) => x.name), []);
  const offenders = fileTools.filter((x) => !IMPERATIVE.test(x.description ?? "")).map((x) => x.name).sort();
  assert.deepEqual(offenders.filter((n) => !NON_IMPERATIVE_BASELINE.includes(n)), []);
});

test("license_status reports free with no key and pro with a signed key", async (t) => {
  const { c: free } = open(t);
  await free.init();
  const f = await free.call("license_status", {});
  assert.equal(f.isError, false, f.text);
  assert.match(f.text, /"tier":\s*"free"/, f.text.slice(0, 300));

  const key = proKey(PRODUCT);
  assert.match(key, /^MCPL1\./);
  const { c: pro } = open(t, { key });
  await pro.init();
  assert.match((await pro.call("license_status", {})).text, /"tier":\s*"pro"/);
});

test("the free tier is the documented one: create and schedule free, early repayment, journal and report Pro", async (t) => {
  const { c } = open(t);
  await c.init();
  const made = await c.json("loan_create", WORKED);
  assert.equal((await c.call("loan_schedule", { loan: made.created.id })).isError, false);
  assert.equal((await c.call("loan_list", {})).isError, false);
  for (const [tool, args] of [
    ["loan_repay_early", { loan: made.created.id, as_of_period: 3 }],
    ["loan_journal", { loan: made.created.id, period: 1 }],
    ["loans_report", {}],
  ]) {
    const r = await c.call(tool, args);
    assert.equal(r.isError, true, `${tool} answered on the free tier`);
    assert.match(r.text, /Pro is a one-time \$\d+ for this server/, tool);
    assert.match(r.text, /license_activate/, tool);
    // The conversion instrument: every gate link carries the tool that tripped it.
    assert.match(r.text, new RegExp(`src=${PRODUCT}\\.${tool}`), `${tool} gate link is untagged`);
  }
});

test("the resource and the prompt are registered and answer", async (t) => {
  const { c } = open(t);
  await c.init();
  const res = (await c.send("resources/read", { uri: "loan://accounts" })).result;
  const body = JSON.parse(res.contents[0].text);
  assert.deepEqual(body.accounts.map((a) => a.account), ["cash", "interest_expense", "loan_liability"]);
  assert.equal(body.posts_to_any_other_store, false);
  assert.equal(body.writes.length, 1);
  assert.equal(body.writes[0].store, "amortization");
  assert.deepEqual(body.writes[0].files, ["loans.json", "counter.json"]);
  const prompts = (await c.send("prompts/list", {})).result.prompts;
  assert.deepEqual(prompts.map((p) => p.name), ["check_a_quote"]);
});

test("this server writes two files and no others, on any tool", async (t) => {
  const { box, c } = open(t, { key: proKey() });
  await c.init();
  const made = await c.json("loan_create", WORKED);
  await c.call("loan_schedule", { loan: made.created.id });
  await c.call("loan_list", {});
  await c.call("loan_repay_early", { loan: made.created.id, as_of_period: 4, penalty_minor: 100 });
  await c.call("loan_journal", { loan: made.created.id, period: 1 });
  await c.call("loans_report", {});
  const files = readdirSync(storeDir(box.dataHome)).filter((f) => !f.startsWith("."));
  assert.deepEqual(files.sort(), ["counter.json", "loans.json"]);
  // And no sibling server's directory was created, let alone written.
  const siblings = readdirSync(join(box.dataHome, "mcp-servers"));
  assert.deepEqual(siblings, ["amortization"], `a sibling store was touched: ${siblings.join(", ")}`);
});

test("no schedule is stored: the register holds terms only", async (t) => {
  const { box, c } = open(t);
  await c.init();
  await c.call("loan_create", { ...WORKED, lender: "Nordbank", note: "signed" });
  const raw = readFileSync(join(storeDir(box.dataHome), "loans.json"), "utf8");
  assert.ok(!/opening_minor|closing_minor|"rows"/.test(raw), "a schedule row was stored; every row must be derived on the call");
  const stored = JSON.parse(raw)[0];
  assert.deepEqual(Object.keys(stored).sort(), [
    "balloon_minor", "compounding", "created", "currency", "effective_annual_rate_bps", "fees_minor",
    "id", "kind", "lender", "method", "name", "note", "payment_frequency", "payment_minor",
    "principal_minor", "rate_bps", "start_date", "term_periods", "updated",
  ].sort());
});

test("the account ids this server journals to are the cash book's own", async () => {
  // If servers/cash-book renames its cash account, a journal produced here would post to
  // an account its ledger does not have, and the entry would look posted and be orphaned.
  const ledger = readFileSync(join(REPO, "servers", "cash-book", "src", "ledger.ts"), "utf8");
  assert.match(ledger, /export const CASH = "cash";/, "servers/cash-book renamed its cash account");
  const accounts = readFileSync(join(HERE, "src", "accounts.ts"), "utf8");
  assert.match(accounts, /export const CASH = "cash";/);
  // The other two are this server's own, and follow that file's id convention exactly.
  for (const id of ["loan_liability", "interest_expense"]) {
    assert.match(accounts, new RegExp(`"${id}"`), `${id} is not declared`);
    assert.match(id, /^[a-z_]+$/, "the cash book's ids are lower snake case");
  }
});

test("src holds no network call and no stdout write", async () => {
  // grep exits 1 on no match, which is the passing case here.
  let raw = "";
  try {
    raw = execFileSync("grep", ["-rEn", "fetch\\(|https?://|node:http|node:net|node:dns|console\\.", join(HERE, "src")], { encoding: "utf8" });
  } catch (e) {
    if (e.status !== 1) throw e;
  }
  const out = raw.trim().split("\n").filter(Boolean);
  const offending = out.filter((l) => !/mcp\.zovo\.one/.test(l));
  assert.deepEqual(offending, [], `network or stdout in src:\n${offending.join("\n")}`);
});

test("the required files are all present", () => {
  for (const f of [
    "package.json", "tsconfig.json", "README.md", "LICENSE", "SPEC.md", "RESULT.md",
    "server.json", "server.mcpb.json", "server.variant.json", "server.lease.json",
    "remotes.json", "smithery.yaml", "glama.json", "llms-install.md", "Dockerfile",
    "src/index.ts", "src/lib.ts", "src/schedule.ts", "src/store.ts", "src/accounts.ts", "src/version.ts",
  ]) {
    assert.ok(existsSync(join(HERE, f)), `missing ${f}`);
  }
});

test("every schedule row the server emits is an integer number of minor units", async (t) => {
  const { c } = open(t);
  await c.init();
  const made = await c.json("loan_create", { ...WORKED, rate_bps: 733, term_periods: 37, payment_frequency: "fortnightly" });
  const s = await c.json("loan_schedule", { loan: made.created.id });
  for (const r of s.rows) {
    for (const k of ["opening_minor", "payment_minor", "interest_minor", "principal_minor", "closing_minor"]) {
      assert.ok(Number.isInteger(r[k]), `${k} is not an integer in period ${r.period}: ${r[k]}`);
    }
    assert.match(r.date, /^\d{4}-\d{2}-\d{2}$/);
  }
  assert.equal(s.rows[s.rows.length - 1].closing_minor, 0);
});
