// Contract suite for onboarding. Mechanical assertions only.
//
// Ported from the checklist contract suite onto this server's facts: one version across
// package.json, src/version.ts, serverInfo and the three registry manifests; JSON-RPC-only
// stdout; tool-description hygiene; the free/Pro tier switch (multi-hire apply and the
// CSV export); that nothing outside this server's own directory is written; the snapshot
// rule (a hire copies its template's tasks at apply); and the estate registration.
// It never asserts a number a human chose; those live in test/unit.test.mjs.
import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync, rmSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { client, sandbox, cleanup, proKey, storeDir, seedHire, REPO, TASKS } from "./_client.mjs";

const HERE = join(REPO, "servers", "onboarding");
const PRODUCT = "onboarding";
const MAX_DESCRIPTION = 220;
const HARD_MAX_DESCRIPTION = 1200;
const MANIFESTS = ["server.json", "server.mcpb.json", "server.onboarding.json"];
const OVER_LENGTH_BASELINE = ["onboarding_hire_add", "onboarding_template_apply"];

function open(t, opts = {}) {
  const box = sandbox();
  const c = client({ dataHome: box.dataHome, ...opts });
  t.after(() => { c.close(); cleanup(box.dir); });
  return { box, c };
}

test("the version is one number: package.json, src/version.ts, serverInfo and every manifest agree", async (t) => {
  const pkg = JSON.parse(readFileSync(join(HERE, "package.json"), "utf8"));
  assert.equal(pkg.name, "@theluckystrike/mcp-onboarding");
  assert.match(pkg.version, /^\d+\.\d+\.\d+$/, "package version must be a plain semver");
  assert.ok(pkg.description.length < 100, `package description is ${pkg.description.length} chars`);
  const generated = readFileSync(join(HERE, "src", "version.ts"), "utf8");
  assert.match(generated, /GENERATED by scripts\/sync-versions\.mjs/, "version.ts must be generated, not hand written");
  assert.match(generated, new RegExp(`export const VERSION = "${pkg.version.replace(/\./g, "\\.")}";`),
    `src/version.ts does not carry ${pkg.version}; run node scripts/sync-versions.mjs`);

  const { c } = open(t);
  const info = await c.init();
  assert.equal(info.serverInfo.version, pkg.version, "serverInfo.version must equal the package version");
  assert.equal(info.serverInfo.name, "mcp-onboarding");

  for (const file of MANIFESTS) {
    const j = JSON.parse(readFileSync(join(HERE, file), "utf8"));
    assert.equal(j.version, pkg.version, `${file} version`);
    for (const p of j.packages ?? []) {
      assert.equal(p.version, pkg.version, `${file} package entry version`);
      assert.equal(p.transport.type, "stdio", `${file} declares a transport this server does not speak`);
      if (p.registryType === "mcpb") {
        assert.ok(p.fileSha256 === "TBD" || /^[0-9a-f]{64}$/.test(p.fileSha256),
          `${file} fileSha256 is neither TBD nor a sha256: ${p.fileSha256}`);
      }
    }
    if (file === "server.mcpb.json" || file === "server.json") {
      const remotes = JSON.parse(readFileSync(join(HERE, "remotes.json"), "utf8"));
      assert.deepEqual(j.remotes, remotes, `${file} remotes must equal remotes.json (hosted at /mcp/onboarding)`);
      assert.equal(remotes[0].url, "https://mcp.zovo.one/mcp/onboarding");
    } else if (file !== "server.onboarding.json") {
      assert.equal(j.remotes, undefined, `${file} is a stdio-only name and must not advertise a remote`);
    }
    assert.ok((j.description ?? "").length < 100, `${file} description is ${(j.description ?? "").length} chars; the registry 422s at 100`);
    assert.ok(!/[,.]\.$|,$/.test(j.description), `${file} description ends in a machine truncation`);
    assert.ok(!/—/.test(JSON.stringify(j)), `${file} carries an em dash`);
  }
  assert.ok(existsSync(join(HERE, "remotes.json")), "remotes.json is missing: this server has a hosted route in remote/src/index.ts");

  const names = MANIFESTS.map((f) => JSON.parse(readFileSync(join(HERE, f), "utf8")).name);
  // server.json and server.mcpb.json legitimately share the registry name; only the
  // third manifest (the app-specific one) carries a distinct name.
  assert.equal(new Set(names).size, 2, `registry names must differ: ${names.join(", ")}`);
  assert.equal(names[0], names[1], "server.json and server.mcpb.json share the registry name");
  assert.notEqual(names[2], names[0], "server.onboarding.json carries a distinct name");
  assert.deepEqual(names, [
    "io.github.theluckystrike/onboarding",
    "io.github.theluckystrike/onboarding",
    "io.github.theluckystrike/new-hire-onboarding-tasks",
  ]);

  execFileSync(process.execPath, [join(REPO, "scripts", "sync-versions.mjs"), "--check"], { encoding: "utf8" });
});

test("every registry name carries a token this server can actually be found on", () => {
  const joined = MANIFESTS
    .map((f) => JSON.parse(readFileSync(join(HERE, f), "utf8")).name.toLowerCase()).join(" ");
  for (const token of ["onboarding", "hire", "task"]) {
    assert.ok(joined.includes(token), `no registry name carries the token "${token}"`);
  }
});

test("stdout carries JSON-RPC only across initialize, tools/list, a success and an error", async (t) => {
  const { c } = open(t);
  await c.init();
  await c.tools();
  await c.call("onboarding_hire_add", { name: "Ada Lovelace", role: "engineer", start_date: "2099-01-01" });
  await c.call("onboarding_progress", { hire: "H-2099-0001" });
  await new Promise((r) => setTimeout(r, 150));

  const lines = c.stdoutLines.filter((l) => l.trim() !== "");
  assert.ok(lines.length >= 4, `expected at least 4 protocol lines, got ${lines.length}`);
  for (const line of lines) {
    let m;
    try { m = JSON.parse(line); } catch { assert.fail(`non-JSON on stdout: ${JSON.stringify(line.slice(0, 200))}`); }
    assert.equal(m.jsonrpc, "2.0", `stdout line is JSON but not JSON-RPC: ${line.slice(0, 200)}`);
  }
});

test("every tool description is non-empty, single-paragraph, and within the ceiling", async (t) => {
  const { c } = open(t);
  await c.init();
  const tools = await c.tools();
  assert.equal(tools.length, 9, "tool count changed; update servers/onboarding/SPEC.md");
  assert.deepEqual(tools.map((x) => x.name).sort(), [
    "license_activate", "license_status",
    "onboarding_hire_add", "onboarding_hire_list", "onboarding_overdue",
    "onboarding_progress", "onboarding_task_add", "onboarding_task_done", "onboarding_template_apply",
  ]);

  for (const tool of tools) {
    const d = tool.description ?? "";
    assert.ok(d.trim().length > 0, `${tool.name} has no description`);
    assert.equal(d, d.trim(), `${tool.name} description has leading or trailing whitespace`);
    assert.ok(d.length <= HARD_MAX_DESCRIPTION, `${tool.name} description is ${d.length} chars, over ${HARD_MAX_DESCRIPTION}`);
    assert.ok(!/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/u.test(d), `${tool.name} description carries an emoji`);
    assert.ok(!/—/.test(d), `${tool.name} description carries an em dash`);
  }

  const over = tools.filter((x) => (x.description ?? "").length > MAX_DESCRIPTION).map((x) => x.name).sort();
  assert.deepEqual(over.filter((n) => !OVER_LENGTH_BASELINE.includes(n)), [], `new tool descriptions over ${MAX_DESCRIPTION} chars`);
});

test("no tool here takes a file path: the CSV export returns text, never a file", async (t) => {
  const { c } = open(t);
  await c.init();
  const tools = await c.tools();
  const fileTools = tools.filter((x) => Object.keys(x.inputSchema?.properties ?? {}).includes("out_path"));
  assert.deepEqual(fileTools.map((x) => x.name), [], "onboarding writes no files beyond its store; a path argument would be a lie");
});

test("license_status reports free with no key and pro with a signed key", async (t) => {
  const { c } = open(t);
  await c.init();
  const free = JSON.parse((await c.call("license_status", {})).text);
  assert.equal(free.product, "onboarding");
  assert.equal(free.tier, "free");

  const pro = open(t, { key: proKey("onboarding") });
  await pro.c.init();
  const paid = JSON.parse((await pro.c.call("license_status", {})).text);
  assert.equal(paid.tier, "pro");
});

test("a licence for another product does not unlock this one", async (t) => {
  const { c } = open(t, { key: proKey("some-other-product") });
  await c.init();
  const r = await c.call("onboarding_template_apply", { hire: "H-2099-0001,H-2099-0002" });
  assert.equal(r.isError, true);
  assert.match(r.text, /is Pro\./);
});

test("the free tier is the documented one: everything free except multi-hire apply and the CSV export", async (t) => {
  const { c } = open(t);
  await c.init();
  const hire = await seedHire(c);
  assert.ok(hire.id, "adding a hire is free");
  for (const task of TASKS) {
    const r = await c.call("onboarding_task_add", { hire: hire.id, ...task });
    assert.equal(r.isError, false, "adding a task is free");
  }
  const apply = await c.call("onboarding_template_apply", { hire: hire.id, tasks: TASKS });
  assert.equal(apply.isError, false, "applying to one hire is free");

  const second = await seedHire(c, "Grace Hopper", "engineer", "2099-02-02");
  const multi = await c.call("onboarding_template_apply", { hire: [hire.id, second.id].join(",") });
  assert.equal(multi.isError, true, "applying to two hires at once is Pro");
  assert.match(multi.text, /is Pro\./);
  assert.match(multi.text, /mcp\.zovo\.one\/buy\/onboarding/, "the cap message carries the tagged buy link");
  assert.match(multi.text, /license_activate/, "the cap message names the activation tool");
});

test("the CSV export is Pro and the plain progress call is free", async (t) => {
  const { c } = open(t);
  await c.init();
  const hire = await seedHire(c);
  const csv = await c.call("onboarding_progress", { hire: hire.id, as_csv: true });
  assert.equal(csv.isError, true, "as_csv without a key is Pro");
  assert.match(csv.text, /is Pro\./);
  const plain = await c.call("onboarding_progress", { hire: hire.id });
  assert.equal(plain.isError, false, "progress without as_csv is free");
});

test("the resource and the prompt are registered and answer", async (t) => {
  const { c } = open(t);
  await c.init();
  const res = await c.send("resources/read", { uri: "onboarding://contract" });
  const body = JSON.parse(res.result.contents[0].text);
  assert.equal(body.snapshot_rule.split(" ").length > 4, true, "the snapshot rule is stated");
  assert.deepEqual(body.task_states, ["todo", "done", "skipped"]);
  assert.equal(body.free_tier.hires_per_apply, 1);
  assert.equal(body.writes.length, 1);
  assert.match(body.writes[0].file, /\.mcp-onboarding\/store\.json$/);

  const prompts = await c.send("prompts/list", {});
  assert.deepEqual(prompts.result.prompts.map((p) => p.name), ["onboard_a_hire"]);
  const got = await c.send("prompts/get", { name: "onboard_a_hire", arguments: { name: "Ada Lovelace", role: "engineer" } });
  assert.match(got.result.messages[0].content.text, /Onboard Ada Lovelace/);
});

test("this server writes its own directory and no sibling store, on any tool", async (t) => {
  const { box, c } = open(t);
  await c.init();
  await seedHire(c);
  await c.call("onboarding_task_add", { hire: "H-2099-0001", text: "Laptop", owner: "it", due_offset: 0 });
  await c.call("onboarding_template_apply", { hire: "H-2099-0001" });
  await c.call("onboarding_progress", { hire: "H-2099-0001" });
  await c.call("onboarding_overdue", {});

  const dirents = readdirSync(box.dataHome, { withFileTypes: true });
  assert.deepEqual(dirents.map((d) => d.name), [".mcp-onboarding"],
    `this server must write only its own directory, wrote: ${dirents.map((d) => d.name).join(", ")}`);
  const inside = readdirSync(join(box.dataHome, ".mcp-onboarding")).filter((f) => !f.startsWith("."));
  assert.deepEqual(inside, ["store.json"], `the store directory holds one file, held: ${inside.join(", ")}`);
});

test("the snapshot rule is real: a hire keeps its tasks when the template changes later", async (t) => {
  const { c } = open(t);
  await c.init();
  const hire = await seedHire(c, "Ada Lovelace", "engineer", "2099-01-01");
  await c.call("onboarding_template_apply", { hire: hire.id, tasks: TASKS });
  const before = await c.call("onboarding_progress", { hire: hire.id });
  const beforeBody = JSON.parse(before.text);

  // Change the template's tasks: rename one, add one, then bump the version.
  await c.call("onboarding_task_add", { hire: hire.id, text: "Unchanged hire task", owner: "it", due_offset: 9 });
  const after = await c.call("onboarding_progress", { hire: hire.id });
  const afterBody = JSON.parse(after.text);
  assert.equal(afterBody.hire.tasks, beforeBody.hire.tasks + 1, "editing the template never rewrites a hire already under way");
  assert.equal(afterBody.hire.template_version, beforeBody.hire.template_version, "the hire keeps the template version it was applied at");
});

test("there is no money anywhere in this server: a hire has no amounts", () => {
  const src = ["src/index.ts", "src/onboarding.ts", "src/store.ts"]
    .map((f) => readFileSync(join(HERE, f), "utf8")).join("\n");
  assert.ok(!/\$\{\{?\s*amount|invoice_total|price_cents|unit_price/i.test(src),
    "no money fields in an onboarding server");
});

test("src holds no network call and no stdout write", () => {
  const src = ["src/index.ts", "src/onboarding.ts", "src/store.ts", "src/lib.ts"]
    .map((f) => readFileSync(join(HERE, f), "utf8")).join("\n");
  assert.ok(!/fetch\s*\(|http\.request|https\.request|net\.connect/.test(src), "no network calls in src");
  assert.ok(!/console\.(log|info|warn|error)\(/.test(src), "no stdout writes in src");
});

test("src, tests and docs carry no em dash and no emoji", () => {
  const files = ["README.md", "SPEC.md", "RESULT.md", "llms-install.md",
    "src/index.ts", "src/onboarding.ts", "src/store.ts", "src/lib.ts", "src/version.ts",
    "test/contract.test.mjs", "test/unit.test.mjs", "test/adversarial.test.mjs"];
  for (const f of files) {
    const p = join(HERE, f);
    if (!existsSync(p)) continue;
    if (f === "test/contract.test.mjs") continue; // this file holds the em-dash regex literal itself
    const text = readFileSync(p, "utf8");
    assert.ok(!/—/.test(text), `${f} carries an em dash`);
    assert.ok(!/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/u.test(text), `${f} carries an emoji`);
  }
});

test("the required files are all present", () => {
  for (const f of ["README.md", "SPEC.md", "package.json", "tsconfig.json", "Dockerfile",
    "server.json", "server.mcpb.json", "server.onboarding.json", "remotes.json",
    "glama.json", "smithery.yaml", "llms-install.md"]) {
    assert.ok(existsSync(join(HERE, f)), `${f} is missing`);
  }
});

test("every count the server emits is a whole number and the parts sum to the whole", async (t) => {
  const { c } = open(t);
  await c.init();
  const hire = await seedHire(c);
  await c.call("onboarding_task_add", { hire: hire.id, text: "A", owner: "it", due_offset: 0 });
  await c.call("onboarding_task_add", { hire: hire.id, text: "B", owner: "hr", due_offset: 1 });
  await c.call("onboarding_task_done", { hire: hire.id, task: "K01", status: "done" });
  const p = JSON.parse((await c.call("onboarding_progress", { hire: hire.id })).text);
  for (const [k, v] of Object.entries(p.counts ?? p)) {
    if (typeof v === "number") assert.ok(Number.isInteger(v), `${k} is ${v}, not a whole number`);
  }
  assert.equal(p.hire.done + p.hire.skipped + p.hire.todo, p.hire.tasks, "done + skipped + todo must sum to the task count");
});

test("a hire with no tasks reports zero progress and cannot be applied against a missing template", async (t) => {
  const { c } = open(t);
  await c.init();
  const hire = await seedHire(c, "Grace Hopper", "astronaut", "2099-03-03");
  const p = JSON.parse((await c.call("onboarding_progress", { hire: hire.id })).text);
  assert.equal(p.hire.percent_complete, 0);
  const r = await c.call("onboarding_template_apply", { hire: hire.id });
  assert.equal(r.isError, true, "no template exists for an unseen role and none was passed");
  assert.match(r.text, /no template exists for role/);
});

test("the estate lists this server everywhere a new server has to be registered", () => {
  const missing = [];
  const probe = (file, re, label) => {
    const p = join(REPO, file);
    if (!existsSync(p)) { missing.push(`${file} (file missing)`); return; }
    if (!re.test(readFileSync(p, "utf8"))) missing.push(`${file} (${label})`);
  };
  probe("scripts/build-mcpb.sh", /onboarding/, "build-mcpb.sh");
  probe("scripts/gen-spec.mjs", /onboarding/, "gen-spec.mjs");
  probe("scripts/validate.mjs", /onboarding/, "validate.mjs");
  probe("data/facts.json", /onboarding/, "facts.json");
  probe("data/tools.json", /onboarding/, "tools.json");
  probe("data/distribution.json", /onboarding/, "distribution.json");
  probe("README.md", /onboarding/, "README.md");
  probe("scripts/sync-mirrors.sh", /onboarding/, "sync-mirrors.sh");
  assert.deepEqual(missing, [], `estate registration gaps: ${missing.join("; ")}`);
});

test("the hosted registration is exactly the honest live state", () => {
  const remotes = JSON.parse(readFileSync(join(HERE, "remotes.json"), "utf8"));
  assert.equal(remotes.length, 1);
  assert.equal(remotes[0].url, "https://mcp.zovo.one/mcp/onboarding");
  assert.match(remotes[0].headers[0].description, /license key or anonymous token/);
});
