#!/usr/bin/env node
// Renders servers/*/README.md into billing/src/pages.js so mcp.zovo.one serves a product page per server.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { marked } from "marked";
const ids = ["time-tracker", "price-tracker", "spreadsheet", "invoice", "expense-tracker", "currency", "timezone", "docx", "resume", "recurring", "clauses", "pdf", "calendar", "kanban", "image", "bank-statement", "quotes", "barcode", "zip"];
const facts = JSON.parse(readFileSync("data/facts.json", "utf8"));
const out = {};

/** Append ?src=<src> to every untagged /buy/<product> href in a block of rendered HTML. */
function tagBuyLinks(html, src) {
  return html.replace(/(href="(?:https:\/\/mcp\.zovo\.one)?\/buy\/[a-z0-9-]+)"/g, `$1?src=${src}"`);
}

/**
 * Every generated page's CTA block gets a bundle mention, regardless of whether that
 * server's README happens to say anything about the bundle already: some do, some
 * (e.g. time-tracker) do not link to /buy at all. Rather than depend on README wording,
 * this appends one sentence, tagged src=store.s.<id>.bundle so its clicks are told apart
 * from a same-server buy click on /stats/clicks.
 */
function addBundleCta(html, id) {
  const bundleLink = `<a href="https://mcp.zovo.one/buy/bundle?src=store.s.${id}.bundle">the nineteen-server bundle for $39</a>`;
  const taggedHref = new RegExp(`(<p>[^<]*<a href="https://mcp\\.zovo\\.one/buy/${id}\\?src=store\\.s\\.${id}"[\\s\\S]*?<\\/a>[^<]*)(<\\/p>)`);
  if (taggedHref.test(html)) {
    return html.replace(taggedHref, (m, before, after) => `${before} Or ${bundleLink}.${after}`);
  }
  return html + `\n<p>Or ${bundleLink}.</p>`;
}

for (const id of ids) {
  if (!existsSync(`servers/${id}/README.md`)) { console.error(`skip ${id}: no README yet`); continue; }
  const md = readFileSync(`servers/${id}/README.md`, "utf8");
  // Conversion instrument (docs/CONVERSION_INSTRUMENT.md): a /buy link that reaches the
  // storefront from a README carried no src, so its clicks landed in <product>.unknown.
  // Tag every one of them with the page that rendered it. Links that already carry a
  // query string are left alone, so this stays idempotent.
  const tagged = tagBuyLinks(marked.parse(md.replace(/<!--[\s\S]*?-->/g, "")), `store.s.${id}`);
  const body = addBundleCta(tagged, id);
  const f = facts.servers[id];
  out[id] = { title: f.title, tagline: f.tagline, description: f.does, html: body };
}
writeFileSync("billing/src/pages.js", "// generated by scripts/build-pages.mjs, do not edit\nexport const PAGES = " + JSON.stringify(out) + ";\n");
console.log("pages:", Object.keys(out).join(", "), "bytes", JSON.stringify(out).length);
