#!/usr/bin/env node
// Renders servers/*/README.md into billing/src/pages.js so mcp.zovo.one serves a product page per server.
import { readFileSync, writeFileSync } from "node:fs";
import { marked } from "marked";
const ids = ["time-tracker", "price-tracker", "spreadsheet", "invoice", "expense-tracker", "currency", "timezone", "docx"];
const facts = JSON.parse(readFileSync("data/facts.json", "utf8"));
const out = {};
for (const id of ids) {
  const md = readFileSync(`servers/${id}/README.md`, "utf8");
  const body = marked.parse(md.replace(/<!--[\s\S]*?-->/g, ""));
  const f = facts.servers[id];
  out[id] = { title: f.title, tagline: f.tagline, description: f.does, html: body };
}
writeFileSync("billing/src/pages.js", "// generated by scripts/build-pages.mjs, do not edit\nexport const PAGES = " + JSON.stringify(out) + ";\n");
console.log("pages:", Object.keys(out).join(", "), "bytes", JSON.stringify(out).length);
