// Mechanical transform: copy the three stdio servers' TypeScript sources into
// remote/src/vendor/<name>/ so the remote worker runs the SAME tool handlers.
// Only three things change:
//   1. node:fs / node:os are redirected to the in-memory shims (Workers has no fs).
//   2. @theluckystrike/mcp-license is redirected to the request-scoped gate shim.
//   3. index.ts's module body is wrapped in `export function createServer()` so a
//      fresh McpServer exists per request (stateless streamable HTTP), and the
//      stdio boot block is dropped.
// Run: node remote/build-vendor.mjs
import { readFileSync, writeFileSync, mkdirSync, rmSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "remote", "src", "vendor");

const SERVERS = {
  "time-tracker": ["index.ts"],
  "price-tracker": ["index.ts", "extract.ts", "fetch.ts", "redirect.ts", "store.ts"],
  "invoice": ["index.ts", "money.ts", "store.ts"],
};

const IMPORT_RE = /^import\b[^;]*?;/gms;

function rewriteSpec(spec, depth) {
  const up = "../".repeat(depth);
  if (spec === "node:fs") return `${up}shims/fs.js`;
  if (spec === "node:os") return `${up}shims/os.js`;
  if (spec === "@theluckystrike/mcp-license") return `${up}shims/license.js`;
  return spec;
}

function rewriteImports(text, depth) {
  return text.replace(/from\s+"([^"]+)"/g, (m, s) => `from "${rewriteSpec(s, depth)}"`);
}

rmSync(OUT, { recursive: true, force: true });

for (const [name, files] of Object.entries(SERVERS)) {
  const dir = join(OUT, name);
  mkdirSync(dir, { recursive: true });
  for (const f of files) {
    let src = readFileSync(join(ROOT, "servers", name, "src", f), "utf8");
    src = src.replace(/^#!.*\n/, "");
    if (f !== "index.ts") {
      writeFileSync(join(dir, f), rewriteImports(src, 2));
      continue;
    }
    // invoice: the local pdfkit writer needs a real filesystem; the remote build
    // swaps in an HTML renderer that returns a signed download URL.
    if (name === "invoice") {
      src = src.replace('import { renderInvoicePdf } from "./pdf.js";',
        'import { renderInvoicePdf } from "../../shims/pdf.js";');
      src = src.replace(
        "    const out = expandPath(a.out_path ?? join(dataDir(), \"pdf\", `${inv.number}.pdf`));\n    await renderInvoicePdf(inv, biz, out, { branded: !pro, logo: pro });",
        "    const out = await renderInvoicePdf(inv, biz, `${inv.number}.pdf`, { branded: !pro, logo: pro });");
      src = src.replace("return ok(`Wrote ${out}${note}`);",
        "return ok(`Invoice ${inv.number} rendered. Download (HTML, valid 1 hour): ${out}${note}`);");
    }
    // 1. hoist the imports
    const imports = [];
    src = src.replace(IMPORT_RE, (m) => {
      if (m.includes("StdioServerTransport")) return "";
      imports.push(rewriteImports(m, 2));
      return "";
    });
    // 2. drop the stdio boot block
    src = src.replace(/\nasync function main\(\)[\s\S]*$/, "\n");
    src = src.replace(/\nconst transport = new StdioServerTransport\(\);[\s\S]*$/, "\n");
    const body = src.trim();
    writeFileSync(join(dir, "index.ts"),
      `// GENERATED by remote/build-vendor.mjs from servers/${name}/src/index.ts. Do not edit.\n` +
      imports.join("\n") + "\n\n" +
      `export function createServer() {\n${body}\n\nreturn server;\n}\n`);
  }
  console.log(`vendored ${name}: ${files.join(", ")}`);
}
