// Contract suite for catalogue. Generated shape, mechanical assertions only.
//
// Asserts the invariants of servers/catalogue/SPEC.md that a test can check without
// judgement: one version number across package.json, src/version.ts, serverInfo and all
// four registry manifests; the remotes rule (the mcpb manifest carries remotes.json, the
// stdio-only names carry none); JSON-RPC-only stdout; tool-description hygiene; the
// free/Pro tier switch; that nothing outside this server's own directory is written; and
// that the invoice engine is imported rather than restated. It never asserts a number a
// human chose; those live in test/unit.test.mjs.
import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { client, sandbox, cleanup, proKey, storeDir, writeProfile, seed, REPO, LINES, RESOLVE_DATE } from "./_client.mjs";

const HERE = join(REPO, "servers", "catalogue");
const PRODUCT = "catalogue";
const MAX_DESCRIPTION = 220;
const HARD_MAX_DESCRIPTION = 1200;
const FILE_ARGS = ["path", "url", "out_path", "template_path"];
const IMPERATIVE = /^(Call this tool|Use this)\b/;

/**
 * Tools that already break the two description rules on the day this suite was written.
 * The suite is a ratchet: an existing entry is reported, a NEW one fails. Both lists are
 * defects; the fix is in src, not here.
 */
const OVER_LENGTH_BASELINE = [];
const NON_IMPERATIVE_BASELINE = [];

function open(t, opts = {}) {
  const box = sandbox();
  writeProfile(box.dataHome);
  const c = client({ dataHome: box.dataHome, ...opts });
  t.after(() => { c.close(); cleanup(box.dir); });
  return { box, c };
}

test("the version is one number: package.json, src/version.ts, serverInfo and every manifest agree", async (t) => {
  const pkg = JSON.parse(readFileSync(join(HERE, "package.json"), "utf8"));
  assert.equal(pkg.name, "@theluckystrike/mcp-catalogue");
  assert.match(pkg.version, /^\d+\.\d+\.\d+$/, "package version must be a plain semver; the release bump moves it, the test does not pin it");
  assert.ok(pkg.description.length < 100, `package description is ${pkg.description.length} chars`);
  const generated = readFileSync(join(HERE, "src", "version.ts"), "utf8");
  assert.match(generated, /GENERATED by scripts\/sync-versions\.mjs/, "version.ts must be generated, not hand written");
  assert.match(generated, new RegExp(`export const VERSION = "${pkg.version.replace(/\./g, "\\.")}";`),
    `src/version.ts does not carry ${pkg.version}; run node scripts/sync-versions.mjs`);

  const { c } = open(t);
  const info = await c.init();
  assert.equal(info.serverInfo.version, pkg.version, "serverInfo.version must equal the package version");
  assert.equal(info.serverInfo.name, "mcp-catalogue");

  for (const file of ["server.json", "server.mcpb.json", "server.variant.json", "server.rate-card.json"]) {
    const j = JSON.parse(readFileSync(join(HERE, file), "utf8"));
    assert.equal(j.version, pkg.version, `${file} version`);
    for (const p of j.packages ?? []) {
      assert.equal(p.version, pkg.version, `${file} package entry version`);
      assert.equal(p.transport.type, "stdio", `${file} declares a transport this server does not speak`);
      if (p.registryType === "mcpb") {
        // "TBD" until the release job hashes the bundle; after that, a real sha256.
        assert.ok(p.fileSha256 === "TBD" || /^[0-9a-f]{64}$/.test(p.fileSha256),
          `${file} fileSha256 is neither TBD nor a sha256: ${p.fileSha256}`);
      }
    }
    if (file === "server.mcpb.json") {
      const remotes = JSON.parse(readFileSync(join(HERE, "remotes.json"), "utf8"));
      assert.deepEqual(j.remotes, remotes, `${file} remotes must equal remotes.json (hosted at /mcp/catalogue)`);
      assert.equal(remotes[0].url, "https://mcp.zovo.one/mcp/catalogue");
    } else {
      assert.equal(j.remotes, undefined, `${file} is a stdio-only name and must not advertise a remote`);
    }
    assert.ok((j.description ?? "").length < 100, `${file} description is ${(j.description ?? "").length} chars; the registry 422s at 100`);
    assert.ok(!/[,.]\.$|,$/.test(j.description), `${file} description ends in a machine truncation`);
  }
  // Three distinct registry names, so the second and third are second listings, not copies.
  const names = ["server.json", "server.variant.json", "server.rate-card.json"]
    .map((f) => JSON.parse(readFileSync(join(HERE, f), "utf8")).name);
  assert.equal(new Set(names).size, 3, `registry names must differ: ${names.join(", ")}`);
  assert.deepEqual(names, [
    "io.github.theluckystrike/catalogue",
    "io.github.theluckystrike/price-list",
    "io.github.theluckystrike/rate-card",
  ]);

  // And sync-versions --check passes for the whole repo, so no sibling drifted either.
  execFileSync(process.execPath, [join(REPO, "scripts", "sync-versions.mjs"), "--check"], { encoding: "utf8" });
});

test("stdout carries JSON-RPC only across initialize, tools/list, a success and an error", async (t) => {
  const { c } = open(t);
  await c.init();
  await c.tools();
  await c.call("sku_set", { sku: "WEB-AUDIT", name: "Website audit", unit: "each", price_minor: 45000, valid_from: "2026-01-01" });
  await c.call("sku_get", { sku: "NOT-A-CODE" });
  await new Promise((r) => setTimeout(r, 150));

  const lines = [...c.stdoutLines, c.tail].filter((l) => l.trim() !== "");
  assert.ok(lines.length >= 4, `expected at least 4 protocol lines, got ${lines.length}`);
  for (const line of lines) {
    let m;
    try { m = JSON.parse(line); } catch { assert.fail(`non-JSON on stdout: ${JSON.stringify(line.slice(0, 200))}`); }
    assert.equal(m.jsonrpc, "2.0", `stdout line is JSON but not JSON-RPC: ${line.slice(0, 200)}`);
  }
});

test("every tool description is non-empty, single-paragraph, and within the ceiling", async (t) => {
  const { c } = open(t);
  await c.init();
  const tools = await c.tools();
  assert.equal(tools.length, 12, "tool count changed; update servers/catalogue/SPEC.md");
  assert.deepEqual(tools.map((x) => x.name).sort(), [
    "catalogue_report", "license_activate", "license_status", "lines_resolve",
    "price_list_pdf", "price_list_text", "rate_get", "rate_set",
    "sku_delete", "sku_get", "sku_list", "sku_set",
  ]);

  for (const tool of tools) {
    const d = tool.description ?? "";
    assert.ok(d.trim().length > 0, `${tool.name} has no description`);
    assert.equal(d, d.trim(), `${tool.name} description has leading or trailing whitespace`);
    assert.ok(d.length <= HARD_MAX_DESCRIPTION, `${tool.name} description is ${d.length} chars, over ${HARD_MAX_DESCRIPTION}`);
    assert.ok(!/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/u.test(d), `${tool.name} description carries an emoji`);
    assert.ok(!/[—]/.test(d), `${tool.name} description carries an em dash`);
  }

  const over = tools.filter((x) => (x.description ?? "").length > MAX_DESCRIPTION).map((x) => x.name).sort();
  const regressions = over.filter((n) => !OVER_LENGTH_BASELINE.includes(n));
  assert.deepEqual(regressions, [], `new tool descriptions over ${MAX_DESCRIPTION} chars`);
});

test("the one tool that takes a file path says so imperatively, and no other tool takes one", async (t) => {
  const { c } = open(t);
  await c.init();
  const tools = await c.tools();
  const fileTools = tools.filter((x) => Object.keys(x.inputSchema?.properties ?? {}).some((k) => FILE_ARGS.includes(k)));
  assert.deepEqual(fileTools.map((x) => x.name), ["price_list_pdf"]);
  const offenders = fileTools.filter((x) => !IMPERATIVE.test(x.description ?? "")).map((x) => x.name).sort();
  assert.deepEqual(offenders.filter((n) => !NON_IMPERATIVE_BASELINE.includes(n)), []);
});

test("license_status reports free with no key and pro with a signed key", async (t) => {
  const { c: free } = open(t);
  await free.init();
  const f = await free.call("license_status", {});
  assert.equal(f.isError, false, f.text);
  assert.match(f.text, /"tier":\s*"free"/, f.text.slice(0, 300));

  const key = proKey(PRODUCT);
  assert.match(key, /^MCPL1\./);
  const { c: pro } = open(t, { key });
  await pro.init();
  assert.match((await pro.call("license_status", {})).text, /"tier":\s*"pro"/);
});

test("the free tier is the documented one: the catalogue and every text answer are free", async (t) => {
  const { c } = open(t);
  await c.init();
  await seed(c);
  for (const [tool, args] of [
    ["sku_set", { sku: "NEW-ONE", name: "Another product", unit: "each", price_minor: 500, valid_from: "2026-01-01" }],
    ["sku_get", { sku: "WEB-AUDIT", date: RESOLVE_DATE }],
    ["sku_list", {}],
    ["rate_set", { role: "designer", hourly_minor: 6000, valid_from: "2025-01-01" }],
    ["rate_get", {}],
    ["lines_resolve", { lines: LINES, date: RESOLVE_DATE }],
    ["price_list_text", {}],
    ["sku_delete", { sku: "NEW-ONE" }],
  ]) {
    assert.equal((await c.call(tool, args)).isError, false, `${tool} was gated`);
  }
  for (const [tool, args] of [
    ["price_list_pdf", {}],
    ["catalogue_report", {}],
  ]) {
    const r = await c.call(tool, args);
    assert.equal(r.isError, true, `${tool} answered on the free tier`);
    assert.match(r.text, /Pro is a one-time \$\d+ for this server/, tool);
    assert.match(r.text, /license_activate/, tool);
    // The conversion instrument: every gate link carries the tool that tripped it.
    assert.match(r.text, new RegExp(`src=${PRODUCT}\\.${tool}`), `${tool} gate link is untagged`);
  }
});

test("the resource and the prompt are registered and answer", async (t) => {
  const { c } = open(t);
  await c.init();
  const res = (await c.send("resources/read", { uri: "catalogue://price-list" })).result;
  const body = JSON.parse(res.contents[0].text);
  assert.equal(body.default_tier, "standard");
  assert.equal(body.free_tier.skus, 25);
  assert.deepEqual(body.free_tier.pro_tools.sort(), ["catalogue_report", "price_list_pdf"]);
  assert.equal(body.payload_scales.invoice_create, "unit_price in MAJOR units");
  assert.equal(body.payload_scales.quote_create, "unit_price_minor in MINOR units");
  assert.equal(body.creates_invoices, false);
  assert.equal(body.creates_quotes, false);
  assert.equal(body.writes.length, 1);
  assert.equal(body.writes[0].store, "catalogue");
  const prompts = (await c.send("prompts/list", {})).result.prompts;
  assert.deepEqual(prompts.map((p) => p.name), ["price_the_job"]);
});

test("this server writes its own directory and no sibling store, on any tool", async (t) => {
  const { box, c } = open(t, { key: proKey() });
  await c.init();
  await seed(c);
  await c.call("lines_resolve", { lines: LINES, client: "Harbour Cafe", date: RESOLVE_DATE });
  await c.call("price_list_text", {});
  await c.call("price_list_pdf", { date: RESOLVE_DATE });
  await c.call("catalogue_report", {});
  await c.call("sku_set", { sku: "GONE", name: "Temporary", unit: "each", price_minor: 100, valid_from: "2026-01-01" });
  await c.call("sku_delete", { sku: "GONE" });

  const files = readdirSync(storeDir(box.dataHome)).filter((f) => !f.startsWith("."));
  assert.deepEqual(files.sort(), ["counter.json", "pdf", "rates.json", "register.json", "skus.json"]);
  // The shared profile was READ and must be untouched: one file, the one the test wrote.
  const siblings = readdirSync(join(box.dataHome, "mcp-servers")).sort();
  assert.deepEqual(siblings, ["catalogue", "profile"], `a sibling store was created: ${siblings.join(", ")}`);
  assert.deepEqual(readdirSync(join(box.dataHome, "mcp-servers", "profile")), ["business.json"],
    "this server wrote into the shared profile directory; it must only read business.json");
});

test("no price is derived and stored: a SKU record holds its rows and nothing worked out from them", async (t) => {
  const { box, c } = open(t, { key: proKey() });
  await c.init();
  await seed(c);
  await c.call("lines_resolve", { lines: LINES, date: RESOLVE_DATE });
  const raw = readFileSync(join(storeDir(box.dataHome), "skus.json"), "utf8");
  // A derived figure stored under any of these keys is a second copy of what the rows say.
  for (const key of ["price_minor", "current_price", "in_force", "net_minor", "total_minor",
    "vat_minor", "value_minor", "unit_price", "unit_price_minor"]) {
    assert.equal(raw.includes(`"${key}"`), false, `${key} was stored; every price must be derived on the call`);
  }
  const stored = JSON.parse(raw).find((s) => s.sku === "WEB-AUDIT");
  assert.deepEqual(Object.keys(stored).sort(), ["created", "name", "prices", "sku", "unit", "updated", "vat_rate"]);
  assert.deepEqual(Object.keys(stored.prices[0]).sort(), ["amount_minor", "created", "currency", "tier", "valid_from"]);
  assert.equal(stored.prices.length, 3, "the ladder must survive on disk as three rows");
});

test("the money engine is the invoice server's own, not a copy", async () => {
  // If servers/invoice changes its rounding basis, this server must change with it, which
  // it does because it never implements the arithmetic: it imports it.
  const engine = readFileSync(join(HERE, "src", "catalogue.ts"), "utf8");
  assert.match(engine, /import \{[^}]*computeTotals[^}]*\} from "@theluckystrike\/mcp-invoice\/lib";/,
    "the totals must come from the invoice server, never be restated here");
  assert.match(engine, /roundHalfUp/, "the rounding must be the invoice server's roundHalfUp");
  for (const forbidden of [/function roundHalfUp/, /function computeTotals/, /Math\.round\(/]) {
    assert.equal(forbidden.test(engine), false, `src/catalogue.ts reimplements ${forbidden}`);
  }
  const index = readFileSync(join(HERE, "src", "index.ts"), "utf8");
  assert.match(index, /import \{ renderDocPdf \} from "@theluckystrike\/mcp-billing-docs\/lib";/,
    "the A4 renderer must be imported from billing-docs, never reproduced here");
  assert.match(index, /readSharedProfile/, "the default currency must come from the shared business profile");
});

test("src holds no network call and no stdout write", async () => {
  // grep exits 1 on no match, which is the passing case here.
  let raw = "";
  try {
    raw = execFileSync("grep", ["-rEn", "fetch\\(|https?://|node:http|node:net|node:dns|console\\.", join(HERE, "src")], { encoding: "utf8" });
  } catch (e) {
    if (e.status !== 1) throw e;
  }
  const out = raw.trim().split("\n").filter(Boolean);
  const offending = out.filter((l) => !/mcp\.zovo\.one|github\.com|modelcontextprotocol\.io/.test(l));
  assert.deepEqual(offending, [], `network or stdout in src:\n${offending.join("\n")}`);
});

test("the required files are all present", () => {
  for (const f of [
    "package.json", "tsconfig.json", "README.md", "LICENSE", "SPEC.md", "RESULT.md",
    "server.json", "server.mcpb.json", "server.variant.json", "server.rate-card.json",
    "remotes.json", "smithery.yaml", "glama.json", "llms-install.md", "Dockerfile",
    "src/index.ts", "src/lib.ts", "src/catalogue.ts", "src/store.ts", "src/version.ts",
  ]) {
    assert.ok(existsSync(join(HERE, f)), `missing ${f}`);
  }
});

test("every amount the server emits is an integer number of minor units", async (t) => {
  const { c } = open(t, { key: proKey() });
  await c.init();
  await seed(c);
  const got = await c.json("sku_get", { sku: "WEB-AUDIT", date: RESOLVE_DATE });
  assert.ok(Number.isInteger(got.price_minor), `price_minor is not an integer: ${got.price_minor}`);
  const r = await c.json("lines_resolve", { lines: LINES, date: RESOLVE_DATE });
  for (const l of r.lines) {
    assert.ok(Number.isInteger(l.unit_price_minor), JSON.stringify(l));
    assert.ok(Number.isInteger(l.value_minor), JSON.stringify(l));
  }
  for (const k of ["subtotal_minor", "net_minor", "vat_minor", "total_minor"]) {
    assert.ok(Number.isInteger(r.totals[k]), `${k} is not an integer: ${r.totals[k]}`);
  }
  assert.equal(r.totals.net_minor + r.totals.vat_minor, r.totals.total_minor, "net plus VAT does not make the total");
  for (const i of r.quote_create.arguments.items) {
    assert.ok(Number.isInteger(i.unit_price_minor), `quote_create takes MINOR units and got ${i.unit_price_minor}`);
  }
});
