// Contract suite for dunning-letters. Mechanical assertions only.
//
// Asserts the invariants of servers/dunning-letters/SPEC.md that a test can check without
// judgement: one version number across package.json, src/version.ts, serverInfo and all
// three registry manifests; the remotes rule (the mcpb manifest carries remotes.json, the
// stdio-only name carries none); JSON-RPC-only stdout; tool-description hygiene; the
// free/Pro tier switch; that nothing outside this server's own two files is written; and
// that the ladder is anchored to the due date. It never asserts a number a human chose;
// those live in the unit suite.
import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { client, sandbox, cleanup, proKey, storeDir, ACME, REPO } from "./_client.mjs";

const HERE = join(REPO, "servers", "dunning-letters");
const PRODUCT = "dunning-letters";
const MAX_DESCRIPTION = 220;
const HARD_MAX_DESCRIPTION = 1200;
const MANIFESTS = ["server.json", "server.mcpb.json", "server.variant.json"];

/**
 * Tools that already break the description rules on the day this suite was written.
 * The suite is a ratchet: an existing entry is reported, a NEW one fails. The fix is in
 * src, not here.
 */
const OVER_LENGTH_BASELINE = ["chase_today", "invoice_register", "letter_render", "payment_record"];

/** The shared business profile: the letters' sender block reads it, never writes it. */
function writeProfile(dataHome) {
  const dir = join(dataHome, "mcp-servers", "profile");
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, "business.json"), JSON.stringify({
    name: "Nova Studio", address: "ul. Prosta 1, Warsaw", default_currency: "EUR",
    default_tax_rate: 23, payment_terms_days: 14, timezone: "Europe/Warsaw",
  }, null, 2));
}

function open(t, opts = {}) {
  const box = sandbox();
  writeProfile(box.dataHome);
  const c = client({ dataHome: box.dataHome, ...opts });
  t.after(() => { c.close(); cleanup(box.dir); });
  return { box, c };
}

test("the version is one number: package.json, src/version.ts, serverInfo and every manifest agree", async (t) => {
  const pkg = JSON.parse(readFileSync(join(HERE, "package.json"), "utf8"));
  assert.equal(pkg.name, "@theluckystrike/mcp-dunning-letters");
  assert.match(pkg.version, /^\d+\.\d+\.\d+$/, "package version must be a plain semver; the release bump moves it, the test does not pin it");
  assert.ok(pkg.description.length < 100, `package description is ${pkg.description.length} chars`);
  const generated = readFileSync(join(HERE, "src", "version.ts"), "utf8");
  assert.match(generated, /GENERATED by scripts\/sync-versions\.mjs/, "version.ts must be generated, not hand written");
  assert.match(generated, new RegExp(`export const VERSION = "${pkg.version.replace(/\./g, "\\.")}";`),
    `src/version.ts does not carry ${pkg.version}; run node scripts/sync-versions.mjs`);

  const { c } = open(t);
  const info = await c.init();
  assert.equal(info.serverInfo.version, pkg.version, "serverInfo.version must equal the package version");
  assert.equal(info.serverInfo.name, "mcp-dunning-letters");

  for (const file of MANIFESTS) {
    const j = JSON.parse(readFileSync(join(HERE, file), "utf8"));
    assert.equal(j.version, pkg.version, `${file} version`);
    for (const p of j.packages ?? []) {
      assert.equal(p.version, pkg.version, `${file} package entry version`);
      assert.equal(p.transport.type, "stdio", `${file} declares a transport this server does not speak`);
      if (p.registryType === "mcpb") {
        // "TBD" until scripts/manifest-sha256.mjs hashes the built bundle; after that, the
        // real digest. A STALE digest is worse than none.
        assert.ok(p.fileSha256 === "TBD" || /^[0-9a-f]{64}$/.test(p.fileSha256),
          `${file} fileSha256 is neither TBD nor a sha256: ${p.fileSha256}`);
      }
    }
    if (file === "server.mcpb.json") {
      const remotes = JSON.parse(readFileSync(join(HERE, "remotes.json"), "utf8"));
      assert.deepEqual(j.remotes, remotes, `${file} remotes must equal remotes.json (hosted at /mcp/dunning-letters)`);
      assert.equal(remotes[0].url, "https://mcp.zovo.one/mcp/dunning-letters");
    } else {
      assert.equal(j.remotes, undefined, `${file} is a stdio-only name and must not advertise a remote`);
    }
    assert.ok((j.description ?? "").length < 100, `${file} description is ${(j.description ?? "").length} chars; the registry 422s at 100`);
    assert.ok(!/[,.]\.$|,$/.test(j.description), `${file} description ends in a machine truncation`);
    assert.ok(!/\u2014/.test(JSON.stringify(j)), `${file} carries an em dash`);
  }
  assert.ok(existsSync(join(HERE, "remotes.json")), "remotes.json is missing: this server has a hosted route in remote/src/index.ts");

  // server.json and server.mcpb.json share the primary name; the variant is the second listing.
  const names = MANIFESTS.map((f) => JSON.parse(readFileSync(join(HERE, f), "utf8")).name);
  assert.equal(new Set(names).size, 2, `registry names must be one primary and one variant: ${names.join(", ")}`);
  assert.deepEqual(names, [
    "io.github.theluckystrike/dunning-letters",
    "io.github.theluckystrike/dunning-letters",
    "io.github.theluckystrike/overdue-invoice-reminder",
  ]);

  execFileSync(process.execPath, [join(REPO, "scripts", "sync-versions.mjs"), "--check"], { encoding: "utf8" });
});

test("every registry name carries a token this server can actually be found on", () => {
  // Registry search matches a substring of the FULL name and nothing else; the description
  // is never searched. So the tokens this server is meant to be findable on have to be IN
  // the names, and this asserts they are rather than assuming it.
  const joined = MANIFESTS.map((f) => JSON.parse(readFileSync(join(HERE, f), "utf8")).name.toLowerCase()).join(" ");
  for (const token of ["dunning", "letters", "overdue", "invoice", "reminder"]) {
    assert.ok(joined.includes(token), `no registry name carries the token "${token}"`);
  }
});

test("stdout carries JSON-RPC only across initialize, tools/list, a success and an error", async (t) => {
  const { c } = open(t);
  await c.init();
  await c.tools();
  await c.call("invoice_register", ACME);
  await c.call("invoice_status", { invoice: "DUN-2099-0001" });
  await new Promise((r) => setTimeout(r, 150));

  const lines = c.stdoutLines.filter((l) => l.trim() !== "");
  assert.ok(lines.length >= 4, `expected at least 4 protocol lines, got ${lines.length}`);
  for (const line of lines) {
    let m;
    try { m = JSON.parse(line); } catch { assert.fail(`non-JSON on stdout: ${JSON.stringify(line.slice(0, 200))}`); }
    assert.equal(m.jsonrpc, "2.0", `stdout line is JSON but not JSON-RPC: ${line.slice(0, 200)}`);
  }
});

test("every tool description is non-empty, single-paragraph, and within the ceiling", async (t) => {
  const { c } = open(t);
  await c.init();
  const tools = await c.tools();
  assert.equal(tools.length, 11, "tool count changed; update servers/dunning-letters/SPEC.md");
  assert.deepEqual(tools.map((x) => x.name).sort(), [
    "aging_summary", "chase_today", "invoice_delete", "invoice_register", "invoice_status",
    "letter_render", "letter_sent", "license_activate", "license_status",
    "overdue_list", "payment_record",
  ]);

  for (const tool of tools) {
    const d = tool.description ?? "";
    assert.ok(d.trim().length > 0, `${tool.name} has no description`);
    assert.equal(d, d.trim(), `${tool.name} description has leading or trailing whitespace`);
    assert.ok(d.length <= HARD_MAX_DESCRIPTION, `${tool.name} description is ${d.length} chars, over ${HARD_MAX_DESCRIPTION}`);
    assert.ok(!/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/u.test(d), `${tool.name} description carries an emoji`);
    assert.ok(!/\u2014/.test(d), `${tool.name} description carries an em dash`);
  }

  const over = tools.filter((x) => (x.description ?? "").length > MAX_DESCRIPTION).map((x) => x.name).sort();
  assert.deepEqual(over.filter((n) => !OVER_LENGTH_BASELINE.includes(n)), [], `new tool descriptions over ${MAX_DESCRIPTION} chars`);
});

test("no tool takes a file path, so nothing here writes outside its own data directory", async (t) => {
  const { c } = open(t);
  await c.init();
  const tools = await c.tools();
  const FILE_ARGS = ["path", "url", "out_path", "template_path"];
  const fileTools = tools.filter((x) => Object.keys(x.inputSchema?.properties ?? {}).some((k) => FILE_ARGS.includes(k)));
  assert.deepEqual(fileTools.map((x) => x.name), [], "a file-path argument appeared; the letters are returned as text and this server writes no document files");
});

test("license_status reports free with no key and pro with a signed key", async (t) => {
  const { c: free } = open(t);
  await free.init();
  const f = await free.call("license_status", {});
  assert.equal(f.isError, false, f.text);
  assert.match(f.text, /"tier":\s*"free"/, f.text.slice(0, 300));

  const key = proKey(PRODUCT);
  assert.match(key, /^MCPL1\./);
  const { c: pro } = open(t, { key });
  await pro.init();
  assert.match((await pro.call("license_status", {})).text, /"tier":\s*"pro"/);
});

test("a licence for another product does not unlock this one", async (t) => {
  const { c } = open(t, { key: proKey("not-a-real-product") });
  await c.init();
  assert.match((await c.call("license_status", {})).text, /"tier":\s*"free"/);
});

test("the free tier is the documented one: everything but the fourth concurrent chase", async (t) => {
  const { c } = open(t);
  await c.init();
  const reg = await c.json("invoice_register", ACME);
  const id = reg.registered.id;
  for (const [tool, args] of [
    ["letter_render", { invoice: id, format: "markdown" }],
    ["letter_sent", { invoice: id, stage: 1, sent: "2026-06-08" }],
    ["payment_record", { invoice: id, amount_minor: 50000, date: "2026-06-20" }],
    ["overdue_list", { on: "2026-07-01" }],
    ["aging_summary", { on: "2026-07-01" }],
    ["chase_today", { on: "2026-07-01" }],
    ["invoice_status", { invoice: id }],
  ]) {
    const r = await c.call(tool, args);
    assert.equal(r.isError, false, `${tool} was gated: ${r.text}`);
  }
});

test("the free-tier concurrent-chase cap carries the tagged link and the bundle, and nothing is written", async (t) => {
  const { box, c } = open(t);
  await c.init();
  for (let i = 1; i <= 3; i++) await c.json("invoice_register", { ...ACME, reference: `INV-${i}` });
  const r = await c.call("invoice_register", { ...ACME, reference: "INV-4" });
  assert.ok(r.isError, r.text);
  assert.match(r.text, /Pro is a one-time \$\d+ for this server/);
  assert.match(r.text, /license_activate/);
  assert.match(r.text, new RegExp(`src=${PRODUCT}\\.invoice_register`), "the gate link is untagged");
  assert.match(r.text, /buy\/bundle/);
  const invoices = JSON.parse(readFileSync(join(storeDir(box.dataHome), "invoices.json"), "utf8"));
  assert.equal(invoices.length, 3, "the refused fourth chase was written");
});

test("a payment that covers the balance frees the slot on the free tier", async (t) => {
  const { c } = open(t);
  await c.init();
  for (let i = 1; i <= 3; i++) await c.json("invoice_register", { ...ACME, reference: `INV-${i}` });
  assert.equal((await c.call("payment_record", { invoice: "INV-1", amount_minor: ACME.amount_minor, date: "2026-06-20" })).isError, false);
  const again = await c.call("invoice_register", { ...ACME, reference: "INV-4" });
  assert.equal(again.isError, false, `a closed chase did not free its slot: ${again.text}`);
});

test("a byte-identical invoice is refused before the cap is consulted", async (t) => {
  const { c } = open(t);
  await c.init();
  await c.json("invoice_register", ACME);
  const r = await c.call("invoice_register", ACME);
  assert.ok(r.isError, r.text);
  assert.match(r.text, /duplicate_ok/, "the refusal does not name the way through");
});

test("the resource and the prompt are registered and answer", async (t) => {
  const { c } = open(t);
  await c.init();
  const res = (await c.send("resources/read", { uri: "dunning://ladder" })).result;
  const body = JSON.parse(res.contents[0].text);
  assert.deepEqual(body.stages.map((s) => s.stage), [1, 2, 3]);
  assert.equal(body.free_tier.active_unpaid_invoices, 3);
  assert.deepEqual(body.writes[0].files, ["invoices.json", "counter.json"]);
  assert.ok(body.rules.some((r) => /due-anchored/.test(r)), "the due-anchored rule is not stated");
  assert.ok(body.rules.some((r) => /never the previous letter/.test(r)), "the anchoring rule is not stated");
  const prompts = (await c.send("prompts/list", {})).result.prompts;
  assert.deepEqual(prompts.map((p) => p.name), ["weekly_chase"]);
});

test("this server writes two files and no others, on any tool", async (t) => {
  const { box, c } = open(t, { key: proKey() });
  await c.init();
  const reg = await c.json("invoice_register", ACME);
  const id = reg.registered.id;
  await c.call("letter_render", { invoice: id });
  await c.call("letter_render", { invoice: id, format: "html" });
  await c.call("letter_sent", { invoice: id, stage: 1, sent: "2026-06-08" });
  await c.call("payment_record", { invoice: id, amount_minor: 50000, date: "2026-06-20" });
  await c.call("overdue_list", { on: "2026-07-01" });
  await c.call("aging_summary", { on: "2026-07-01" });
  await c.call("chase_today", { on: "2026-07-01" });
  await c.call("invoice_status", { invoice: id });
  const gone = await c.json("invoice_register", { ...ACME, reference: "INV-9999" });
  await c.call("invoice_delete", { invoice: gone.registered.id });

  const files = readdirSync(storeDir(box.dataHome)).filter((f) => !f.startsWith("."));
  assert.deepEqual(files.sort(), ["counter.json", "invoices.json"]);
  const siblings = readdirSync(join(box.dataHome, "mcp-servers")).sort();
  assert.deepEqual(siblings, ["dunning-letters", "profile"], `a sibling store was created: ${siblings.join(", ")}`);
  assert.deepEqual(readdirSync(join(box.dataHome, "mcp-servers", "profile")), ["business.json"],
    "this server wrote into the shared profile directory; it must only read business.json");
});

test("src holds no network call and no stdout write", async () => {
  let raw = "";
  try {
    raw = execFileSync("/usr/bin/grep", ["-rEn", "fetch\\(|https?://|node:http|node:net|node:dns|console\\.", join(HERE, "src")], { encoding: "utf8" });
  } catch (e) {
    if (e.status !== 1) throw e;
  }
  const offending = raw.trim().split("\n").filter(Boolean)
    .filter((l) => !/mcp\.zovo\.one|github\.com|modelcontextprotocol\.io|dunning:\/\//.test(l));
  assert.deepEqual(offending, [], `network or stdout in src:\n${offending.join("\n")}`);
});

test("src, tests and docs carry no em dash and no emoji", () => {
  const files = [
    ...readdirSync(join(HERE, "src")).map((f) => join(HERE, "src", f)),
    ...readdirSync(join(HERE, "test")).map((f) => join(HERE, "test", f)),
    join(HERE, "README.md"), join(HERE, "llms-install.md"), join(HERE, "RESULT.md"), join(HERE, "SPEC.md"),
  ].filter(existsSync);
  for (const f of files) {
    const s = readFileSync(f, "utf8");
    assert.equal(s.includes("\u2014"), false, `${f} carries an em dash`);
    assert.equal(/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/u.test(s), false, `${f} carries an emoji`);
  }
});

test("the required files are all present", () => {
  for (const f of [
    "package.json", "tsconfig.json", "README.md", "LICENSE", "SPEC.md", "RESULT.md",
    "server.json", "server.mcpb.json", "server.variant.json",
    "smithery.yaml", "glama.json", "llms-install.md", "Dockerfile",
    "src/index.ts", "src/engine.ts", "src/letters.ts", "src/lib.ts", "src/store.ts", "src/version.ts",
  ]) {
    assert.ok(existsSync(join(HERE, f)), `missing ${f}`);
  }
});

test("the estate lists this server everywhere a new server has to be registered", () => {
  // The one-line registrations outside this folder. release-check.mjs is the full reader;
  // these are the ones a server cannot ship without, checked here so the omission fails in
  // this suite rather than at bundle time. Copied from the checklist suite, which is where
  // this pattern was established.
  const cases = [
    ["scripts/build-mcpb.sh", /^SERVERS="[^"]*\bdunning-letters\b/m, "SERVERS list"],
    ["scripts/build-mcpb.sh", /^\s*\[dunning-letters\]="/m, "DISPLAY_NAME"],
    ["scripts/build-mcpb.sh", /^\s*\[dunning-letters\]='\[/m, "KEYWORDS"],
    ["scripts/build-pages.mjs", /const ids = \[[^\]]*"dunning-letters"/, "page ids"],
    ["scripts/gen-spec.mjs", /"dunning-letters"/, "SPEC generator"],
    ["servers/office-suite/src/index.ts", /id: "dunning-letters"/, "office-suite CHILDREN"],
    ["servers/invoice/src/index.ts", /"dunning-letters"/, "PROFILE_READERS"],
    ["data/facts.json", /"dunning-letters":/, "facts tagline, which the README table is generated from"],
    ["data/distribution.json", /"dunning-letters":/, "distribution per_server"],
    ["data/tools.json", /"dunning-letters":/, "tools.json, which the storefront tool tables read"],
    ["scripts/sync-mirrors.sh", /^ALL_SERVERS="[^"]*\bdunning-letters\b/m, "ALL_SERVERS"],
    ["scripts/mirror-seo.py", /^\s*"dunning-letters":/m, "mirror-seo CAPABILITY and topics"],
  ];
  for (const [file, re, what] of cases) {
    const src = readFileSync(join(REPO, file), "utf8");
    assert.ok(re.test(src), `${file} does not list dunning-letters in its ${what}`);
  }
});

test("the hosted registration is exactly one of two honest states", () => {
  // The hosted route for this server exists in remote/src/index.ts and the worker deploy is
  // pending (docs/HOSTED_LOOP34.md). data/distribution.json must say one of two things and
  // nothing in between: "none by design" is a narrative from before the route existed and is
  // now stale, but the ONLY string that means live is the exact published URL, because
  // scripts/kpi.mjs counts hosted servers by string match.
  const dist = JSON.parse(readFileSync(join(REPO, "data", "distribution.json"), "utf8"));
  const hosted = String(dist.per_server["dunning-letters"].hosted);
  const published = "published https://mcp.zovo.one/mcp/dunning-letters";
  assert.ok(hosted === published || hosted.startsWith("none by design") || hosted.startsWith("pending deploy:"),
    `distribution.json per_server.dunning-letters.hosted is neither the exact published string nor a none-by-design note: ${hosted}`);
  // And the live-validation remote sweep covers this server, added by the hosting loop.
  const validate = readFileSync(join(REPO, "scripts", "validate.mjs"), "utf8");
  const remoteBlock = validate.slice(validate.indexOf("async function remote()"));
  assert.ok(remoteBlock.includes('"dunning-letters"'), "scripts/validate.mjs remote() does not probe dunning-letters");
});
