// Contract suite for calendar. Mechanical assertions only: the invariants of
// servers/calendar/SPEC.md that a test can check without judgement.
import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { REPO, cleanup, client, proKey, sandbox } from "./_client.mjs";

const PRODUCT = "calendar";
const MAX_DESCRIPTION = 220;
const HARD_MAX_DESCRIPTION = 1200;
const FILE_ARGS = ["path", "url", "out_path", "out_dir", "template_path"];
const IMPERATIVE = /^(Call this tool|Use this)\b/;

/**
 * Tools that already break the two description rules on the day this suite was written.
 * The suite is a ratchet: an existing entry is reported, a NEW one fails. The fix is in
 * src, never here.
 */
const OVER_LENGTH_BASELINE = [];
const NON_IMPERATIVE_BASELINE = [];

const GARBAGE = '{"version":1, <<< truncated by a crash';

test("the version is one number: package.json, src/version.ts and serverInfo agree", async (t) => {
  const here = join(REPO, "servers", PRODUCT);
  const pkg = JSON.parse(readFileSync(join(here, "package.json"), "utf8"));
  const generated = readFileSync(join(here, "src", "version.ts"), "utf8");
  assert.match(generated, /GENERATED by scripts\/sync-versions\.mjs/, "version.ts must be generated, not hand written");
  assert.match(generated, new RegExp(`export const VERSION = "${pkg.version.replace(/\./g, "\\.")}";`),
    `src/version.ts does not carry ${pkg.version}; run node scripts/sync-versions.mjs`);

  const box = sandbox();
  const c = client({ dataHome: box.dataHome });
  t.after(() => { c.close(); cleanup(box.dir); });
  const info = await c.init();
  assert.equal(info.serverInfo.version, pkg.version, "serverInfo.version must equal the package version");
  assert.equal(info.serverInfo.name, `mcp-${PRODUCT}`);

  for (const file of ["server.json", "server.mcpb.json"]) {
    const j = JSON.parse(readFileSync(join(here, file), "utf8"));
    assert.equal(j.version, pkg.version, `${file} version`);
    for (const p of j.packages ?? []) assert.equal(p.version, pkg.version, `${file} package entry version`);
  }
  execFileSync(process.execPath, [join(REPO, "scripts", "sync-versions.mjs"), "--check"], { encoding: "utf8" });
});

test("stdout carries JSON-RPC only across initialize, tools/list and one call", async (t) => {
  const box = sandbox();
  const c = client({ dataHome: box.dataHome });
  t.after(() => { c.close(); cleanup(box.dir); });
  await c.init();
  await c.tools();
  await c.call("calendars_list", {});
  await new Promise((r) => setTimeout(r, 150));

  const lines = [...c.stdoutLines, c.tail].filter((l) => l.trim() !== "");
  assert.ok(lines.length >= 3, `expected at least 3 protocol lines, got ${lines.length}`);
  for (const line of lines) {
    let m;
    try { m = JSON.parse(line); } catch { assert.fail(`non-JSON on stdout: ${JSON.stringify(line.slice(0, 200))}`); }
    assert.equal(m.jsonrpc, "2.0", `stdout line is JSON but not JSON-RPC: ${line.slice(0, 200)}`);
  }
});

test("every tool description is non-empty, single-paragraph, and within the hard ceiling", async (t) => {
  const box = sandbox();
  const c = client({ dataHome: box.dataHome });
  t.after(() => { c.close(); cleanup(box.dir); });
  await c.init();
  const tools = await c.tools();
  assert.equal(tools.length, 12, `tool count changed; update servers/${PRODUCT}/SPEC.md`);

  for (const tool of tools) {
    const d = tool.description ?? "";
    assert.ok(d.trim().length > 0, `${tool.name} has no description`);
    assert.equal(d, d.trim(), `${tool.name} description has leading or trailing whitespace`);
    assert.ok(d.length <= HARD_MAX_DESCRIPTION, `${tool.name} description is ${d.length} chars, over the hard ceiling ${HARD_MAX_DESCRIPTION}`);
    assert.ok(!/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/u.test(d), `${tool.name} description carries an emoji`);
  }

  const over = tools.filter((x) => (x.description ?? "").length > MAX_DESCRIPTION).map((x) => x.name).sort();
  const regressions = over.filter((n) => !OVER_LENGTH_BASELINE.includes(n));
  assert.deepEqual(regressions, [], `new tool descriptions over ${MAX_DESCRIPTION} chars`);
  assert.equal(over.length, 0, `${over.length} tool descriptions over ${MAX_DESCRIPTION} chars: ${over.join(", ")}`);
  const fixed = OVER_LENGTH_BASELINE.filter((n) => !over.includes(n));
  if (fixed.length) t.diagnostic(`now within ${MAX_DESCRIPTION} chars, drop from the baseline: ${fixed.join(", ")}`);
});

test("a tool that takes a file path or a URL opens with an imperative sentence", async (t) => {
  const box = sandbox();
  const c = client({ dataHome: box.dataHome });
  t.after(() => { c.close(); cleanup(box.dir); });
  await c.init();
  const tools = await c.tools();

  const fileTools = tools.filter((x) => Object.keys(x.inputSchema?.properties ?? {}).some((k) => FILE_ARGS.includes(k)));
  assert.ok(fileTools.length > 0, "expected at least one file/URL tool");
  const offenders = fileTools.filter((x) => !IMPERATIVE.test(x.description ?? "")).map((x) => x.name).sort();
  const regressions = offenders.filter((n) => !NON_IMPERATIVE_BASELINE.includes(n));
  assert.deepEqual(regressions, [], 'new file/URL tools whose description does not start with "Call this tool" or "Use this"');
  assert.equal(offenders.length, 0, `${offenders.length} file/URL tool descriptions do not open with an imperative: ${offenders.join(", ")}`);
  const fixed = NON_IMPERATIVE_BASELINE.filter((n) => !offenders.includes(n));
  if (fixed.length) t.diagnostic(`now imperative, drop from the baseline: ${fixed.join(", ")}`);
});

test("corrupt store: the garbage is quarantined byte-for-byte and nothing is overwritten", async (t) => {
  const box = sandbox();
  const dir = join(box.dataHome, "mcp-servers", PRODUCT);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, "data.json"), GARBAGE);

  const c = client({ dataHome: box.dataHome });
  t.after(() => { c.close(); cleanup(box.dir); });
  await c.init();
  const r = await c.call("events_list", { from: "2026-01-01", to: "2026-01-31" });
  assert.equal(r.isError, true, `a corrupt store must refuse, not succeed: ${r.text.slice(0, 300)}`);
  assert.match(r.text, /corrupt|not valid JSON/i, r.text.slice(0, 300));

  const moved = readdirSync(dir).filter((f) => f.startsWith("data.json.corrupt-"));
  assert.equal(moved.length, 1, `expected one quarantined copy, found ${JSON.stringify(readdirSync(dir))}`);
  assert.equal(readFileSync(join(dir, moved[0]), "utf8"), GARBAGE, "the quarantined copy must be the original bytes");
  assert.equal(readdirSync(dir).includes("data.json"), false, "an empty store must not be written over the corrupt one");
  assert.ok(readdirSync(dir).includes("data.json.corrupt"), "the marker that blocks every later call must exist");
});

test("cap: the third calendar is refused and nothing is added to the store", async (t) => {
  const box = sandbox();
  const c = client({ dataHome: box.dataHome });
  t.after(() => { c.close(); cleanup(box.dir); });
  await c.init();

  const ics = (uid) => [
    "BEGIN:VCALENDAR", "VERSION:2.0", "PRODID:-//contract//EN", "BEGIN:VEVENT",
    `UID:${uid}@contract`, "DTSTART:20260310T090000Z", "DTEND:20260310T100000Z",
    "SUMMARY:Standup", "END:VEVENT", "END:VCALENDAR",
  ].join("\r\n");

  for (const n of ["one", "two"]) {
    const r = await c.call("ics_import", { name: n, text: ics(n) });
    assert.equal(r.isError, false, r.text.slice(0, 300));
  }
  const third = await c.call("ics_import", { name: "three", text: ics("three") });
  assert.match(third.text, /free/i, third.text.slice(0, 300));

  const dir = join(box.dataHome, "mcp-servers", PRODUCT);
  const db = JSON.parse(readFileSync(join(dir, "data.json"), "utf8"));
  assert.deepEqual(Object.keys(db.calendars ?? {}).sort(), ["one", "two"],
    "the refused import must add nothing: no third calendar, no partial record");
  assert.equal(readdirSync(dir).filter((f) => f.includes(".tmp")).length, 0, "no tmp file may survive a refusal");
});

test("license_status reports free with no key and pro with a signed key", async (t) => {
  const a = sandbox();
  const free = client({ dataHome: a.dataHome });
  t.after(() => { free.close(); cleanup(a.dir); });
  await free.init();
  const f = await free.call("license_status", {});
  assert.equal(f.isError, false, f.text);
  assert.match(f.text, /"tier":\s*"free"/, f.text.slice(0, 300));

  const key = proKey(PRODUCT);
  assert.match(key, /^MCPL1\./);
  const b = sandbox();
  const pro = client({ dataHome: b.dataHome, key });
  t.after(() => { pro.close(); cleanup(b.dir); });
  await pro.init();
  const p = await pro.call("license_status", {});
  assert.equal(p.isError, false, p.text);
  assert.match(p.text, /"tier":\s*"pro"/, p.text.slice(0, 300));

  // A key signed for another product must not unlock this one.
  const d = sandbox();
  const other = client({ dataHome: d.dataHome, key: proKey("not-a-real-product") });
  t.after(() => { other.close(); cleanup(d.dir); });
  await other.init();
  const o = await other.call("license_status", {});
  assert.match(o.text, /"tier":\s*"free"/, o.text.slice(0, 300));
});
